lib/src/util/prop_errors.dart
lib/src/util/react_wrappers.dart
test/over_react/util/constants_base_test.dart
test/over_react/util/dom_util_test.dart
test/over_react/util/event_helpers_test.dart
test/over_react/util/guid_util_test.dart
test/over_react_test.dart

Our coverage was only at 92% and we were missing some easy test coverage.
- Add missing tests
- Remove left over deprecated code
- Verify that tests pass
- Verify that coverage is ~97%
- Removed deprecated code
--
FYA: @aaronlademann-wf @greglittlefield-wf @clairesarsam-wf @joelleibow-wf

Add missing coverage

---

README.md
pubspec.yaml

Bump version to 1.1.0

---

README.md
pubspec.yaml

Self explanatory
---
> __FYA:__ @greglittlefield-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf

Update version strings for 1.1.1

---

aviary.yaml

Create aviary.yaml for over_react with an empty policy.
N/A
None
---
Please code review and merge if you deem this policy appropriate.  Thanks!

RED-1195: Create aviary.yaml for over_react

---

.gitignore
CHANGELOG.md
README.md
pubspec.yaml
smithy.yaml

Self explanatory.
Release notes are present in the updated CHANGELOG file.
---

UIP-1828 Release over_react 1.3.0

---

.analysis_options
CHANGELOG.md
README.md
pubspec.yaml

Self explanatory.
Release notes are present in the updated CHANGELOG file.
---

UIP-1850 Release over_react 1.4.0

---

CHANGELOG.md
README.md
pubspec.yaml
smithy.yaml
test/over_react_component_declaration_test.dart
test/over_react_component_declaration_test.html
test/over_react_component_test.dart
test/over_react_component_test.html
test/over_react_util_test.dart
test/over_react_util_test.html
tool/dev.dart

Self explanatory.
Release notes are present in the updated CHANGELOG file.
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf @kaanaksoy-wk

UIP-1955: Release over_react 1.6.0

---

CHANGELOG.md
pubspec.yaml

__This patch release includes the following changes:__
- https://github.com/Workiva/over_react/commit/2ff10983724fec4d86dd2063ad1f4664da8160cb analyzer `>=0.27.0 <0.31.0` (was `>=0.27.0 <0.30.0`) ([UIP-2287](https://jira.atl.workiva.net/browse/UIP-2287))

WP-4048 UIP-2262 Release over_react 1.9.2

---

README.md

Add callout to new [VS Code snippet extension](https://marketplace.visualstudio.com/items?itemName=JaceHensley.over-react-snippets)
---

Add callout to VS Code Snippet extension

---

lib/src/util/handler_chain_util.dart
test/over_react/util/handler_chain_util_test.dart

Pretty self explanatory.
---
> __FYA:__ @greglittlefield-wf @jacehensley-wf @clairesarsam-wf

UIP-2740 Add 4-argument callback utils

---

CHANGELOG.md
README.md
pubspec.yaml

* #115 Add 4-argument callback utils
---
> __FYA:__ @greglittlefield-wf @jacehensley-wf @clairesarsam-wf

UIP-2648 Release over_react 1.17.0

---

CHANGELOG.md
README.md
pubspec.yaml

* #128: Add `UiPropsMapView`.
__Misc__
* #129: Add CODEOWNERS file.
---
> __FYA:__ @greglittlefield-wf @jacehensley-wf @clairesarsam-wf

UIP-2912 Release over_react 1.20.0

---

CHANGELOG.md
README.md
pubspec.yaml

> [Complete `1.22.0` Changeset](https://github.com/Workiva/over_react/compare/1.21.0...Workiva:release_over_react_1_22_0)
* [#142]: Do not execute prop validation logic in dart2js code
__FYA__ @Workiva/ui-platform-pp @corwinsheahan-wf @evanweible-wf @sebastianmalysa-wf

UIP-3052 Release over_react 1.22.0

---

CHANGELOG.md
pubspec.yaml

WP-6108 UIP-3085 Release over_react 1.23.0

---

lib/src/component_declaration/component_base.dart

https://github.com/Workiva/over_react/pull/155 did much of the work around cleaning up our internal Map classes, and there were just a few more things left that could be removed, which is this PR.
Testing (in Dart 2):
- Verify that the example `pub build`s with no compile-time errors
- Verify that the example has no compile-time or runtime errors in the DDC

Clean up the rest of the Map grossness left over from DDC workarounds

---

lib/src/util/react_wrappers.dart

Pretty self-explanatory.
---
> __FYA:__ @greglittlefield-wf @kealjones-wk @evanweible-wf @maxwellpeterson-wf

AF-1247 Make getDartComponent generic

---

CHANGELOG.md

CPLAT-4124: Changelog for V2

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/1.31.0...Workiva:release_over_react_2.0.0-alpha.dart1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/1.31.0...2.0.0-alpha.dart1

CPLAT-4146 CPLAT-4145 Release over_react 2.0.0-alpha.dart1

---

pubspec.yaml

* [CPLAT-4154: Widen `over_react_test` range](https://github.com/Workiva/over_react/pull/238)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.0.0-alpha...Workiva:release_over_react_2.0.0-dart1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.0.0-alpha...2.0.0-dart1

CPLAT-4163 CPLAT-4162 Release over_react 2.0.0-dart1

---

pubspec.yaml

* [CPLAT-4160 v2.0.0 (Dart 2)](https://github.com/Workiva/over_react/pull/240)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.0.0-dart1...Workiva:release_over_react_2.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.0.0-dart1...2.0.0

CPLAT-4161 CPLAT-4160 Release over_react 2.0.0

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.0.0...Workiva:release_over_react_2.0.0+dart1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.0.0...2.0.0+dart1

CPLAT-4208 CPLAT-4207 Release over_react 2.0.0+dart1

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.0.0...Workiva:release_over_react_2.0.0+dart2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.0.0...2.0.0+dart2

CPLAT-4206 CPLAT-4205 Release over_react 2.0.0+dart2

---

pubspec.yaml

Requested by: @corwinsheahan-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.0.0...Workiva:release_over_react_2.1.0+dart1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.0.0...2.1.0+dart1

CPLAT-4214 CPLAT-4213 Release over_react 2.1.0+dart1

---

CONTRIBUTING.md
pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.1.0...Workiva:release_over_react_2.1.0+dart2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.1.0...2.1.0+dart2

CPLAT-4733 CPLAT-4732 Release over_react 2.1.0+dart2

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/1.32.0...Workiva:release_over_react_2.2.0+dart1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/1.32.0...2.2.0+dart1

CPLAT-4735 CPLAT-4734 Release over_react 2.2.0+dart1

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/1.33.0...Workiva:release_over_react_2.3.0+dart1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/1.33.0...2.3.0+dart1

CPLAT-4830 CPLAT-4829 Release over_react 2.3.0+dart1

---

CHANGELOG.md
lib/over_react.dart
lib/src/component/error_boundary.dart
lib/src/component/error_boundary.over_react.g.dart
pubspec.yaml
test/over_react/component/error_boundary_test.dart
test/over_react_component_test.dart

Brings #266 into the `+dart2` line-of-release.
@greglittlefield-wf @kealjones-wk

CPLAT-4837, CPLAT-4838 Release over_react 2.3.0+dart2

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/1.33.1...Workiva:release_over_react_2.3.1+dart1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/1.33.1...2.3.1+dart1

CPLAT-4895 CPLAT-4894 Release over_react 2.3.1+dart1

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.3.1+dart2...Workiva:release_over_react_2.4.0+dart1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.3.1+dart2...2.4.0+dart1

CPLAT-4954 CPLAT-4953 Release over_react 2.4.0+dart1

---

CHANGELOG.md
pubspec.yaml

* [CPLAT-3300: CP Code Review and PR Merging Team agreement update](https://github.com/Workiva/over_react/pull/277)
* [CPLAT-5152: Optimize builder's use of asset reads to avoid unnecessary rebuilds](https://github.com/Workiva/over_react/pull/280)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.3.1+dart2...Workiva:release_over_react_2.4.0+dart2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.3.1+dart2...2.4.0+dart2

CPLAT-4956 CPLAT-4955 Release over_react 2.4.0+dart2

---

pubspec.yaml
test/over_react/component_declaration/redux_component_test/test_reducer.g.dart
test/vm_tests/builder/declaration_parsing_test.dart

> _Depends on these three PRs:_
> - https://github.com/Workiva/over_react/pull/280
> - https://github.com/Workiva/dart_transformer_utils/pull/31
> - https://github.com/davidmarne/built_redux/pull/117
The latest versions of the `build_*` packages require at least analyzer v0.35.0 (and will presumably soon start requiring v0.36.0 that was released about a week ago).
Upgrade the `analyzer` dependency to `^0.35.0`.
_**Note: it is safe to upgrade the minimum to `^0.35.0` because this change is only being made on the dart2-only release line. Consumers of the dart1 version of over_react 2.x will not be constrained by this change.**_
Upgrade to `analyzer: ^0.35.0`. …

CPLAT-4003 Upgrade to analyzer ^0.35.0

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/1.33.2...Workiva:release_over_react_2.4.2+dart1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/1.33.2...2.4.2+dart1

CPLAT-5279 CPLAT-5278 Release over_react 2.4.2+dart1

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.4.2+dart2...Workiva:release_over_react_2.4.3+dart1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.4.2+dart2...2.4.3+dart1

CPLAT-5791 CPLAT-5790 Release over_react 2.4.3+dart1

---

.travis.yml
Dockerfile
pubspec.yaml
tool/generate_coverage.sh

We want to make sure over_react works with the latest analyzer and we want to upgrade to the latest build packages.
- Widen `analyzer` range to include 0.36.x
- Upgrade to `build_web_compilers` 2.x
- Remove the `coverage` dep and the `generate_coverage.sh` script as they currently don't work on dart2

CPLAT-6244: DO NOT MERGE: Upgrade to analyzer 0.36.x and build_web_compilers 2.x

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.4.3+dart2...Workiva:release_over_react_2.4.4+dart1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.4.3+dart2...2.4.4+dart1

RM-53252 RM-53251 Release over_react 2.4.4+dart1

---

CHANGELOG.md
pubspec.yaml

This release includes:
* #327 Add support for `SyntheticAnimationEvent` / `SyntheticTransitionEvent`
@kealjones-wk @greglittlefield-wf

RM-53702 Release over_react 2.5.0+dart2

---

lib/over_react.dart

The `TypedSnapshot` mixin from `package:react/react.dart` is a core piece used by `UiComponent2` - but currently, consumers have to import `package:react/react.dart` in order to utilize it, which is not ideal.
Export `TypedSnapshot` from `package:over_react/over_react.dart`.
Export the `TypedSnapshot` mixin from `over_react.dart`.
Please review: @greglittlefield-wf @joebingham-wk @kealjones-wk @sydneyjodon-wk  …

Export TypedSnapshot

---

lib/src/component/prop_mixins.dart
lib/src/component/prop_mixins.over_react.g.dart

We need to update the typing of SVG attributes because they are currently all typed as `dynamic`.
Update typing of SVG attributes based on specified attribute typing listed in the following:
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2210
- https://github.com/facebook/react/blob/16.8.6/packages/react-dom/src/shared/DOMProperty.js#L262
@kealjones-wk @aaronlademann-wf @greglittlefield-wf @joebingham-wk  …

CPLAT-7675 Update existing SvgProps typing

---

pubspec.yaml

Pulls included in this __Dart 1 only (alpha)__ release:
---

RM-58743 Release over_react 3.0.0-alpha.1+dart1

---

pubspec.yaml

Upper bounds of the `analyzer` version need to be increased so that we aren't prevented from pulling newer versions of packages (e.g., `build_web_compilers`) that depend on newer versions of `analyzer`.
- Update `Analyzer` dependency.
- Increase the `analyzer` dependency upper bound to ensure the package can consume the latest version of other dependencies. 
@aaronlademann-wf @greglittlefield-wf @kealjones-wk @sydneyjodon-wk
- Pull down branch.
- Upgrade analyzer.
- Verify it resolves to `0.38.5` and there are no static errors. …

Bump analyzer top constraint

---

pubspec.yaml

DPC needs to  use analyzer `0.31.1` to generate their redux files on Dart 1. This prevents them from having to use a dependency override to accomplish that goal.
Bump analyzer range to include `0.31.1`. This was originally excluded to help build times, but is no longer an issue since we can use Dart 2's pub.

[Dart 1] Widen analyzer constraint

---

lib/over_react.dart
lib/src/component/error_boundary.dart
test/over_react/component/error_boundary_test.dart

[Dart 1] CPLAT-7836 Add error logging to ErrorBoundary

---

CHANGELOG.md
pubspec.yaml

This Dart 2 only __alpha__ release of over_react includes:
---

RM-59382 Release over_react 3.0.0-alpha.3+dart2

---

lib/src/component/prop_mixins.dart
lib/src/component/prop_mixins.over_react.g.dart

We need to update the typing of DomProps attributes because many are currently typed as `dynamic`.
Update typing of DomProps attributes based on specified attribute typing listed in the following:
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2210
- https://github.com/facebook/react/blob/16.8.6/packages/react-dom/src/shared/DOMProperty.js#L262
@kealjones-wk @aaronlademann-wf @greglittlefield-wf @joebingham-wk  …

CPLAT-7860 Update Existing DomProps Typing

---

README.md

Readme boilerplate templates don't include a necessary part declaration.
Add part declaration to boilerplate in README.md
Add part declaration to boilerplate in README.md

Add part declaration to boilerplate in README.md

---

CHANGELOG.md
analysis_options.yaml
lib/over_react.dart
lib/src/util/safe_render_manager/safe_render_manager.dart
lib/src/util/safe_render_manager/safe_render_manager_helper.dart
lib/src/util/safe_render_manager/safe_render_manager_helper.over_react.g.dart
pubspec.yaml
test/over_react/util/safe_render_manager/safe_render_manager_helper_test.dart
test/over_react/util/safe_render_manager/safe_render_manager_test.dart
test/over_react/util/safe_render_manager/test_component.dart
test/over_react/util/safe_render_manager/test_component.over_react.g.dart
test/over_react_util_test.dart

This Dart 2 only __stable__ release of over_react includes:
* #390 Add new SafeRenderManager utility
---

RM-59768 Release over_react 2.7.0+dart2

---

web/component2/src/demo_components/button.dart
web/component2/src/demo_components/button_group.dart
web/component2/src/demo_components/list_group.dart
web/component2/src/demo_components/list_group_item.dart
web/component2/src/demo_components/progress.dart
web/component2/src/demo_components/prop_validation_wrap.dart
web/component2/src/demo_components/tag.dart
web/component2/src/demo_components/toggle_button.dart
web/component2/src/demo_components/toggle_button_group.dart
web/component2/src/demos/custom_error_boundary.dart

Examples in web/component2 were all broken due to new `defaultProps` and `initialState` syntax, this updates the components using the latest codemod release
- ran codemod updated web/component2 components

Update Component2 web example components

---

CHANGELOG.md
pubspec.yaml

* [CPLAT-8499 OverReactRedux: fix bug and make error messages more verbose](https://github.com/Workiva/over_react/pull/423)
* [CPLAT-8603 Add Multiple Error Check to ErrorBoundary](https://github.com/Workiva/over_react/pull/432)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/3.1.4...Workiva:release_over_react_3.1.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/3.1.4...3.1.5

RM-61541 RM-61540 Release over_react 3.1.5

---

README.md

UiComponent links did not work in documentation
Updated links in README.md
Update links to UiComponent2 in README.md

Changed links from UiComponent to UiComponent2

---

lib/src/component_declaration/component_base.dart
test/over_react/component_declaration/redux_component_test/test_reducer.g.dart

There's a chunk of dead code that call Function.apply(...) which can be expensive for dart2js to optimize. Quick tests of removing this code makes compiling wdesk 30s faster. Not bad for unused code!
Remove the block of unused code.

Remove dead code & help dart2js compile perf

---

CHANGELOG.md
pubspec.yaml

* [Changed links from UiComponent to UiComponent2](https://github.com/Workiva/over_react/pull/430)
* [Fixed typo in builder README.md](https://github.com/Workiva/over_react/pull/431)
* [Remove dead code & help dart2js compile perf](https://github.com/Workiva/over_react/pull/436)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/3.1.5...Workiva:release_over_react_3.1.6
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/3.1.5...3.1.6

RM-62606 RM-62605 Release over_react 3.1.6

---

.travis.yml
Dockerfile
pubspec.yaml

Dart 2.4 and I do not get along.
- Threw Dart 2.4 to the curb in `.travis.yaml`
- Updated `dockerfile` to use `google/dart:2.6`

CPLAT-8863 Remove Dart 2.4 from CI

---

web/component2/index.dart
web/component2/index.html
web/component2/src/demos.dart
web/component2/src/demos/return-types/fragment_example_component.dart
web/component2/src/demos/return-types/fragment_example_component.over_react.g.dart
web/component2/src/demos/return-types/list_example_component.dart
web/component2/src/demos/return-types/list_example_component.over_react.g.dart
web/component2/src/demos/return-types/num_example_component.dart
web/component2/src/demos/return-types/num_example_component.over_react.g.dart
web/component2/src/demos/return-types/string_example_component.dart
web/component2/src/demos/return-types/string_example_component.over_react.g.dart

While working on the React 16 presentation, we were adding examples of the new possible return types for a component. To test them and make sure they were valid as expected, they were made in over_react. Thought we might as well save the work and add the examples in!
- Add examples for `Fragment`, and `List`, `num`, and `String` return types.
- Add return type examples.
@kealjones-wk @greglittlefield-wf @aaronlademann-wf @sydneyjodon-wk  …

Add Some New Examples

---

CHANGELOG.md
pubspec.yaml

* [CPLAT-9796 HOC type checking fixes and improvements](https://github.com/Workiva/over_react/pull/464)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/3.2.1...Workiva:release_over_react_3.3.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/3.2.1...3.3.0

RM-67773 RM-67772 Release over_react 3.3.0

---

CHANGELOG.md
pubspec.yaml

* [CPLAT-8693 Finalize `connect` for w_flux](https://github.com/Workiva/over_react/pull/459)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/3.3.0...Workiva:release_over_react_3.4.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/3.3.0...3.4.0

RM-67996 RM-67995 Release over_react 3.4.0

---

CHANGELOG.md
pubspec.yaml

* [Allow redux.dart version 4](https://github.com/Workiva/over_react/pull/468)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/3.4.0...Workiva:release_over_react_3.4.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/3.4.0...3.4.1

RM-68200 RM-68199 Release over_react 3.4.1

---

README.md
doc/built_redux_to_redux.md
doc/flux_to_redux.md
doc/over_react_redux_documentation.md
lib/src/component/ref_util.dart
lib/src/component_declaration/annotations.dart
lib/src/component_declaration/builder_helpers.dart
lib/src/component_declaration/component_base.dart
lib/src/component_declaration/component_base_2.dart
lib/src/component_declaration/component_type_checking.dart
lib/src/util/typed_default_props_for.dart
web/component1/src/demo_components/button_group.dart

In preparation for the boilerplate changes, the comments and docs need to be updated to reflect the upcoming change.
- Update doc examples
- Update `annotations.dart` to reflect the optional nature of the annotations
- Remove references to the annotations in API doc comments
@aaronlademann-wf @greglittlefield-wf @sydneyjodon-wk @willdrach-wk 
- None!
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual- …

CPLAT-9776 Update Boilerplate Examples

---

lib/src/builder/generation/parsing/members/component.dart
test/vm_tests/builder/parsing/member_association_test.dart
test/vm_tests/builder/parsing/members_test.dart
test/vm_tests/builder/parsing/parsing_version_test.dart
test/vm_tests/builder/parsing/util_test.dart
test/vm_tests/builder/parsing/validation_test.dart
test/vm_tests/builder/parsing_version_test.dart

Test coverage is needed for the utilities added to the new parser.

Add Tests for Utilities

---

README.md
doc/new_boilerplate_migration.md

- Add notes about ignoring the uri_has_not_been_generated error (similar to [how Angular did it](https://github.com/dart-lang/angular/blob/d2e4c599ab5a3ee0544d8c639a4de4e011b14517/doc/migrating-to-v5.md#adjust-analysis_optionsyaml))
- in the over_react readme 
- in the boilerplate upgrade guide 
- To help Workiva devs, also mention that it's also ignored by default in [workiva_analysis_options](https://github.com/Workiva/workiva_analysis_options).
- Update new boilerplate migration guide.
- Add note to readme.
Please review: @joebingham-wk @greglittlefield-wf @aaronlademann-wf 
While we perform many automated checks before auto-merging, some manual checks are …

CPLAT-10334 Add notes about ignoring uri_has_not_been_generated errors

---

CHANGELOG.md
pubspec.yaml

Diff: https://github.com/Workiva/over_react/compare/3.5.0...release-over_react-3.5.1

RM-72168 RM-72167 Release over_react 3.5.1

---

pubspec.yaml

* [CPLAT-11102: Widen analyzer range to include 0.39.x](https://github.com/Workiva/over_react/pull/494)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/3.5.1...Workiva:release_over_react_3.5.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/3.5.1...3.5.2

RM-74102 RM-74101 Release over_react 3.5.2

---

lib/src/component_declaration/flux_component.dart

The example for `FluxUiPropsMixin` was just missing the `$FluxUiPropsMixin`.
- Add `$FluxUiPropsMixin` to the example
@aaronlademann-wf @greglittlefield-wf @sydneyjodon-wk 

Update FluxUiPropsMixin example

---

lib/src/over_react_redux/devtools/middleware.dart

`handleEventFromRemote` is a function that gets passed to javascript but it was not wrapped with `allowInterop`.
- Wrap `handleEventFromRemote` in `allowInterop`

wrap OverReactReduxDevToolsMiddleware's handleEventFromRemote with allowInterop

---

tools/analyzer_plugin/lib/src/diagnostic/missing_required_prop.dart

downgrade required prop to info

---

tools/analyzer_plugin/lib/src/diagnostic/duplicate_prop_cascade.dart

We should retain the last duplicate prop in a prop cascade
Flag every duplicate prop except for the last instance.

Warn for all except last duplicate prop

---

tools/analyzer_plugin/lib/src/plugin.dart

Temporarily disable missing required props lint

---

tools/analyzer_plugin/playground/README.md
tools/analyzer_plugin/playground/analysis_options.yaml
tools/analyzer_plugin/playground/web/dom_prop_types.dart

See: the commit messages
Closes #561

Misc analyzer plugin playground cleanup

---

tools/analyzer_plugin/lib/src/assist/refs/add_create_ref.dart
tools/analyzer_plugin/lib/src/util/ast_util.dart

Fix misc. null exceptions encountered while testing

---

lib/src/component/with_transition.over_react.g.dart
test/over_react/component/with_transition_test.over_react.g.dart

Just checking in generated files!

Check in changed generated files

---

pubspec.yaml

React-dart 5.6.1 includes the chrome 86 workaround in `react.js`. Many consumers don't use `react` directly, but instead use `over_react`. 
Bump the `react` minimum here so that we can have a version of over_react which ensures the workaround is present in `react.js`.

bump react to 5.6.1

---

lib/over_react.dart
pubspec.yaml

In React.dart, new event helper APIs were added. Just like the synthetic event classes, we should export these to make them easy to use.
- Bump minimum React version to `5.7.0`
- Export all of the new event APIs

Expose new event helper APIs

---

CHANGELOG.md
pubspec.yaml
tools/analyzer_plugin/pubspec.yaml

* [Expose new event helper APIs](https://github.com/Workiva/over_react/pull/641)
Requested by: @joebingham-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/3.11.0...Workiva:release_over_react_3.12.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/3.11.0...3.12.0

RM-87645 RM-87644 Release over_react 3.12.0

---

lib/src/util/event_helpers.dart
test/over_react/util/event_helpers_test.dart

An upcoming release of react-dart (v6.0.0) will change behavior around react-dart's `SyntheticEvent` wrappers. For more information, see [this blog post](https://wiki.atl.workiva.net/display/CP/2020/11/11/The+Road+to+MUI%3A+New+%60SyntheticEvent%60+Behavior+and+Component+Parity+Updates). This PR intends to fix forward and make updating to react-dart 6.0.0 (which will have React 17), as seamless as possible.
- Switch out any event invocations with `createSynthetic{X}Event` …

CPLAT-12547 Remove event invocations

---

README.md

When the component boilerplate is copied to a repo with the [`always_declare_return_types`](https://dart-lang.github.io/linter/lints/always_declare_return_types.html) lint enabled, there is an analyzer warning on all the methods without return types.
Add return types to the component boilerplate.

Add return types to component boilerplate

---

.github/workflows/dart_ci.yml

GitHub actions currently only runs on PRs to master, and not wip branches
- Update config to run on all PRs
- Also run on consumption branches so that we don't need PRs for react-dart consumer tests

Update GitHub Actions to run on all PRs and also consumption branches

---

app/over_react_redux/todo_client/pubspec.yaml
pubspec.yaml

As soon as we set the core check to no longer be dry-run, over_react will fail because there are usages of all the different boilerplate syntaxes. Therefore, we should disable the corecheck to prevent our CIs from failing.
- Opt out of react_boilerplate core-check

Opt main lib out of react_boilerplate core-check

---

CHANGELOG.md
pubspec.yaml
tools/analyzer_plugin/pubspec.yaml

* [CPLAT-12196: @Component2 annotation parity for function components](https://github.com/Workiva/over_react/pull/655)
* [Consume setup-dart 0.2 action](https://github.com/Workiva/over_react/pull/673)
* [CPLAT-11863 Add Redux Hooks](https://github.com/Workiva/over_react/pull/674)
* [Dart SDK 2.9+ boilerplate compatibility](https://github.com/Workiva/over_react/pull/679)
Requested by: @joebingham-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.0.0...Workiva:release_over_react_4.1.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.0.0...4.1.0
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/6449952306233344/ …

RM-93430 RM-93429 Release over_react 4.1.0

---

CHANGELOG.md
pubspec.yaml
tools/analyzer_plugin/pubspec.yaml

* [CPLAT-15063 Conditionally unconvert style and children props](https://github.com/Workiva/over_react/pull/698)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.1.2...Workiva:release_over_react_4.1.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.1.2...4.1.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?pull_number=700&repo_name=Workiva%2Fover_react)

RM-109912 RM-109911 Release over_react 4.1.3

---

lib/src/component_declaration/component_type_checking.dart
test/over_react/component_declaration/component_type_checking_test.dart

Support type-checking directly from the UiFactory to better support JS components

---

pubspec.yaml
tools/analyzer_plugin/pubspec.yaml

* [Support type-checking directly from the UiFactory to better support JS components](https://github.com/Workiva/over_react/pull/710)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.2.3...Workiva:release_over_react_4.2.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.2.3...4.2.4
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?pull_number=712&repo_name=Workiva%2Fover_react)

RM-116081 RM-116080 Release over_react 4.2.4

---

pubspec.yaml
tools/analyzer_plugin/pubspec.yaml

* [Raise Max Versions](https://github.com/Workiva/over_react/pull/722)
Requested by: @joebingham-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.2.5...Workiva:release_over_react_4.2.6
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.2.5...4.2.6
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?pull_number=723&repo_name=Workiva%2Fover_react)

RM-124607 RM-124606 Release over_react 4.2.6

---

app/over_react_redux/todo_client/test/unit/_templates/react_components_test_template.html
app/over_react_redux/todo_client/test/unit/_templates/react_test_template.html

See #727 
Update html templates in app example for test_html_builder v2.2.2. Checked by running `pub run build_runner test -- -p chrome` in the `app/over_react_redux/todo_client` directory and verifying that the tests can now be loaded and run. 
Update html templates in app example for test_html_builder v2.2.2
Please review: @Workiva/app-framework

Closes #727

---

skynet.yaml

Add empty skynet plan so release pipelines will stop failing

---

tools/analyzer_plugin/lib/src/diagnostic/forward_only_dom_props_to_dom_builders.dart
tools/analyzer_plugin/playground/web/prop_forwarding.dart
tools/analyzer_plugin/test/integration/diagnostics/forward_only_dom_props_to_dom_builders_test.dart

Make prop forwarding diagnostic work for function components

---

skynet.yaml

Currently skynet is just an echo saying that it makes RM happy which doesn't actually do anything we have tests running in github workflow RM pipeline just can't see them so instead we should make a check in skynet that verifies that github workflow passes.
Added a skynet config that uses the github actions api to check and see if the github worflow is successful or not.
Add skynet config that verifies that github workflow is successful. …

fw-149 Change skynet to verify that github workflow is successful

---

lib/src/component_declaration/component_base.dart

Make error message when component failed to initialize more helpful

---

lib/src/builder/codegen/typed_map_impl_generator.dart

There was a duplicate import that was showing up as a warning instead of an info in newer Dart SDKs, failing the `Dart CI / validate_analyzer (stable, ^1.0.0) (pull_request)` build.
- Remove the import
- Passing build for `Dart CI / validate_analyzer (stable, ^1.0.0) (pull_request)`

Remove duplicate import

---

CHANGELOG.md
pubspec.yaml
tools/analyzer_plugin/pubspec.yaml

* [FED-471 Add utilities for jsifying/unsifying context props](https://github.com/Workiva/over_react/pull/785)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.4.4...Workiva:release_over_react_4.5.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.4.4...4.5.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_number=787)

RM-163391 RM-163390 Release over_react 4.5.0

---

pubspec.yaml
tools/analyzer_plugin/pubspec.yaml

* [Update 3rd party dependencies](https://github.com/Workiva/over_react/pull/824)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.9.0...Workiva:release_over_react_4.9.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.9.0...4.9.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_number=825)

RM-192152 RM-192151 Release over_react 4.9.1

---

CHANGELOG.md

4.10.0 needs a changelog update.
updated changelog.

Update Changelog for 4.10.0 release

---

.github/workflows/dart_ci.yml
lib/src/builder/codegen.dart
lib/src/builder/codegen/accessors_generator.dart
lib/src/builder/codegen/component_generator.dart
lib/src/builder/codegen/typed_map_impl_generator.dart
lib/src/builder/codegen/util.dart
lib/src/builder/parsing/member_association.dart
lib/src/builder/parsing/members/component.dart
lib/src/builder/parsing/members_from_ast.dart
lib/src/builder/parsing/util.dart

Formatting wasn't being run in CI - fixed that and ran ddev format

Format v5 wip

---

pubspec.yaml
tools/analyzer_plugin/pubspec.yaml

* Major changes:
* [FED-2443 Merge version 5.0.0 changes to master](https://github.com/Workiva/over_react/pull/898)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.11.1...Workiva:release_over_react_5.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.11.1...5.0.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_number=899)

RM-237135 RM-237134 Release over_react 5.0.0

---

CHANGELOG.md

Add changelog entry for 5.0.1

---

doc/null_safety/null_safe_migration.md

We should include instructions for how consumers can pull in a fix for https://github.com/dart-lang/sdk/issues/46263
Update migration guide with migrator tool fork fixes.
- Make sure all links are good
- Follow steps locally and make sure the local migrator tool runs without error

FED-2558 Add instructions for using a fork of the migrator tool

---

CHANGELOG.md

The changelog should include all [notable PRs merged since the previous 5.0.1 release](https://github.com/Workiva/over_react/compare/5.0.1...master) that will be included in the 5.1.0 release.

Finalize changelog for 5.1.0 release

---

pubspec.yaml
tools/analyzer_plugin/pubspec.yaml

* [Run CI on release tag commits](https://github.com/Workiva/over_react/pull/921)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.1.0...Workiva:release_over_react_5.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/5.1.0...5.1.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_number=922)

RM-261920 RM-261919 Release over_react 5.1.1

---

.github/workflows/dart_ci.yml
.github/workflows/publish.yml
CHANGELOG.md
build.yaml
dart_dependency_validator.yaml

CI was failing to release properly
- Only use Dart 2.19.6 in CI
- Remove references to mockito (it has been removed, but not all references)
- Update versions of checkout and setup-dart actions

Investigating CI failures

---

pubspec.yaml
tools/analyzer_plugin/pubspec.yaml

* [Investigating CI failures](https://github.com/Workiva/over_react/pull/923)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.1.1...Workiva:release_over_react_5.1.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/5.1.1...5.1.2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_number=924)

RM-262790 RM-262789 Release over_react 5.1.2

---

lib/src/component_declaration/disposable_manager_proxy.dart
pubspec.yaml

Reverts Workiva/over_react#964

Revert "FEDX-1997: adjust `manageAndReturnTypedDisposable`"
