Workiva/over_react

- web/demos/demos.dart
- web/demos/toggle-button/toggle-button-checkbox.dart
- web/demos/toggle-button/toggle-button-radio.dart
- web/index.dart
- web/index.html
- web/src/demo_components.dart
- web/src/demo_components/button.dart
- web/src/demo_components/button_group.dart
- web/src/demo_components/shared.dart
- web/src/demo_components/toggle_button.dart
- web/src/demo_components/toggle_button_group.dart
All of our component demos thus-far have been props-only.
This new demo component constructs a bootstrap "toggle button", and is fully-functional without the use of the jQuery bootstrap "button" plugin.
---
__FYA__ @greglittlefield-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf
> Add stateful component demo

- .travis.yml
Travis will frequently fail on dart_dev test, because Content Shell exits with 1.
This is an attempt to fix that, the idea was taken from https://github.com/dart-lang/test/issues/449#issuecomment-243527617.
> Try to fix failing travis builds

- README.md
- lib/over_react.dart
- lib/src/component_declaration/component_base.dart
- lib/src/component_declaration/flux_component.dart
- lib/src/component_declaration/transformer_helpers.dart
- pubspec.yaml
- test/over_react/component_declaration/flux_component_test.dart
- test/over_react/component_declaration/flux_component_test/default.dart
- test/over_react/component_declaration/flux_component_test/handler_precedence.dart
- test/over_react/component_declaration/flux_component_test/redraw_on.dart
- test/over_react/component_declaration/flux_component_test/store_handlers.dart
- test/over_react_test.dart
Integrating the two components that can be used to build OverReact components that talk to [w_flux](https://github.com/Workiva/w_flux)!
---
__FYA__ @greglittlefield-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf
> Add FluxUiComponent / FluxUiStatefulComponent

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Pretty self-explanatory...
I added `CONTRIBUTING.md`, along with a PR / ISSUE template, and an update to the main readme with a word about our friend `dartfmt`, and our versioning scheme.
__FYA:__ @jacehensley-wf @clairesarsam-wf @greglittlefield-wf @joelleibow-wf
> Add contributor docs / guides, add pr + issue templates

- lib/src/util/rem_util.dart
- test/over_react/util/rem_util_test.dart
This change allows consumers to begin utilizing `toRem` / `toPx` methods within their components - without causing breaking API changes since their consumers may have been implementing the components using a unit like `em`.
Mirrors WSD commit [`0178dd`](https://github.com/Workiva/web_skin_dart/pull/563/commits/0178dd21c738c1129a5c1d55a6ac1a3126947a12)
---
__FYA__ @greglittlefield-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf
> Allow unsupported units in toRem / toPx functions

- README.md
**Ultimate problem:**
The README code does not run.
**How it was fixed:**
Named the import `react_client` so the example code runs.
**Testing suggestions:**
Paste code and verify it runs.
**Potential areas of regression:**
None.
---
> **FYA:** @greglittlefield-wf @aaronlademann-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf
The README code does not compile because it looks for `react_client`.
> Fix react_client reference in README

- README.md
The example code always uses:
``` dart
@Factory()
UiFactory<FooProps> Foo;
```
So shouldn't Foo also be used in the initial render call? FooComponent is a bit misleading.
> changed react_dom.render(FooComponent()() to react_dom.render(Foo()()

- .github/PULL_REQUEST_TEMPLATE.md
PR template was not using headers. The sections don't have enough visual weight.
Use headers instead of bold text.
Verify this PR Looks good.
PR template.
---
> Use markdown headers in PR template

- pubspec.yaml
Added browser_detect to dependencies because it is imported in over_react but only included via dart_dev in dev_dependencies. Deploying an application without it fails, because browser_detect.dart returns with a 404.
> added missing dependency browser_detect

- .travis.yml
- integrate/pubspec.yaml
- pubspec.yaml
Dart SDK version 1.19.1 introduces the ability to have trailing commas in argument lists, which will make re-ordering components in our fluent style much less error-prone for consumers.
It also removes the need for a couple of gross type casts we were doing in #15.
Updated the sdk constraint in `pubspec.yaml`, `integrate/pubspec.yaml`, and in the Travis CI configuration.
Verify that all tests pass.
None expected.
---
> Bump minimum sdk version from 1.17.1 to 1.19.1

- lib/src/component/dom_components.dart
- pubspec.yaml
- test/over_react/component/dom_components_test.dart
- test/over_react_test.html
- test/test_util_test.html
ReactJS 15.4.0 was [released](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html), we should upgrade to that.
ReactJS 15.4.1 was [released](https://github.com/facebook/react/releases/tag/v15.4.1).
- Point to branch of react-dart that has upgraded to 15.4.1 ([PR pending](https://github.com/cleandart/react-dart/pull/108)).
- Add missing SVG elements (#27)
- No longer use `react_dom_prod.js` in tests since `react_dom` now exports the addons.
- None expected
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @clairesarsam-wf @joelleibow-wf
> Upgrade to React 15.4.1

- README.md
Formatting guidelines were outdated when it came to trailing commas. (#25)
Update them.
* Verify that the new guidelines are correct and makes sense.
* README formatting
---
> UIP-1639 Update formatting guidelines WRT dartfmt and trailing commas

- smithy.yaml
- test/over_react/component/dom_components_test.dart
- tool/dev.dart
- tool/smithy_dart2js_tests.sh
dart2js-compiled code that deals with JS interop doesn't always behave the same as native Dart code.
We should be running unit tests in dart2js.
* Fix `MirrorsUsed` typo in test, for proper dart2js compilation
* ~~Run dart2js tests on Travis~~
* Travis is too slow and the suite times out; see #36
* ~~Run dart2js tests on Smithy in Firefox~~
* Focus-related tests fail in Firefox on CI. Attempts to tweak xvfb config or set the `focusmanager.testmode` user preference proved fruitless
* ~~Run dart2js tests on Smithy in Chrome~~
* Chrome wouldn't install properly in the Docker build, and debugging that wasn't going anywhere...
* Run dart2js tests on Smithy using Chromium (already installed) 
* Have to spoof the `google-chrome` executable that the `test` package uses to run the `chrome` …
> UIP-1903 Run unit tests in dart2js on CI

- CHANGELOG.md
- lib/src/component/resize_sensor.dart
- pubspec.yaml
- test/over_react/component/resize_sensor_test.dart
Copy missing updates from https://github.com/Workiva/web_skin_dart/pull/608
Verify that the dynamic-height demo in w_virtual_components master is no longer broken with this dependency override:
```yaml
dependency_overrides:
over_react:
git:
url: git@github.com:greglittlefield-wf/over_react.git
ref: resize_sensor_quick_mount
```
---
`ResizeSensor` (especially its `componentDidMount`) was too slow to use on `VirtualList` items in order to support [dynamic-height items (UIP-1511)](https://github.com/Workiva/w_virtual_components/pull/205).
* Add `quickMount` prop to `ResizeSensor`, which minimizes layouts caused by accessing element dimensions. When enabled:
* The initial dimensions will not be retrieved, so the first `onResize` event will contain `0` for the previous dimensions.
* …
> UIP-1976, UIP-1975 Release over_react 1.5.0 (HOTFIX)

- lib/src/component_declaration/component_base.dart
- test/over_react/component_declaration/component_base_test.dart
`UiProps.addProp`, `UiProps.addProps` and `UiProps.modifyProps` should have a second optional parameter that will allow the consumer to conditionally add or modify props. Similar to ClassnameBuilder.add.
- Added boolean parameters to the `addProp`, `addProps`, and `modifyProps` methods.
- Wrote tests for these three methods.
- Verify that the tests pass.
- N/A
---
> UIP-1392 Make props methods work conditionally

- .travis.yml
- lib/src/util/react_wrappers.dart
- pubspec.yaml
- smithy.yaml
- test/over_react/component_declaration/component_type_checking_test.dart
- test/over_react/component_declaration/transformer_helpers_test.dart
- test/over_react/util/react_wrappers_test.dart
- test/test_util/one_level_wrapper.dart
- test/test_util/two_level_wrapper.dart
- test/test_util_tests/custom_matchers_test.dart
- test/vm_tests/transformer/impl_generation_test.dart
- test/wsd_test_util/zone.dart
`getProps` did not support traversing "Wrapper" components.
- Add param `traverseWrappers` to `getProps`
- When true will traverse all "Wrapper" components until it finds the first nested non-"Wrapper" component.
- This is supported for `ReactElements` and Dart `ReactComponents`.
- Bump min SDK restraint to 1.21.1
- Verify tests cover all cases.
- None expected, only new logic is added.
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf @kaanaksoy-wk
> UIP-1897: Add support for traversing wrapper components to getProps

- lib/src/component_declaration/annotations.dart
- lib/src/component_declaration/component_base.dart
- lib/src/transformer/impl_generation.dart
- pubspec.yaml
- test/over_react/component_declaration/transformer_integration_tests/constant_required_accessor_integration_test.dart
- test/over_react/component_declaration/transformer_integration_tests/required_accessor_integration_test.dart
- test/over_react_component_declaration_test.dart
- test/vm_tests/transformer/impl_generation_test.dart
The `Required` annotation used by the `over_react` transformer collides with the annotation from `package:meta`.
- Deprecate `Required`, and add more options to the `Accessor` annotation.
- Update logic around the transformer to support the new options on an `Accessor` annotation.
- Added shorthand consts for `Accessor(isRequired: true)` and `Accessor(isRequired: true, isNullable: true)`.
- On one of the example components, make a prop required via the new options on an `Accessor` annotation.
- Verify that when you don't set it, the component throws an error.
- Required annotation support.
---
> UIP-1590: Deprecate the Required annotation (Includes UIP-1835)

- lib/src/transformer/impl_generation.dart
- test/over_react/component_declaration/transformer_integration_tests/component_integration_test.dart
- test/vm_tests/transformer/impl_generation_test.dart
There are dart2js warnings incorrectly emitted (likely due to https://github.com/dart-lang/sdk/issues/16030) by each component class declared using over_react, of the form:
```
[Warning from Dart2JS on over_react|web/demos/button/index.dart]:
web/src/demo_components/button.dart:11:1:
'ButtonProps' doesn't implement 'abstract ReactElement call([dynamic a, dynamic a1, dynamic a2, dynamic a3, dynamic a4, dynamic a5, dynamic a6, dynamic a7, dynamic a8, dynamic a9, dynamic a10, dynamic a11, dynamic a12, dynamic a13, dynamic a14, dynamic a15, dynamic a16, dynamic a17, dynamic a18, dynamic a19, dynamic a20, dynamic a21, dynamic a22, dynamic a23, dynamic a24, dynamic a25, dynamic a26, dynamic a27, dynamic a28, dynamic a29, dynamic a30, dynamic a31, dynamic a32, dynamic a33, dynamic a34, dynamic …
```
> UIP-2074 Dart2js warning workaround

- CHANGELOG.md
- pubspec.yaml
> [Complete `1.7.0` Changeset](https://github.com/Workiva/over_react/compare/1.6.0...1.7.0)
* Eliminate dart2js warnings on component props classes #52
* Deprecate the `@Required()` annotation since it conflicts with the `meta` package. #51 Replaced by:
* arguments to the `Accessor` annotation:
```dart
@Accessor(isRequired: true, isNullable: true, requiredErrorMessage: 'foo')
```
* shorthand aliases: `@requiredProp`/`@nullableRequiredProp`
> UIP-2052 Release over_react 1.7.0

- lib/src/component/prop_typedefs.dart
There was a strong mode warning on a typedef on Dart 1.22.0.
- Add a type parameter to base_component.UiComponent.
- Verify that there are no analyzer warnings on Dart 1.22.0
N/A
---
> UIP-2120 Fix strong mode warning

- lib/src/component/abstract_transition.dart
- test/over_react/component/abstract_transition_test.dart
When creating custom `Modals`, it's possible to set transition to a value that `ModalTrigger` doesn't know about, which causes the cleanup of the modal to hang.
We add a timeout to ensure that the modal is cleaned up even if something goes wrong with the transition, and warn the consumer.
- Add a `transitionTimeout` getter to `AbstractTransitionComponent` that can be overridden to adjust the desired timeout duration.
- Use a `Timer` and display a warning after a timeout has occurred.
- Write a test to verify that the timeout actually occurs.
- Verify that the tests pass.
- N/A
---
> UIP-1802 CSS Transition Timeout/Warning

- lib/src/component/abstract_transition.dart
- test/over_react/component/abstract_transition_test.dart
The newly-added transition warning ([UIP-1802](https://github.com/Workiva/over_react/pull/55)),
`VALIDATION WARNING: The number of transitions expected to complete have not completed. Something is most likely wrong.` fires sometimes when it shouldn't.
For instance, sometimes `transitionend` events never fire on purpose, such as when the user cancels the transition (think hiding a popover while it's still showing). This results in a warning when it should not.
I also noticed in the code that the timer does not unsubscribe the listener function, which it probably should.
- Create an instance field, `_transitionEndTimer`, that keeps track of whether a transition timeout has occurred.
- When a transition is canceled (ie, after hiding a popover while it's still showing), `_transitionEndTimer` …
> UIP-2153: Transition warning sometimes fires when it shouldn't

- lib/src/component/abstract_transition.dart
- test/over_react/component/abstract_transition_test.dart
This resolves a warning of the form "Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op."
An AbstractTransitionComponent's `setState` call to set the transition phase to `TransitionPhase.HIDDEN` can occur after the component has been unmounted. This may happen if the component contains a button that causes the AbstractTransitionComponent to be unmounted when clicked.
Added `_isMounted` boolean to the component to keep track of whether or not the component is mounted (it's set to true in `componentDidMount` and set to false in `componentWillUnmount`). The value of this boolean is checked before calling `setState` to set the transition phase to `TransitionPhase.HIDDEN`.
Verify that …
> UIP-2186 Don't call setState when AbstractTransitionComponent is unmounting

- lib/over_react.dart
- lib/src/component/prop_mixins.dart
* Using synthetic event classes required importing `react:react.dart` in addition to `over_react:over_react.dart`.
* Using `setClientConfiguration` and `ReactElement` required importing `react:react_client.dart`.
* ReactJS supports capturing event handlers ([briefly mentioned here](https://facebook.github.io/react/docs/events.html#supported-events)) and so does `react-dart`, but OverReact didn't.
* Export synthetic event classes (this doesn't generate any warnings/infos for consumers already importing `react:react.dart`.
* Export `setClientConfiguration` and `ReactElement`.
* Add capturing event handlers to `DomPropsMixin`.
* Consume this branch in WSD and note no issues occur.
None.
---
> Export react-dart members and add capturing event handlers

- lib/src/component/abstract_transition.dart
- lib/src/component/resize_sensor.dart
- lib/src/component_declaration/component_base.dart
- lib/src/util/dom_util.dart
- lib/src/util/validation_util.dart
- web/src/demo_components/button_group.dart
This pull request is connected with [UIP-1164 (WSD)](https://github.com/Workiva/web_skin_dart/pull/716)
`ValidationUtil.warn` should take an optional `Element` parameter which will be `console.log/.warn'd `to the browser console, allowing consumers to navigate to the offending DOM node in the inspector.
All usages of `ValidationUtil.warn` should be updated to pass in the corresponding DOM node, where applicable.
- Because `ValidationUtil.warn` is often used in components' `render` methods, it cannot use the `findDomNode` method, since it causes the following error message:
> render() should be a pure function of props and state. It should never access something that requires stale data from the previous render, such as refs. Move this logic to componentDidMount and componentDidUpdate …
> UIP-1164 (OR): Provide easy access to DOM node in ValidationUtil.warn messages

- docs.yml
We need a `docs.yml` file so that this lib's README can be displayed in the Workiva dev portal.
Added a `docs.yml`
---
> UIP-2208 Add a docs.yml

- docs.yml
Found this formatting issue while testing out the latest ApplicationFrameworks docs integration on staging.
Define `topics` child as list.
Validated with `dev-portal-docs` cli tool:
```
workiva/over_react [master] » git checkout patch-1
Branch patch-1 set up to track remote branch patch-1 from fork.
Switched to a new branch 'patch-1'
workiva/over_react [patch-1] » docs validate
workiva/over_react [patch-1] »
```
> UIP-2247 Fix docs.yml for publication

- lib/src/component_declaration/component_base.dart
A strong mode change was made in Dart 1.23 that disallows conflicting private members in mixins: <https://github.com/dart-lang/sdk/issues/28809>.
This was causing issues in w_filing when manually mixing in MapViewMixin/PropsMapViewMixin  https://github.com/Workiva/w_filing/blob/1c9a406b59daf3c178d0c69336690c5ce28763f0/lib/src/shared/services/configs/service_props_base.dart#L3
This would have been an issue in over_react if UiProps was in a separate library from these classes.
Declare conflicting `_props` getter in common base class.
- Verify unit tests pass
- Verify analyzer passes in Dart 1.22.0
- Pull the branch into w_filing in Dart 1.23.0 and verify that tehre are no strong mode errors in ServicePropsBase.
UiProps class
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf …
> UIP-2258 Workaround for Dart 1.23 strong mode issue with MapViewMixin

- CHANGELOG.md
- lib/src/component/abstract_transition.dart
- pubspec.yaml
Consumers of AbstractTransition (like `OverlayRenderer`) that didn't call `super.componentDidMount` stopped working properly in over_react 1.9.0: transitions never completed.
Remove `componentDidMount` requirement as a quick fix.
Pull in this version of over_react, and verify that overlay DOM gets cleaned up when overlays (e.g., web_skin_dart Alerts, Popovers, etc.) are transitioned out:
```yaml
dependency_overrides:
over_react:
git:
url: git@github.com:Workiva/over_react.git
ref: 1f41e0b20a335264bdd60372f34d90199bb0d20c # from transition_hotfix
```
Overlay `setState` warnings.
---
> UIP-2260 Release over_react 1.9.1 (HOTFIX)

- pubspec.yaml
When running `pub publish`, there were warnings about libraries being used but not declared as dependencies:
```
Suggestions:
* line 21, column 1 of lib/src/util/react_wrappers.dart: This package doesn't depend on js.
import 'package:js/js.dart';
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 23, column 1 of lib/transformer.dart: This package doesn't depend on path.
import 'package:path/path.dart' as p;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 17, column 1 of test/over_react/component_declaration/component_type_checking_test.dart: This package doesn't depend on js.
import 'package:js/js.dart';
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 20, column 1 of test/over_react/util/react_wrappers_test.dart: This package doesn't depend on js.
import 'package:js/js.dart';
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* line 21, …
```
> UIP-2298 Include explicitly-used transitive imports, as warned by `pub publish`

- test/over_react/component/abstract_transition_test.dart
A test was failing in dart2js due to validation warnings being compiled out.
Don't run those tests in js.
* Pull this branch
* Run `pub run dart_dev test -p chrome` and verify that all tests pass
Unit tests
---
> UIP-2304 Don't run ValidationUtil-related tests in dart2js

- lib/src/util/dom_util.dart
- test/over_react/util/dom_util_test.dart
In order to implement cursor index caching in CTEs, we need a streamlined function that gives us the `selectionStart` value for any input type. 
The `getSelectionStart` function in this PR handles inconsistent behavior across browsers—Chrome does not support `selectionStart` for number and email inputs—while also properly handling text areas.
- Create a `getSelectionStart` function similar to the already existing `setSelectionRange` utility.
- Write tests to verify the functionality of the `getSelectionStart` utility.
- Verify that tests pass.
- N/A
---
FYA: @aaronlademann-wf @greglittlefield-wf @clairesarsam-wf @joelleibow-wf @jacehensley-wf
> UIP-2303 getSelectionStart Util for CTE Cursor Caching

- CHANGELOG.md
- pubspec.yaml
__Improvements__
* #69: New top-level `getSelectionStart` function to normalize `selectionStart` across browsers for both `TextInputElement`s and `TextAreaElement`s
__Tech Debt Paid__
* #68: Declare explicitly-used transitive imports in `pubspec.yaml`  
* #70: Don't run `ValidationUtil`-related tests in dart2js
---
> UIP-2297 Release over_react 1.10.0

- .analysis_options
- lib/src/component/abstract_transition.dart
- lib/src/component/resize_sensor.dart
- pubspec.yaml
- test/over_react/component/resize_sensor_test.dart
- test/over_react/component_declaration/flux_component_test.dart
- test/test_util/dom_util.dart
- test/wsd_test_util/common_component_tests.dart
1. The `cancel_subscriptions` and `close_sinks` lints were not enabled.
2. `AbstractTransitionComponent` / `ResizeSensorComponent` both have lifecycle methods that - if a consumer were to extend from, and not call `super` - could/would cause memory leaks.
3. The `browser_detect` dev dependency is abandonware.
1. Lints were added / instances of violations were addressed _(tests were the only place that had problems)_
2. `@mustCallSuper` annotation was added to critical lifecycle methods that register handlers that could leak if never un-registered / destroyed / closed.
3. Use `platform_detect` instead.
Verify that tests pass
None expected
---
> UIP-2379 Memory leak audit

- .travis.yml
- lib/src/transformer/impl_generation.dart
- pubspec.yaml
- smithy.yaml
- test/vm_tests/transformer/impl_generation_test.dart
> NOTE: This is not a clean diff.
>
> It will be clean once #75 merges
The `over_react` transformer did not support the `covariant` keyword recently added by the Dart SDK.
The transformer was updated to detect the presence of the keyword, and place it within the setter parameter only.
1. Verify that tests pass
Transformed code
---
> UIP-2024 Add support for covariant prop / state fields

- lib/src/component_declaration/flux_component.dart
- pubspec.yaml
- test/over_react/component_declaration/flux_component_test.dart
If a `FluxUiComponent` is rerendered with different `props.store` or different props that affect the return value of `redrawOn`, it does not currently update its subscriptions to look at the latest store. This can happen indirectly as a result of rerendering larger views.
- Re-bind store handlers/subscriptions whenever a component is rerendered with new props, ensuring that the latest are always referenced.
- Add `mustCallSuper` annotations to help consumers detect when they're interfering with existing mount/unmount hooks, as well as the new lifecycle hooks added to support this new behavior
- __Note:__ If existing consumers don't call super on `componentWillReceiveProps`/`componentDidUpdate`, then they just won't get this improved behavior. However, they may hit state issues if they …
> UIP-2114: Update FluxUiComponent subscriptions when props are updated

- CHANGELOG.md
- README.md
- lib/src/component_declaration/flux_component.dart
- pubspec.yaml
- test/over_react/component_declaration/flux_component_test.dart
* Revert _#77: Update `FluxUiComponent` subscriptions when new `props` are received._
* Reverted since this broke subclasses that weren't calling super in lifecycle methods `componentWillReceieveProps` and `componentDidUpdate`
* Keep `@mustCallSuper` annotations from this changeset  
---
> UIP-2398 Release over_react 1.11.1 (HOTFIX)

- lib/over_react.dart
- lib/src/component/abstract_transition.dart
- lib/src/component/abstract_transition_props.dart
The props in `AbstractTransitionProps` cannot be consumed as a mixin, which makes component extension difficult if the consumer cannot extend directly from `AbstractTransitionProps`.
A props mixin / map view were added, and the existing abstract props class now mixes in the new mixin.
Verify that tests pass
None expected
---
> UIP-2373 Make AbstractTransitionProps available in mixin form

- CHANGELOG.md
- README.md
- lib/src/component_declaration/flux_component.dart
- pubspec.yaml
Some Store mocks in consumer tests don't properly mock `isDisposedOrDisposing`, which results in breakages caused by this new check.
We can fix all those tests here by accounting for this case.
Null-coalesce `isDisposedOrDisposing` to ease test breakages
Pull into a branch that was previously failing with the error:
```
Failed assertion: boolean expression must not be null
#0      UiComponent&&_FluxComponentMixin.componentWillMount.<anonymous closure> (package:over_react/src/component_declaration/flux_component.dart:155:21)
```
`isDisposedOrDisposing` error message
---
> UIP-2399 Release over_react 1.11.2

- dart_test.yaml
- lib/src/component/dom_components.dart
- lib/src/component_declaration/component_base.dart
- lib/src/transformer/README.md
- lib/src/transformer/impl_generation.dart
- lib/src/util/ddc_emulated_function_name_bug.dart
- lib/src/util/react_wrappers.dart
- lib/transformer.dart
- pubspec.yaml
- test/over_react/component_declaration/component_base_test.dart
- test/over_react/util/ddc_emulated_function_name_bug_test.dart
- test/over_react/util/react_wrappers_test.dart
- test/over_react_util_test.dart
- test/vm_tests/transformer/impl_generation_test.dart
- test/vm_tests/transformer/transformer_test.dart
Running OverReact-based code in the DDC resulted in several runtime errors.
Also, the patterns of declaring abstract prop getters was problematic.
- Fix DDC issues within internal code
- Major fixes:
- Detect and patch [DDC emulated function name bug](https://github.com/dart-lang/sdk/issues/27647) in UiProps instances
- This bug prevented `UiProps` classes from having props named `name`
- Work around [DDC emulated function bug](https://github.com/dart-lang/sdk/issues/29904) encountered when invoking react-dart factories
- Bump to react-dart `^3.4.0` to consume new `.build()` API
- Minor fixes:
- Disable caching (for now) in `getProps` since Expandos not working on certain JS objects
- Fix mixing in the same props class twice
- Work around MapViewMixin and Props/StateMapViewMixin errors in …
> UIP-2410: Basic DDC support

- CHANGELOG.md
- README.md
- pubspec.yaml
> [Complete `1.12.0` Changeset](https://github.com/Workiva/over_react/compare/1.11.2...1.12.0)
__Strong Mode / Dart Dev Compiler__
* #81: Make transformer output strong mode clean.
* Closes #14
* #82: Implement workarounds necessary to make OverReact-based code able to be compiled by the Dart Dev Compiler _("DDC")_.
* _See new [transformer options documentation](https://github.com/Workiva/over_react/blob/master/lib/src/transformer/README.md#transformer-options) for more information._
---
> UIP-2406 Release over_react 1.12.0

- CHANGELOG.md
- README.md
- pubspec.yaml
- Bump source_span to version w/ SourceFile.fromString, which we started using in the last release
---
> UIP-2432 Release over_react 1.12.1 (HOTFIX)

- lib/src/component/dom_components.dart
- test/over_react/component/dom_components_test.dart
The following code is affected by a DDC issue affecting emulated functions and `noSuchMethod` (issue: https://github.com/dart-lang/sdk/issues/29904):
```dart
render() {
var builder;
if (condition) {
builder = Dom.div();
} else {
builder = Button();
}
return builder(); // throws `Uncaught TypeError: Cannot read property 'noSuchMethod' of undefined`
}
```
The easiest way for consumers to work around it, is to type `builder`. In this case, however, the least upper bound is `component_base.UiProps`, so consumers would have to import that.
```diff
+import 'package:over_react/component_base.dart' as component_base;
render() {
-  var builder;
+  component_base.UiProps builder;
...
}
```
It would be nice if they could just do `UiProps builder;`, using the `UiProps` exposed by over_react.dart. …
> UIP-2447 Make DomProps/SvgProps implement UiProps for more convenient DDC typing

- pubspec.yaml
+ DDC compilation errors are still present even in 0.24.0
---
> UIP-2450 Update quiver dependency

- CHANGELOG.md
- README.md
- pubspec.yaml
* #89: quiver `>=0.21.4 <0.26.0` (was `>=0.21.4 <0.25.0`)
* #87: Make `DomProps`/`SvgProps` implement `UiProps` for more convenient DDC typing
__Misc__
* #86: Get tests passing using the DDC
* #83: Use `over_react_test`
---
> UIP-2434 Release over_react 1.13.0

- lib/src/util/prop_errors.dart
> Related to: https://github.com/Workiva/over_react_test/pull/8
When running tests in the DDC the `Error.safeToString` was kinda a PITA
- Do not use `Error.safeToString`
??
N/A
---
> Update prop error message

- lib/src/component/abstract_transition.dart
- lib/src/component_declaration/component_base.dart
- lib/src/component_declaration/flux_component.dart
- pubspec.yaml
- test/over_react/component_declaration/component_base_test.dart
Consumers are required to manually deal with lifecycle management within the component lifecycle. This either requires mixing lifecycle management functionality into all of their components or independently managing the lifetime of `StreamControllers`, `StreamSubscriptions, etc in each component. 
The DisposableManagerV3 interface has been mixed into the base implementation of `UiComponent`. This interface proxies all calls to an internal instance of `w_common`'s Disposable. The call to dispose is tied to the `componentWillUnmount` call ensuring that managed objects are correctly cancelled or concluded when the component is removed from the DOM.
- The disposable functionality has been exercised in the unit tests. The CI run should pass to confirm this functionality is correct.
- An …
> UIP-2161 Implement DisposableManagerV3 for UiComponent

- CHANGELOG.md
- README.md
- pubspec.yaml
* react `^3.4.3` (was `^3.4.1`)
* w_common `^1.6.0` (new)
* #91: Implement [`DisposableManagerV3`](https://github.com/Workiva/w_common/blob/master/lib/src/common/disposable_manager.dart#L71) for `UiComponent`
* Assists with cleaning up streams and other data structures that won't 
necessarily be garbage collected without some manual intervention.
__Misc__
* #92: Update prop error message to make it more DDC friendly
---
__FYA:__ @jacehensley-wf @clairesarsam-wf @greglittlefield-wf 
__FYI:__ @joelleibow-wf @bencampbell-wf
> UIP-2458 Release over_react 1.14.0

- pubspec.yaml
- test/over_react/component/prop_mixins_test.dart
- test/over_react/component_declaration/component_base_test.dart
- test/over_react/component_declaration/transformer_helpers_test.dart
- test/over_react/component_declaration/transformer_integration_tests/stateful_component_integration_test.dart
- test/over_react/util/handler_chain_util_test.dart
- test/wsd_test_util/prop_utils.dart
- test/wsd_test_util/zone.dart
The `dart-lang/test` has a number of deprecations that we couldn't address previously because of some issues with the `throwsA` replacement.  Those issues appear to have been fixed in a recent update to the test package.
Address deprecations
Passing CI build
Tests
---
__FYA:__ @greglittlefield-wf @jacehensley-wf @clairesarsam-wf
> Address deprecation lints

- lib/src/component_declaration/flux_component.dart
The parameter for `componentWillReceiveProps` was incorrectly listed as `prevProps`.
This is very misleading when inspecting the super implementation when insde a flux component subclass.
N/A (the name of the changed parameter has no effect in this case)
---
> UIP-2528 Fix misleading typo in overriden parameter name

- lib/src/component_declaration/component_base.dart
- test/over_react/component_declaration/component_base_test.dart
- Consumers need an easy way to validate props without having to override `componentWillReceiveProps` and `componentWillMount`.
- Add `validateProps` method that is called automatically during those lifecycle methods.
- Required prop validation
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @clairesarsam-wf @joelleibow-wf
> UIP-2529 Add validateProps method to UiComponent

- CHANGELOG.md
- README.md
- pubspec.yaml
* over_react_test `^1.0.1` (was `^1.0.0`)
* test `^0.12.24` (was `^0.12.6+2`)
* #88: Add `validateProps` method to `UiComponent`
* Will automatically validate props annotated with `@requiredProp` 
within `componentWillMount` and `componentWillReceiveProps`
__Tech Debt__
* #94: Address deprecations from `package:test`
* #98: Fix misleading typo in overridden parameter name
__Misc__
* #73: Add callout for the [OverReact Snippet VS Code Extension](https://marketplace.visualstudio.com/items?itemName=JaceHensley.over-react-snippets)
---
__FYA:__ @clairesarsam-wf @greglittlefield-wf @jacehensley-wf
> UIP-2463 Release OverReact 1.15.0

- lib/src/component/resize_sensor.dart
- lib/src/component_declaration/component_base.dart
- lib/src/component_declaration/component_type_checking.dart
- lib/src/component_declaration/flux_component.dart
- lib/src/util/class_names.dart
- lib/src/util/css_value_util.dart
- lib/src/util/dom_util.dart
- lib/src/util/event_helpers.dart
- lib/src/util/key_constants.dart
- lib/src/util/map_util.dart
- lib/src/util/pretty_print.dart
- lib/src/util/prop_errors.dart
- lib/src/util/prop_key_util.dart
- lib/src/util/react_wrappers.dart
- lib/src/util/rem_util.dart
- lib/src/util/string_util.dart
Misc. documentation improvements I made while doing the memory leak audit.
---
__FYA:__ @greglittlefield-wf @jacehensley-wf @clairesarsam-wf
> UIP-2563 Improve some doc comments

- .travis.yml
- CHANGELOG.md
- README.md
- pubspec.yaml
* over_react_test `^1.1.1` (was `^1.0.1`)
__Tech Debt__
* #97: Improve some documentation comments.
* #95: Move internal test utils to [over_react_test](https://github.com/Workiva/over_react_test/pull/11), and consume them.
---
> UIP-2546 Release OverReact 1.15.1

- lib/src/component_declaration/component_base.dart
- pubspec.yaml
- test/over_react/component_declaration/component_base_test.dart
Version `1.8.0` of `w_common` includes a new version of the disposable manager interface that `UiComponent` implements.
- Upgraded the minimum `w_common` version to `1.8.0`
- Updated `UiComponent` to implement `DisposableManagerV6`
🤷‍♂️ 
---
> UIP-2614 Update UiComponent to implement DisposableManagerV6

- lib/src/util/dom_util.dart
- lib/src/util/react_wrappers.dart
- test/over_react/util/dom_util_test.dart
- test/over_react/util/react_wrappers_test.dart
The soon to be released react-dart 4.0 will no longer support retrieving Dart components via `getDartComponent` from `ReactElements` (pre-mounted VDOM instances) in order to avoid memory leaks.
We should have a warning in place for when this occurs so that consumers will:
- be able to identify problematic usages that need to be updated
- be able to tell why things are breaking if they don't fix them in time:
- Add error message that prints when a ReactElement is passed into `getDartComponent`
- Add tests
- Fixes to selection range tests that were failing in Chrome
- [UIP-2322](https://jira.atl.workiva.net/browse/UIP-2322) Fixes to selection range logic in Firefox
Verify that tests pass in all platforms:
- Dart VM
- `ddev test -p content-shell`
- `ddev test -p dartium`
- dart2js
- `ddev …
> UIP-2629 getDartComponent warning for ReactElements

- lib/src/component_declaration/flux_component.dart
- pubspec.yaml
- test/over_react/component_declaration/flux_component_test.dart
- test/over_react/component_declaration/flux_component_test/nested.dart
Depends on https://github.com/Workiva/w_flux/pull/96
Flux components were rerendered excessively when nested inside each other and a store trigger caused rerendering of those nested components.
See reduced test case [here](https://gist.github.com/greglittlefield-wf/e2cd42b03261e1cb11817a6e5718025d).
Track whether components were already redrawn during the current redraw batch.
All consumers will need to do is make sure to call `super.componentDidUpdate` in overrides, and they'll get this fix.
- Verify tests pass.
- Verify issue is resolved in linked reduced test case.
Flux component rerendering
---
FYA @Workiva/web-platform-pp @Workiva/ui-platform-pp 
FYI: @kylemcmorrow-wf @johnbland-wf @brentschuele-wf @brandonrodgers-wf @robbielamb-wf
> UIP-2615 Redraw only once when store triggers along with ancestor rerender

- CHANGELOG.md
- README.md
- pubspec.yaml
- test/over_react/component_declaration/component_base_test.dart
- test/over_react/util/react_wrappers_test.dart
* w_common `^1.8.0` (was `^1.6.0`)
* w_flux `^2.9.0` (was `^2.7.1`)
* #104: Update `UiComponent` to implement `DisposableManagerV6`.
__Improvements__
* #103: `FluxUiComponent` redraws only once when store triggers along with ancestor rerender.
__Tech Debt__
* #105: Add warning for incorrect usage of `getDartComponent`.
---
> UIP-2588 Release over_react 1.16.0

- CHANGELOG.md
- README.md
- lib/src/component_declaration/flux_component.dart
- pubspec.yaml
- test/over_react/component_declaration/flux_component_test.dart
Currently, when a component calls `setState` at the same time the store triggers, the rerender with the updated store does not take place.
Use `componentWillReceiveProps` to mark batch redraws instead of `componentDidUpdate`.
This will mark only components that are getting excessive rerenders from parent components, and not components that have unrelated `setState` calls.
- Pull this branch into graph_app tag 1.320.0 and verify there are no longer any failing tests.
- Build: https://ci.webfilings.com/build/987215
FluxUiComponent batch redrawing.
---
@Workiva/ui-platform-pp @Workiva/web-platform-pp @kylemcmorrow-wf
> UIP-2637 Release over_react 1.16.1 (HOTFIX)

- lib/src/component_declaration/transformer_helpers.dart
An `UngeneratedError` was thrown in some cases without a useful error message.
Improve error message
- Verify tests pass.
- Verify that rendering the following faulty component results in a useful error message:
```dart
@Factory()
UiFactory<FooProps> Foo;
@Props()
class FooProps extends UiProps {}
class FooState extends UiState {}
@Component()
class FooComponent extends UiStatefulComponent<FooProps, FooState> {
@override
Map getInitialState() => newState();
@override
render() {
return Dom.div()();
}
}
```
`typedStateFactory` error messages.
---
> UIP-2742 Improve error message when UiState classes aren't set up properly

- lib/src/component/prop_mixins.dart
- lib/src/component_declaration/annotations.dart
- lib/src/transformer/impl_generation.dart
- test/over_react/component/prop_mixins_test.dart
- test/over_react/component_declaration/transformer_integration_tests/do_not_generate_accessor_integration_test.dart
- test/over_react_component_declaration_test.dart
_I was bored after work yesterday 😄_
Adding aria/DOM props to components is a little clunky; you have to do something like this:
```dart
(Button()
..addProps(domProps()..draggable = true)
..addProps(ariaProps()
..controls = 'my_popover'
..labelledby = 'my_label'
)
)('Click me')
```
What would be nicer is a syntax like this:
```dart
(Button()
..dom.draggable = true
..aria.controls = 'my_popover'
..aria.labelledby = 'my_label'
)('Click me')
```
- Add `aria` and `dom` getters to `UbiquitousDomPropsMixin` that provide typed views into a given `UiProps` class that allow for reading/writing aria/DOM props.
- Add `doNotGenerate` option to `@Accessor()` annotation to allow declaring fields in accessor (props, props mixin, state, state mixin) classes that shouldn't be generated into …
> UIP-2762 More convenient ubiquitous access of DOM/aria props

- lib/src/component/abstract_transition.dart
- lib/src/component/abstract_transition_props.dart
- test/over_react/component/abstract_transition_test.dart
- There wasn't a way to configure the number of transitions to be different between showing and hiding
- We want to add test attributes that mirror the state of the transition in the DOM in consistent way
- Add `transitionInCount`/`transitionOutCount` props and update `AbstractTransitionComponent` to support them
- Add `AbstractTransitionComponent.getTransitionTestAttributes` for use in consumer implementations
- Verify that tests pass
- Verify that there are no regressions in AbstractTransition behavior in WSD branch: https://github.com/Workiva/web_skin_dart/pull/860
- collapsible cards
- overlay transitions (popovers, tooltips, modals)
- AbstractTransition
---
> UIP-2751 Transition in/out-specific config, test attributes

- CHANGELOG.md
- pubspec.yaml
Pulls Included in Release:
* [UIP-2742 Improve error message when UiState classes aren't set up properly](https://github.com/Workiva/over_react/pull/117)
* [UIP-2762 More convenient ubiquitous access of DOM/aria props](https://github.com/Workiva/over_react/pull/119)
* [UIP-2751 Transition in/out-specific config, test attributes](https://github.com/Workiva/over_react/pull/120)
Requested by: @jacehensley-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/1.17.0...Workiva:release_over_react_1_18_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/1.17.0...1.18.0
> WP-5222 UIP-2741 Release over_react 1.18.0

- CHANGELOG.md
- lib/src/component/prop_mixins.dart
- pubspec.yaml
Imported members used by generated code were removed, which for some reason only affected the DDC.
Re-add the imports.
Verify tests pass in DDC:
```bash
ddev test -p chrome --web-compiler=dartdevc -- \
test/over_react_component_test.dart test/over_react_component_declaration_test.dart test/over_react_util_test.dart \
-x no-ddc
```
None
---
> WP-5352 UIP-2794 Release over_react 1.18.1

- .travis.yml
- pubspec.yaml
- smithy.yaml
Now that `dependency_validator` is published we should use it.
- Add `dependency_validator` as a dev dep and runs its check during CI.
- Verify CI still passes
N/A
---
FYA: @Workiva/ui-platform-pp @Workiva/web-platform-pp
> UIP-2889 Use dependency_validator

- CHANGELOG.md
- pubspec.yaml
Pulls Included in Release:
* [Add BuiltReduxUiComponent](https://github.com/Workiva/over_react/pull/118)
* [UIP-2889 Use dependency_validator](https://github.com/Workiva/over_react/pull/126)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/1.18.1...jacehensley-wf:release_1_19_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/1.18.1...1.19.0
> UIP-2806: Release over_react 1.19.0

- lib/over_react.dart
- lib/src/util/react_util.dart
- test/over_react/util/react_util_test.dart
- test/over_react_util_test.dart
We should add `UiPropsMapView`
- Add and test `UiPropsMapView`
- N/A only new stuff
---
> UIP-2924: Add UiPropsMapView

- lib/src/component_declaration/flux_component.dart
Rename loggers to follow the pattern: `<package_name>.<class_name>` per @leerobinson-wf's email to wf-dev.
@Workiva/app-frameworks
> WP-5737 over_react should follow new logger name standard

- CHANGELOG.md
- README.md
- pubspec.yaml
The latest release of over_react includes the following:
__Misc__
* #133: Update logger name standard.
---
> __FYA:__ @Workiva/app-frameworks
> UIP-2949 Release over_react 1.20.1

- integrate/lib/test_component_declaration.dart
- integrate/test/test_runtime_import.dart
- integrate/tool/dev.dart
- lib/src/component/abstract_transition.dart
- lib/src/component/abstract_transition_props.dart
- lib/src/component/dom_components.dart
- lib/src/component/dummy_component.dart
- lib/src/component/resize_sensor.dart
- lib/src/util/dom_util.dart
- lib/src/util/guid_util.dart
- lib/src/util/key_constants.dart
- pubspec.yaml
A few pieces of our code was causing noisy dart2js compiler output for our consumers.
Address those items.
Passing CI build
None expected.
---
> __FYA:__ @Workiva/app-frameworks
> UIP-3039 Get rid of dart2js compiler warnings

- lib/src/experimental/built_redux_component.dart
I ran into an issue when implementing a `shouldComponentUpdate` method in a class that extends `BuiltReduxUiComponent`.
- Null check `_storeSubs`
- CI still passes
N/A
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @jacehensley-wf @clairesarsam-wf
> UIP-3041 Add a null check when canceling the store stream subscription

- pubspec.yaml
Pulls Included in Release:
* [UIP-3039 Get rid of dart2js compiler warnings](https://github.com/Workiva/over_react/pull/137)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/1.20.1...Workiva:release_over_react_1_20_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/1.20.1...1.20.2
> WP-5859 UIP-2998 Release over_react 1.20.2

- CHANGELOG.md
- README.md
- pubspec.yaml
Pulls Included in Release:
* [Add an option to make BuiltReduxUiComponent "pure"](https://github.com/Workiva/over_react/pull/140)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/1.20.2...Workiva:release_over_react_1_21_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/1.20.2...1.21.0
> UIP-3043 Release over_react 1.21.0

- lib/over_react.dart
- lib/src/component_declaration/component_base.dart
- pubspec.yaml
The `validateProps` method is currently called in `componentWillMount` and `componentWillReceiveProps` - even in production (dart2js) code.
This means that our internal `validateRequiredProps` is always called when a component mounts / updates - and any consumer validations are also always called if/when they override `validateProps`.
There is a not-insignificant performance cost to this, and there is no reason for prop validation to be happening in a dart2js scenario.  
1. Wrap both calls to `validateProps` in an `assert` to improve performance in dart2js builds.
2. Update tests.
1. Pull this branch locally
2. Run `pub get` and `ddev test -p chrome`
3. Verify that all tests pass in chrome. 
* _(NOTE: focusing the chrome window running the tests greatly speeds up test execution)_.
Tests? …
> UIP-3062 Do not execute prop validation logic in dart2js code

- pubspec.yaml
We need to widen the `built_value` version constraint.
- Allow 4.x.x and 5.x.x of `built_value`
- Bump `build_runner` and `built_value_generator`
- Verify CI passes.
- Verify that `built_value` 5.x.x is pulled in
- Verify that `built_collection` 3.x.x is pulled in
- Built stuff
---
> UIP-3156 Widen built_value version constraint

- CHANGELOG.md
- pubspec.yaml
* #149: Dependency Maintenance:
* __Dart SDK__ now `>=1.24.2 <2.0.0`, was `>=1.24.2`
* Dependencies:
* __analyzer__ now `>=0.30.0 <=0.31.0`, was `>=0.30.0 <0.31.0`
* __barback__ now `>=0.15.2 <=0.15.2+14`, was `^0.15.0`
* __quiver__ now `>=0.21.4 <=0.28.0`, was `>=0.21.4 <0.26.0`
* Dev Dependencies:
* __coverage__ now `>=0.7.2 <0.11.0`, was `^0.7.2`
* __dependency_validator__ now `^1.1.0`, was `^1.0.0`
* __mockito__ now `^2.0.0`, was `^0.11.0`
* __test__ now `^0.12.32+1`, was `^0.12.24`
---
> UIP-3159 Release over_react 1.23.1

- lib/src/util/react_wrappers.dart
- pubspec.yaml
- test/over_react/util/react_wrappers_test.dart
The `react` 4.x line-of-release includes improvements to Dart component instance management that help avoid certain memory leaks. See more info here: https://github.com/cleandart/react-dart/pull/127.
While the `react 4.0.0` release contains "breaking" changes, those breakages are limited to internals that should be smoothed over by over_react, and should not affect the majority of consumers.
Bump react-dart dependency to `^4.3.0`.
* Verify that all tests pass in all modes (Dart VM, dart2js, DDC)
* Regression test in low-level Workiva UI repos
| Repo   | Smithy  | Shipyard  | Skynet: Smithy  | Skynet: Shipyard/Push  |
|---|---|---|---|---|
| [w_router](https://github.com/Workiva/w_router/pull/86)  | ✅ | n/a  | n/a  | n/a  |
| [wdesk_sdk](https://github.com/Workiva/wdesk_sdk/pull/2421)  | ✅ …
> AF-36 Use react-dart 4.x

- README.md
- lib/react_dom.dart
- lib/src/util/rem_util.dart
- test/over_react/component/resize_sensor_test.dart
- test/over_react/component_declaration/transformer_integration_tests/constant_required_accessor_integration_test.dart
- test/over_react/component_declaration/transformer_integration_tests/required_accessor_integration_test.dart
- test/over_react/component_declaration/transformer_integration_tests/required_prop_integration_test.dart
- test/over_react/dom/fixtures/dummy_composite_component.dart
- test/over_react/dom/render_test.dart
- test/over_react/dom/unmount_test.dart
- test/over_react/util/react_wrappers_test.dart
- test/over_react_dom_test.dart
- test/over_react_dom_test.html
- tool/dev.dart
- web/demos/button/index.dart
- web/demos/list-group/index.dart
- web/demos/progress/index.dart
- web/demos/tag/index.dart
- web/index.dart
We currently expose most of the commonly consumed methods from the `react` package, but not anything from its `react_dom.dart`.  This forces consumers to import `package:react/react_dom.dart`, and therefore declare `react` as a dependency for their application.
However, this library is designed to act as an improved consumption experience for `react` consumers, which should include insulation from internal breaking changes without having to change the upper bound of a dependency.
1. Proxy the `react_dom.render` and `react_dom.unmountComponentAtNode` methods from `package:react/react_dom.dart`, with improved function / return signatures.
2. Update all internal consumption, and consumption documentation.
3. Write tests.
__For consumers, this should be the extent of the changes necessary to …
> AF-232 Expose render and unmountComponentAtNode

- CHANGELOG.md
- README.md
- pubspec.yaml
* #153 react `^4.3.0` (was `^3.7.0`)
* #151 
* built_redux `^7.4.1` (was `>=6.1.0 <8.0.0`)
* built_value `>=4.2.0 <5.2.0` (was `>=4.2.0 <6.0.0`)
__New Features__ 
* #154: Expose `react_dom.render`/`react_dom.unmountComponentAtNode` from the react library
* __Warning:__ This will be deprecated in an upcoming release in favor of a different approach to creating a `built_redux` component.
__Tech Debt__
* #151 Prepare for Dart 2 SDK
* Address Dart 2.x SDK lints / warnings that do not constitute breaking changes
* Address `DisposableManagerV6` deprecation
* `UiProps` and `UiState` now extend from `MapBase`
---
> __FYA:__ @greglittlefield-wf @clairesarsam-wf @sebastianmalysa-wf @dustinlessard-wf
> AF-188 Release over_react 1.24.0

- CHANGELOG.md
- README.md
- pubspec.yaml
- test/over_react/component_declaration/component_base_test.dart
- test/over_react/util/react_wrappers_test.dart
* w_common `^1.10.0` (was `^1.8.0`)
* react `^4.4.1` (was `^4.3.0`)
__Tech Debt__
* Address `ReactComponentFactory` deprecation
* Address `findRenderedComponentWithType` deprecation
---
> __FYA:__ @greglittlefield-wf @clairesarsam-wf @sebastianmalysa-wf
> AF-258 Release over_react 1.24.1

- .travis.yml
- Dockerfile
- smithy.yaml
- tool/dev.dart
The following pull request has been created by App Frameworks to help move consumers to the latest Smithy image. This was done because of an issue with Dartium and Content-Shell that would fail your CIs. Please seethis [Wiki Question](https://wiki.atl.workiva.net/cq/viewquestion.action?id=96308901&answerId=96308907)for additional context.
The following changes have been made:
* All instances of the production Smithy image have been updated to `drydock-prod.workiva.net/workiva/smithy-runner-generator:355624`.
If you have any questions, please reach out to us in the Support:H5 / Dart Hipchat room
> af_new_drydock_image

- lib/src/util/class_names.dart
- test/over_react/util/class_names_test.dart
AF-1227
As a consumer, I should be able to easily merge together the classes and blacklists present in two ClassNameBuilders.
Added `merge` method to `ClassNameBuilder` class.
Added `merged` constructor to `ClassNameBuilder` class.
Run the unit tests they should pass.
None.
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @clairesarsam-wf
> AF-1227: Adds merge method and merged constructor to ClassNameBuilder class.

- lib/react_wrappers.dart
AF-361
Make react_wrappers.dart a top-level lib
Created a `react_wrappers.dart` file as a top level library file exporting `package:over_react/src/util/react_wrappers.dart`
None.
library test_util.react_util no longer exists.
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @clairesarsam-wf
> AF-361: Adds top level react_wrappers lib and removes test_util.react_util lib

- pubspec.yaml
`over_react` specifies some maximum ranges to prevent Dart 2 resolutions.
The sdk 'environment' range should limit this for us.
Expand version ranges on `analyzer`, `built_value`, and `quiver`
CI passes
---
> Tweak version ranges to allow pub get in Dart 2

- lib/src/util/rem_util.dart
- test/over_react/util/rem_util_test.dart
Because Chrome changes the value of its root font size when zoomed out lower than 90%, we need to automatically wire up the rem change sensor when `toRem` is called the first time so that any subsequent calls to `toRem` when the viewport is zoomed return an accurate value.
> See: https://bugs.chromium.org/p/chromium/issues/detail?id=429140
---
> __FYA:__ @greglittlefield-wf
> AF-2241 Auto-initialize a rem change sensor in Google Chrome

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- README.md
- pubspec.yaml
* #178: Automatic document root font-size change detection in Google Chrome to overcome https://bugs.chromium.org/p/chromium/issues/detail?id=429140
* [881c0c](https://github.com/Workiva/over_react/commit/881c0ca0806d265ad7baf1f45aace632561ab05c) Tighten version constraints to speed up pub get
* analyzer `>=0.30.0+4 <=0.31.0` (was `>=0.30.0 <=0.31.0`)
* built_redux `^7.4.2` (was `^7.4.1`)
* built_value `>=5.1.3 <5.2.0` (was `>=4.2.0 <5.2.0`)
* js `^0.6.1+1` (was `^0.6.0`)
* logging `>=0.11.3+2 <1.0.0` (was `>=0.11.3+1 <1.0.0`)
* meta `^1.1.6` (was `^1.0.4`)
* path `^1.5.1` (was `^1.4.1`)
* react `^4.4.2` (was `^4.4.1`)
* source_span `^1.4.1` (was `^1.4.0`)
* transformer_utils `^0.1.5` (was `^0.1.1`)
* w_common `^1.13.0` (was `^1.10.0`)
* w_flux …
> AF-1696 Release over_react 1.26.0

- CHANGELOG.md
- README.md
- pubspec.yaml
The lower bound of `built-value` in [the `1.26.0` release](https://github.com/Workiva/over_react/pull/182) turned out to be too restrictive for some consumers that need to remain on the `4.x` line-of-release for that package.
* [e8fc86](https://github.com/Workiva/over_react/commit/e8fc86c9748c4cfb8af7bde91b0959827a5a7a63) Loosen lower bound of `built_value`
* built_value `>=4.6.1 <5.2.0` (was `>=5.1.3 <5.2.0`)
---
> __FYA:__ @kealjones-wk
> AF-2344 Release over_react 1.26.1

- CHANGELOG.md
- lib/src/util/rem_util.dart
- pubspec.yaml
Includes:
- [5fb73f](https://github.com/Workiva/over_react/commit/5fb73f26f92182ebd5c45c2ad5bb015a662bc3b4) Make rem change sensor container is `overflow:hidden` so it doesn't interfere with the page layout
- Testing: verify unit tests for resize sensors still pass.
---
> AF-2361 AF-2360 Release over_react 1.26.2

- lib/src/transformer/declaration_parsing.dart
Looks like this can be isNotEmpty instead (https://www.dartlang.org/guides/language/effective-dart/usage#dont-use-length-to-see-if-a-collection-is-empty)
Uses `isNotEmpty` check.
CI/tests pass.
---
> Faster isNotEmpty on collection

- lib/src/component/resize_sensor.dart
- test/over_react/component/resize_sensor_test.dart
ResizeSensor wrapper forces certain inline styles
Added mergedStyles to apply to wrapper styles so that users can override the inline styles.
1. pull branch
2. run `ddev test test/over_react_component_test.dart`
This could cause issues issue to how the resizesensor functions if used incorrectly but allows more consumer control.
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @evanweible-wf @maxwellpeterson-wf
> Add ability to override wrapper styles on resize-sensor

- lib/src/component_declaration/flux_component.dart
- test/over_react/component_declaration/flux_component_test.dart
- test/over_react/component_declaration/flux_component_test/basic.dart
- test/over_react/component_declaration/flux_component_test/prop_validation.dart
- test/over_react/component_declaration/flux_component_test/stateful/basic.dart
- test/over_react/component_declaration/flux_component_test/stateful/handler_precedence.dart
- test/over_react/component_declaration/flux_component_test/stateful/prop_validation.dart
- test/over_react/component_declaration/flux_component_test/stateful/redraw_on.dart
- test/over_react/component_declaration/flux_component_test/stateful/store_handlers.dart
- We needed some new lifecyle hooks to to implement tracing of Flux components. _These changes mirror those in https://github.com/Workiva/w_flux/pull/120; see that PR for more info._
- Add lifecycle methods to allow subclasses to safely hook into and override store redraw logic _These changes mirror those in https://github.com/Workiva/w_flux/pull/120; see that PR for more info._
- `listenToStoreForRedraw`
- `handleRedrawOn`
- Add shared tests to beef up test coverage for FluxUiStatefulComponent, which wasn't being fully excercised
- Work around mixins not calling super, which was causing prop validation and disposal logic in `UiProps` to not get called, and add functional regression tests
- I had these changes ready to go as part of a spike I did a while ago, but I thought they were …
> AF-1037 AF-1038 AF-2925 Flux components: fix disposal and prop validation, add hooks to support tracing

- CHANGELOG.md
- README.md
- pubspec.yaml
[Complete `1.28.0` Changeset](https://github.com/Workiva/over_react/compare/1.27.0...release-1.28.0)
---
> AF-2719 AF-2718 Release over_react 1.28.0

- lib/src/component_declaration/flux_component.dart
- test/over_react/component_declaration/flux_component_test.dart
- test/over_react/component_declaration/flux_component_test/handler_lifecycle.dart
- test/over_react/component_declaration/flux_component_test/stateful/basic.dart
- test/over_react/component_declaration/flux_component_test/stateful/handler_lifecycle.dart
- test/over_react/component_declaration/flux_component_test/stateful/handler_precedence.dart
- test/over_react/component_declaration/flux_component_test/stateful/prop_validation.dart
- test/over_react/component_declaration/flux_component_test/stateful/redraw_on.dart
- test/over_react/component_declaration/flux_component_test/stateful/store_handlers.dart
__I forgot to add the core changes I needed in https://github.com/Workiva/over_react/pull/193 🤦‍♂️__
> - We needed some new lifecyle hooks to to implement tracing of Flux components. _These changes mirror those in https://github.com/Workiva/w_flux/pull/120; see that PR for more info._
> - Add lifecycle methods to allow subclasses to safely hook into and override store redraw logic _These changes mirror those in https://github.com/Workiva/w_flux/pull/120; see that PR for more info._
- `listenToStoreForRedraw`
- `handleRedrawOn`
Also fixed test setup for changes I made in #193:
- https://github.com/Workiva/over_react/commit/0a7f3939473b9915ca6d7ac888f6c9b82517dfa4 "Make stateful test components actually stateful >_>"
Flux component store subscriptions
---
> __FYA:__ …
> AF-2937 Add hooks to support tracing

- lib/src/util/rem_util.dart
- test/over_react/util/rem_util_test.dart
Initializing the rem-change-detecting ResizeSensor synchronously can cause React warnings and get React into a bad state if this happens inside a component's `render`.
This can happen when `toRem` is used for the first time inside a component render method, as is case in w_context_menu's tests in master with the latest over_react.
- Initialize the sensor asynchronously so it doesn't happen within React lifecycle
- Update tests to support this
- Add tests
- Pull into w_context_menu and verify that all tests pass when running `ddev test`
Rem sensor
---
> AF-2994 Rem sensor async mount

- CHANGELOG.md
- README.md
- pubspec.yaml
__Bug fixes__
* #197 Mount the rem-change-detecting node for a `ResizeSensor` asynchronously to prevent react from getting into a bad state
* #195: Add hooks for Flux component redraws that occur in response to store updates: `listenToStoreForRedraw`/`handleRedrawOn` 
* Implements the stuff that was missed in #193
---
> __FYA:__ @greglittlefield-wf
> AF-2935 AF-2936 Release over_react 1.29.0

- lib/src/component_declaration/component_base.dart
- lib/src/util/react_util.dart
- test/over_react/component_declaration/transformer_integration_tests/component_integration_test.dart
- test/over_react/util/react_util_test.dart
With the new builder, the implementation of ```typedPropsFactory()``` will no longer be available on the component class defined by the consumer – it will only be available on the generated component class. As a consequence, all instances of ```new FooComponent().getDefaultProps()``` will break.
Add a ```defaultProps``` getter on the ```UiProps``` as an alternative way to retrieve a component's default props since instantiating the component class directly is an anti-pattern anyway.
---
@greglittlefield-wf @corwinsheahan-wf  @evanweible-wf
> AF-2922: add defaultProps getter to UiProp

- lib/src/transformer/impl_generation.dart
- test/vm_tests/transformer/impl_generation_test.dart
Proposed solution to https://jira.atl.workiva.net/browse/AF-3082
In anticipation of the Dart 2 transition, all props and state classes will have a static meta getter that is implemented to point to some symbol that needs to be generated, for example:
```
class FooProps {
static const PropsMeta meta = $metaForFooProps;
...
}
```
The transformer will need to transform this meta static field inline:
```
class Foo Props{
static const PropsMeta meta = $Props(FooProps);
```
- identify static members with the ```meta``` variable name and replace the initializer to use the appropriate ```Props()``` or ```State()```  implementation within the source file . 
Code changes and tests make sense 
CI passes 
---
@corwinsheahan-wf @evanweible-wf @greglittlefield-wf
> AF-3082: transform static meta fields

- lib/src/transformer/impl_generation.dart
- test/vm_tests/transformer/impl_generation_test.dart
The Dart 2 builder compatible boilerplate for factories includes an initialization statement for a UiFactory, e.g.:
```dart
@Factory()
- UiFactory<FooProps> Foo;
+ // ignore: undefined_identifier
+ UiFactory<FooProps> Foo = $Foo;
```
The problem is that the transformer throws an error if a UiFactory declaration is initialized. 
- Make the transformer aware that Dart 2 builder compatible boiler plate initializes the UiFactory so it doesn't throw an error when initialized correctly 
- Ensure (by adding a test) that the transformer will replace the initialization with: 
```([Map backingProps]) => new _$FooPropsImpl(backingProps);```
CI passes 
Code changes and added tests make sense 
---
> __FYA:__ @aaronlademann-wf @corwinsheahan-wf @evanweible-wf @greglittlefield-wf
> AF-3085: Transformer is aware of Dart 2 builder compatible boilerplate for Factories

- lib/src/transformer/declaration_parsing.dart
- lib/src/transformer/impl_generation.dart
- test/vm_tests/transformer/declaration_parsing_test.dart
- test/vm_tests/transformer/impl_generation_test.dart
With the new boilerplate, props and state classes (including abstract variants) will have a dual-class setup:
- a private class that defines the interface via uninitialized fields
- a public class that is essentially a stub and needs to be transformed to include the concrete accessor implementations
- When parsing declarations if a class annotated with ```@Props()``` or ```@State()``` is private look for the public ```Props|State``` class and add that to the ```declarationMap``` instead. 
- Remove the ```with _$<Name>(Props|State)AcessorsMixin``` from the public signature
- CI passes
- Code changes and tests make sense 
> __FYA:__ @corwinsheahan-wf @evanweible-wf @greglittlefield-wf
> AF-3084: Transformer should handle new boilerplate for Props and State classes

- lib/src/component/abstract_transition.dart
- lib/src/component/aria_mixin.dart
- lib/src/component/prop_mixins.dart
- lib/src/component_declaration/component_base.dart
- lib/src/transformer/declaration_parsing.dart
- lib/src/transformer/impl_generation.dart
- lib/src/util/class_names.dart
- test/vm_tests/transformer/declaration_parsing_test.dart
- test/vm_tests/transformer/impl_generation_test.dart
**_DEPENDS ON https://github.com/Workiva/over_react/pull/203_**
The existing API for obtaining a list of props or a list of prop keys from a props class is via `$Props` or `$PropKeys`, but these options rely on the transformer to replace these instances inline with actual lists. Going forward in Dart2 with a builder, this approach will not work.
The alternative is to introduce `PropsMeta` and `StateMeta` classes and (eventually) have the builder generate a static `meta` field on the generated version of every consumer-defined props and state class. This meta field will map to a `PropsMeta` or `StateMeta` instance that is generated by the builder.
This PR introduces this approach ahead of the Dart 2 transition by adding the classes and updating the transformer to generate the meta …
> AF-1896 Add PropsMeta and StateMeta classes as alternative to $Props/$PropKeys

- lib/src/transformer/impl_generation.dart
- test/vm_tests/transformer/impl_generation_test.dart
The transformer does not carry props/state mixins that have type parameters through to the generated `$` prefixed class. Example:
```
@PropsMixin()
abstract class FooPropsMixin<T> {...}
// This is an analyzer error since $FooPropsMixin does not have any type parameters.
// We need the typing on $FooPropsMixin since, under Dart 2, the implemented getters 
// and setters for the mixin are in $FooPropsMixin and not FooPropsMixin.
class BarProps extends UiProps with FooPropsMixin<String>, $FooPropsMixin<String> {...}
// In the generated output:
abstract class $FooPropsMixin {...}
```
Carry type parameters from the declared props/state mixin class and add tests.
* CI Passes
Mixin generation
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @kealjones-wk @evanweible-wf @sebastianmalysa-wf
> AF-3731: Carry type parameters on generated empty prop/state mixins classes

- lib/src/transformer/declaration_parsing.dart
- lib/src/transformer/impl_generation.dart
- lib/src/transformer/util.dart
- test/vm_tests/transformer/declaration_parsing_test.dart
- test/vm_tests/transformer/impl_generation_test.dart
- test/vm_tests/transformer/util_test.dart
The new version of codemod will update the initializer for private factories to `_$_Foo` if the factory name is `_Foo`. We need to relax the validation on this initializer to allow for this.
It will do the same with the `metaFor` constant.
All of the following variations should be supported:
- Factories:
- For a public factory:
- `$Foo`
- `_$Foo`
- For a private factory:
- `$_Foo`
- `_$_Foo`
- `_$Foo`
- Meta fields:
- For a public containing class:
- `$metaForFoo`
- `_$metaForFoo`
- For a private containing class:
- `$metaFor_Foo`
- `_$metaFor_Foo`
- `_$metaForFoo`
Note: once the Dart 2 transition is complete, these restrictions will be tightened down to:
- Factories:
- For a public factory:
- `_$Foo`
- For a private factory:
- `_$_Foo`
- Meta fields:
- For a public containing class:
- …
> AF-3749: Loosen validation on Factory and meta initializers

- doc/dart2_migration.md
The name/usage of the dart2 upgrade codemod script changed slightly, so the references in the over_react dart 2 migration guide need to be updated accordingly.
n/a
n/a
---
> AF-3912 Update Dart 2 codemod references

- CHANGELOG.md
- lib/src/component_declaration/transformer_helpers.dart
- lib/src/util/react_wrappers.dart
Fixes #213.
The following APIs are being removed in v2.0.0, and consequently need to be deprecated in a 1.x release:
- `getJsProps()` (use `getProps()` instead)
- `$Props` and `$PropKeys` (being replaced by the static `meta` getters on props/state classes)
n/a
---
> CPLAT-4061 Deprecate getJsProps(), $Props, and $PropKeys.

- CHANGELOG.md
- integrate/pubspec.yaml
- lib/src/util/react_wrappers.dart
- pubspec.yaml
- test/over_react/component_declaration/component_base_test.dart
- test/over_react/util/react_wrappers_test.dart
**_This is dependent on https://github.com/cleandart/react-dart/pull/153 - should be released in `react-dart v4.6.0`_**
`getJsProps()` is deprecated and the alternative (`unconvertJsProps()`) is available in react-dart 4.6.0.
Update usages of the deprecated `getJsProps()` to the new `unconvertJsProps()` method in react-dart.
- Calls to `getJsProps()`, should all be tested via unit tests
---
> CPLAT-4129: Use `unconvertJsProps()` instead of `getJsProps()`

- lib/src/util/react_wrappers.dart
- pubspec.yaml
- test/over_react/component_declaration/component_base_test.dart
- test/over_react/util/react_wrappers_test.dart
**_This is dependent on https://github.com/cleandart/react-dart/pull/153 - should be released in `react-dart v4.6.0`_**
`getJsProps()` was deprecated in 1.x and needs to be removed in 2.0.0.
Remove it and update usages to the new `unconvertJsProps()` method in react-dart.
- Calls to `getJsProps()`, should all be tested via unit tests
---
> CPLAT-4107 Remove getJsProps()

- pubspec.yaml
* [AF-392: Add workaround to NSM for Dart 2](https://github.com/Workiva/over_react/pull/207)
* [AF-3870: fix webstorm and vs code snippets](https://github.com/Workiva/over_react/pull/224)
* [AF-3912 Update Dart 2 codemod references](https://github.com/Workiva/over_react/pull/226)
* [CPLAT-4061 Deprecate getJsProps(), $Props, and $PropKeys.](https://github.com/Workiva/over_react/pull/230)
* [CPLAT-4129: Use `unconvertJsProps()` instead of `getJsProps()`](https://github.com/Workiva/over_react/pull/234)
Requested by: @evan.weible
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/1.30.2...Workiva:release_over_react_1.31.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/1.30.2...1.31.0 …
> CPLAT-3763 CPLAT-3762 Release over_react 1.31.0

- pubspec.yaml
* [[2.0.0-dev - dart2] AF-233 Consume react-dart callable class fixes](https://github.com/Workiva/over_react/pull/155)
* [CPLAT-1858, CPLAT-1857: Builder to build on backwards compatible boilerplate](https://github.com/Workiva/over_react/pull/211)
* [CPLAT-4031: Make builder compatible with Dart 2 only boilerplate](https://github.com/Workiva/over_react/pull/227)
* [CPLAT-3974 Remove workaround for DDC bug that is fixed in Dart 2](https://github.com/Workiva/over_react/pull/229)
* [CPLAT-4109: Update documentation for dart2](https://github.com/Workiva/over_react/pull/231)
* [CPLAT-4124: Changelog for V2](https://github.com/Workiva/over_react/pull/232)
* [CPLAT-4107 Remove getJsProps()](https://github.com/Workiva/over_react/pull/233)
Requested by: …
> CPLAT-246 CPLAT-245 Release over_react 2.0.0-alpha

- pubspec.yaml
To support the dual release line for 2.x, we need to widen the `over_react_test` range on the dart 1 version.
Widen it to include `over_react_test` 2.x.
n/a
---
> CPLAT-4154: Widen `over_react_test` range

- CONTRIBUTING.md
Pub/semver treats `-` version suffixes as pre-releases, meaning that a `1.x` version will be prioritized above it. We need to use the `+` suffix (which is treated as build metadata and has no impact on prioritization).
We already made this change when releasing over_react, just needed to update the documentation.
n/a
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @kealjones-wk @corwinsheahan-wf @maxwellpeterson-wf
> CPLAT-4297: Use `+dart1` suffix instead of `-dart1`

- .travis.yml
Since over_react commits generated files to source, we need to verify that there is a clean `git diff` after a build in CI.
Add `git diff` check to CI
None
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @kealjones-wk @evanweible-wf @maxwellpeterson-wf @sebastianmalysa-wf @smaifullerton-wk @seanburke-wf
> CPLAT-4326: Check for git changes after build

- build.yaml
The over_react builder actually only needs to apply to packages which specify over_react as a direct dependency. This will speed up build times, especially for packages with many dependencies. This was trialed in a fairly large internal repo, and a build with just the over_react builder running completed in ~35s vs ~1m30s without this change.
change auto_apply to dependents
* CI Passes
* Publink this over_react branch into this branch of [web_skin_dart](https://github.com/Workiva/web_skin_dart/tree/cplat-2734_dart2) and run `pub run build_runner build`. Verify that a build succeeds.
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @evanweible-wf @maxwellpeterson-wf @sebastianmalysa-wf @seanburke-wf @smaifullerton-wk
> CPLAT-4360: Set auto_apply to dependents

- lib/src/component_declaration/component_base.dart
- test/over_react/component_declaration/component_base_test.dart
With the upcoming change to the component_base class, setting the state / props directly will cause breakages. To give consumers a heads up, we should emit warnings in the browser console when they directly mutate props / state values inside a component instance.
Adding a class called WarnOnUpdate that watches for setting props / state directly and throws an error in dev mode using an Assert.
Run the test suite. Consider any ways the tests could return false results or miss a use case.
None that are known as it's only in dev that the error will be thrown.
> CPLAT-3616 Warn consumers about props / state mutation

- lib/src/component/abstract_transition_props.dart
- lib/src/component/aria_mixin.dart
- lib/src/component/prop_mixins.dart
- lib/src/component/resize_sensor.dart
- lib/src/util/class_names.dart
Over react 2.x+dart2 is using the Dart 2 only compatible boilerplate, since it does not have to be Dart 1 compatible. However, consumers who have been codemodded with backwards compatible over_react boilerplate will expect `$` prefixed props/state mixins to be exported from over_react. 
Add empty `$` prefixed mixins for Props mixin (there are no state mixins).
* CI Passes
None
> CPLAT-4646: Add empty `$` prefixed props mixins for backwards compatible consumers

- CHANGELOG.md
- CONTRIBUTING.md
- pubspec.yaml
* [CPLAT-4297: Use `+dart1` suffix instead of `-dart1`](https://github.com/Workiva/over_react/pull/248)
* [CPLAT-3616 Warn consumers about props / state mutation](https://github.com/Workiva/over_react/pull/249)
* [CPLAT-4326: Check for git changes after build](https://github.com/Workiva/over_react/pull/250)
* [CPLAT-4360: Set auto_apply to dependents](https://github.com/Workiva/over_react/pull/251)
* [CPLAT-4476: Create workaround for ddc bug related to uninitialized maps](https://github.com/Workiva/over_react/pull/252)
* [CPLAT-4646: Add empty `$` prefixed props mixins for backwards compatible consumers](https://github.com/Workiva/over_react/pull/253)
* [CPLAT-4110 Add Dart 2 only IDE snippets](https://github.com/Workiva/over_react/pull/254)
* …
> CPLAT-4217 CPLAT-4216 Release over_react 2.1.0

- README.md
- lib/src/util/react_wrappers.dart
- pubspec.yaml
- test/over_react/component_declaration/component_base_test.dart
- test/over_react/dom/render_test.dart
- test/over_react/util/react_wrappers_test.dart
react_dom.render changed its functionality in react 16.
- remove react_dom.render element throw test since it no longer throws with null passed as the element.
```
dependency_overrides:
react:
git:
url: git@github.com:cleandart/react-dart.git
ref: 5.0.0-wip
```
Then run `pub run build_runner test -r  --delete-conflicting-outputs -- -P dart2js`
Maybe?
---
> CPLAT-4460: Make compatible for use with react.dart 5.0.0-wip

- CHANGELOG.md
- lib/src/component_declaration/component_base.dart
- pubspec.yaml
- test/over_react/component_declaration/component_base_test.dart
Backpatch of #249 into the Dart 1.x line so that consumers get warnings without having to wait until they switch to Dart 2.
> * [#249] Warn consumers about props / state mutation 
>   * Directly mutating props and state is an antipattern and can cause unpredictable rendering.
>      Avoiding this will be especially important for components to behave correctly in React 16's [concurrent mode](https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#react-16x-q2-2019-the-one-with-concurrent-mode).
> CPLAT-4749 Release over_react 1.32.0

- CHANGELOG.md
- pubspec.yaml
* [CPLAT-4460: Make compatible for use with react.dart 5.0.0-wip](https://github.com/Workiva/over_react/pull/255)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.2.0+dart1...Workiva:release_over_react_2.2.0+dart2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.2.0+dart1...2.2.0+dart2
> CPLAT-4739 CPLAT-4738 Release over_react 2.2.0+dart2

- lib/over_react.dart
- lib/src/component/error_boundary.dart
- test/over_react/component/error_boundary_test.dart
- test/over_react_component_test.dart
In preparation for [React16 error boundary capabilities](https://reactjs.org/docs/error-boundaries.html), we should provide a canonical `ErrorBoundary` component.
Add the `ErrorBoundary` component.
> NOTE: This component doesn't actually hook into any ReactJS lifecycle yet.  It won't until support for ReactJS 16 is added to react-dart in version 5.0.0, and to over_react in version 3.0.0.
>
> _The wiring for those lifecycle methods will be implemented in a follow-up ticket, and merged into the 3.0.0-wip branch_.
None, new feature only.
---
> __FYA:__ @greglittlefield-wf @kealjones-wk
> CPLAT-3093 Add ErrorBoundary Component

- CHANGELOG.md
- pubspec.yaml
* [CPLAT-3093 Add ErrorBoundary Component](https://github.com/Workiva/over_react/pull/266)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.2.0+dart2...Workiva:release_over_react_1.33.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.2.0+dart2...1.33.0
> CPLAT-4845 CPLAT-4844 Release over_react 1.33.0

- CHANGELOG.md
- lib/src/component/resize_sensor.dart
- pubspec.yaml
- test/over_react/component/resize_sensor_test.dart
Chrome 73 released with some changes in flexbox behavior: https://www.chromestatus.com/feature/6736527476391936
This caused ResizeSensors that were flex parents or flex children and nested in a flexbox layout to not "shrink" vertically as expected, and instead overflow their container, even with a flex-basis of 0.
Add `min-height: 0`, which is the recommended work around.
- CI passes
- Smoke test in layouts that use ResizeSensor
ResizeSensor
---
> Release over_react 1.33.1

- CHANGELOG.md
- lib/src/component/resize_sensor.dart
- pubspec.yaml
- test/over_react/component/resize_sensor_test.dart
Brings #272 into the `+dart2` line-of-release.
> CPLAT-4896, CPLAT-4897 Release over_react 2.3.1+dart2

- CONTRIBUTING.md
The instructions for managing the dart 1 & 2 dual releases accidentally got overwritten by our recent rollout of updated contributing documentation.
Restore them.
n/a
Docs-only change.
> CPLAT-5243: Restore the dart 1 & 2 dual-release instructions

- CHANGELOG.md
- pubspec.yaml
* [CPLAT-4003 Upgrade to analyzer ^0.35.0](https://github.com/Workiva/over_react/pull/281)
* [CPLAT-5243: Restore the dart 1 & 2 dual-release instructions](https://github.com/Workiva/over_react/pull/284)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.4.1+dart1...Workiva:release_over_react_2.4.1+dart2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.4.1+dart1...2.4.1+dart2
> CPLAT-5235 CPLAT-5234 Release over_react 2.4.1+dart2

- lib/src/builder/builder.dart
- test/over_react/component_declaration/redux_component_test/test_reducer.g.dart
Syntax errors in the `example` dir cause the OverReact builder to unexpectedly fail the build when running `pbr test`
For example:
```
$ pbr test -- test/foo_test.dart
[INFO] Generating build script completed, took 329ms
[INFO] Reading cached asset graph completed, took 548ms
[INFO] Checking for updates since last build completed, took 973ms
[INFO] Running build completed, took 404ms
[INFO] Caching finalized dependency graph completed, took 301ms
[SEVERE] over_react:overReactBuilder on example/viewport/main.dart (cached):
There was an error parsing the compilation unit for file: w_virtual_components|example/viewport/main.dart
```
Downgrade parse error to fine so as to not fail build unnecessarily
If they're problematic, these errors will be handled further
down the line (e.g., …
> CPLAT-5632 Downgrade parse error to fine so as to not fail build unnecessarily

- lib/src/component_declaration/component_type_checking.dart
- lib/src/util/react_wrappers.dart
- pubspec.yaml
- test/over_react/util/react_wrappers_test.dart
react-dart 4.7.0 added some deprecations.
Remove references to deprecated jsify, getProperty, setProperty
Fix deprecation warnings from react-dart
- Verify there are no deprecation warnings coming from jsify/getProperty/setProperty usage
> CPLAT-5641 Fix js interop helper deprecations

- lib/src/component/error_boundary.dart
- lib/src/component_declaration/component_type_checking.dart
- test/over_react/component/error_boundary_test.dart
- test/over_react/component/fixtures/flawed_component.dart
- test/over_react/dom/fixtures/dummy_composite_component.dart
- web/demos/demos.dart
- web/demos/faulty-component.dart
- web/index.dart
- web/index.html
We want to release [react-dart `5.0.0`](https://github.com/cleandart/react-dart/milestone/2) _(which upgrades us to ReactJS 16)_ without depending on Dart 2 / `Component2` / `UiComponent2` - and all the new lifecycle methods that those expose.
However, one of the biggest behavioral differences between ReactJS 15 and 16 is that in 16, when a component throws - the entire component tree that it is a part of - __will unmount completely__.
This means that if we just unleash ReactJS 16 within the Workiva ecosystem, if any UI component in the entire shell throws - the entire shell will unmount (blank screen).  This is an unacceptable risk / experience.
In [CPLAT-3093](https://github.com/Workiva/over_react/pull/266), we created an `ErrorBoundary` component in over_react - and have since wrapped …
> CPLAT-5599 Add temporary JS error boundary

- lib/src/component/abstract_transition.dart
+ To prevent ReactJS setState warnings involving unmounted components
ReactJS `setState` warnings are being produced by components that extend from `AbstractTransitionComponent`.
Cancel the `transitionend` timer in-addition-to the subscription within `componentWillUnmount`.
Fix issue that causes ReactJS `setState` warnings to appear in the browser console.
Please review: @greglittlefield-wf  …
> CPLAT-1053 Cancel the transitionend timer when AbstractTransitionComponent unmounts

- CHANGELOG.md
- pubspec.yaml
* #292 Update `react` dependency to version `^4.7.0`, and remove references to deprecated `jsify`, `getProperty` and `setProperty` members.
* _Back-patched from the commits originally merged into the `2.x` line-of-release._
* #294 Fix issue with `AbstractTransitionComponent` that causes ReactJS `setState` warnings to appear in the browser console.
@greglittlefield-wf @joebingham-wk
> CPLAT-4951 Release over_react 1.33.2

- CHANGELOG.md
- lib/src/component/abstract_transition.dart
- lib/src/component_declaration/component_type_checking.dart
- pubspec.yaml
- test/over_react/util/react_wrappers_test.dart
* [CPLAT-5632 Downgrade parse error to fine so as to not fail build unnecessarily](https://github.com/Workiva/over_react/pull/288)
* [CPLAT-5641 Fix js interop helper deprecations](https://github.com/Workiva/over_react/pull/292)
* [CPLAT-1053 Fix issue with `AbstractTransitionComponent` that causes ReactJS `setState` warnings to appear in the browser console.](https://github.com/Workiva/over_react/pull/294)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/1.33.2...Workiva:release_over_react_2.4.2+dart2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/1.33.2...2.4.2+dart2
The logs for the request that created this PR can be found …
> CPLAT-5264 CPLAT-5263 Release over_react 2.4.2+dart2

- lib/src/util/react_wrappers.dart
- test/over_react/util/react_wrappers_test.dart
The original ticket ([CPLAT-5720](https://jira.atl.workiva.net/browse/CPLAT-5720)) was to ensure that `cloneElement` was compatible with `Component2` because there was an error being thrown when trying to clone. It was discovered that `cloneElement` did not gracefully handle when null was being passed in for the element parameter.
- Add short circuit that throws a not null argument error in `cloneElement`.
- Add a test checking for the short circuit behavior.
- Add additional test coverage for how `cloneElement` interacts with `Component2` and `JsBackedMap`.
- Removed unnecessary `equals()` matchers within `react_wrappers_test.dart`. This was not related to the ticket but was just for general cleanup. 
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 …
> CPLAT-5720 Add short circuit for cloneElement and increase test coverage for Component2

- lib/over_react.dart
- lib/src/component/error_boundary.dart
- lib/src/component/error_boundary.over_react.g.dart
- lib/src/component/error_boundary_mixins.dart
- lib/src/component/error_boundary_mixins.over_react.g.dart
- test/over_react/component/error_boundary_mixin_test.dart
- test/over_react/component/fixtures/custom_error_boundary_component.dart
- test/over_react/component/fixtures/custom_error_boundary_component.over_react.g.dart
- test/over_react/component/shared_error_boundary_tests.dart
- test/over_react_component_test.dart
* Now that the `Component2` class [implements / has js-interop bindings for error boundary lifecycle methods](https://github.com/cleandart/react-dart/pull/175), we can remove the [temporary JS error boundary we added](https://github.com/Workiva/over_react/pull/291) for the `3.0.0` release.
* Now that the `Component2()` annotation [has an argument that allows consumers to make any component an error boundary](https://github.com/Workiva/over_react/pull/293), we need to expose some props / state / component mixins to make it easy for consumers to make custom error boundaries that extend from some (or all) of the standard behaviors that our [`ErrorBoundary` component](https://github.com/Workiva/over_react/pull/266) implements.
* Remove the temporary JS error boundary in-favor-of the bindings …
> CPLAT-5037 Finish error boundary componentry

- lib/src/builder/generation/declaration_parsing.dart
- test/vm_tests/builder/declaration_parsing_test.dart
- test/vm_tests/builder/util.dart
- web/component2/src/demo_components/toggle_button.dart
Because of the inheritance structure of `Component2`, it is possible for a consumer to utilize lifecycle methods that no longer exist within React 16. To prohibit this, a check was needed to stop the builder if a component inheriting from `Component2` was calling one those methods.
- Add a check in `declaration_parsing.dart` looking for the legacy lifecycle methods within `Component2`.
- Fix `ToggleButton` because it was breaking the build process.
- Add Tests
@aaronlademann-wf @greglittlefield-wf @kealjones-wk @sydneyjodon-wk  …
> CPLAT-4843 Check for Legacy Lifecycle Methods in Component2 Declaration

- lib/src/builder/builder.dart
- test/vm_tests/builder/over_react_builder_test.dart
- test_fixtures/source_files/has_part_directive_missing_gen/no_declarations.dart
- test_fixtures/source_files/has_part_directive_missing_gen/with_declarations.dart
In cases where an `.over_react.g.dart` part directive are included in a file where there are no generations, the consumer doesn't get any error or warning messages from this builder.
Log a warning when a part directive exists, but there is no output.
Please review: @greglittlefield-wf @aaronlademann-wf @seanburke-wf 
> CPLAT-6056: Warn consumers if part directive is present but there's no generated output

- .travis.yml
- lib/src/util/handler_chain_util.dart
- test/over_react/util/handler_chain_util_test.dart
Closes #304
When Dart 2.4 is released (imminent), it comes with a small breaking language change that unfortunately affects the handler chaining utils in this package. @greglittlefield-wf and @georgelesica-wf were able to update them in such a way that works around the breaking change without adversely affecting existing usages.
- The `CallbackUtil` class no longer uses its generic type param (that previously was expected to extend `Function`) and instead explicitly marks the relevant types in the class body as `covariant Function` to achieve the same typing.
- The `CallbackUtilNArg` classes no longer specify a type param when extending `CallbackUtil` since it is unused.
- Run CI on the dart dev channel as well as stable to hopefully illuminate issues like this as early as possible.
Fixes …
> CPLAT-6138: Update handler chain utils for dart 2.4 compat

- CHANGELOG.md
- pubspec.yaml
* [CPLAT-6056: Warn consumers if part directive is present but there's no generated output](https://github.com/Workiva/over_react/pull/302)
* [CPLAT-6138: Update handler chain utils for dart 2.4 compat](https://github.com/Workiva/over_react/pull/306)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.4.3+dart1...Workiva:release_over_react_2.4.3+dart2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.4.3+dart1...2.4.3+dart2
> CPLAT-5793 CPLAT-5792 Release over_react 2.4.3+dart2

- lib/src/component/callback_typedefs.dart
- lib/src/component/prop_mixins.dart
- lib/src/component/prop_mixins.over_react.g.dart
- pubspec.yaml
In order to set up `_EventSimulatorAlias`s for react 16 / react.dart 5.0.0 pointer events, we must add the pointer event callbacks to `over_react` prop mixins.
Added pointer event callbacks to prop mixins.
@kealjones-wk @aaronlademann-wf @greglittlefield-wf @joebingham-wk 
> CPLAT 6157 Add pointer event callbacks to prop mixins

- CHANGELOG.md
- pubspec.yaml
* [CPLAT-6244: DO NOT MERGE: Upgrade to analyzer 0.36.x and build_web_compilers 2.x](https://github.com/Workiva/over_react/pull/310)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/2.4.4+dart1...Workiva:release_over_react_2.4.4+dart2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/2.4.4+dart1...2.4.4+dart2
> RM-53250 RM-53249 Release over_react 2.4.4+dart2

- CHANGELOG.md
- lib/src/builder/builder.dart
- test/vm_tests/builder/over_react_builder_test.dart
**This is a breaking change and has been PR'd to the 3.0.0 wip branch.**
The generated `.over_react.g.dart` part file is required for components to function on Dart2. Currently, the builder only logs a warning when the part file is missing, which could lead to a scenario where a consumer omits the part, ignores or doesn't see the warning, and runs into a runtime exception. It would be better to promote this error to one that fails the build so that it can be fixed immediately.
This PR promotes the log for the missing over_react part to the `SEVERE` level, which in turn causes the build to fail. In other words, this failure is being promoted from a runtime error to a build-time error.
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and …
> CPLAT-6287: Promote missing over_react part to severe log (fail the build)

- lib/src/component_declaration/component_base/component_base_2.dart
- lib/src/util/map_util.dart
- test/over_react/component_declaration/builder_integration_tests/component2/component_integration_test.dart
- test/over_react/component_declaration/component_base_test.dart
- test/over_react/util/map_util_test.dart
To increase the performance of forwarding props, we are adding the `addUnconsumedProps` and `addUnconsumedDomProps` methods.
- Add the `addUnconsumedProps` and `addUnconsumedDomProps` methods
- Deprecate the `copyUnconsumedProps` and `copyUnconsumedDomProps` methods
- Change `_validDomProps` from a `SplayTree` to a `Set`
> CPLAT-2281 optimize copy unconsumed props

- lib/src/builder/generation/impl_generation.dart
> How would one initialize a list field of a class?
>
> I have
>
> ```dart
> @State()
> class _$FooState extends UiState {
>   List<ReactElement> inputs = [];
> }
> ```
> 
> But get an error `Fields are stubs for generated setters/getters and should not have initializers.`. > If I remove the `= []`, i get errors claiming the list is null everywhere, so I’m not sure where to initialize it.
This error message could be better, and indicate how to initialize these values.
In error message, add note on where to initialize values
Improve error message for props/state variables with initializers
While we perform many automated checks before auto-merging, …
> CPLAT-6464 Improve error message for props/state variables with initializers

- lib/src/component_declaration/builder_helpers.dart
- lib/src/component_declaration/component_base/component_base_2.dart
- test/over_react/component_declaration/builder_integration_tests/component2/annotation_error_integration_test.dart
- test/over_react/component_declaration/builder_integration_tests/component2/annotation_error_integration_test.over_react.g.dart
- test/over_react/component_declaration/builder_integration_tests/component2/component_integration_test/annotation_error_component.dart
- test/over_react/component_declaration/builder_integration_tests/component2/component_integration_test/annotation_error_stateful_component.dart
- test/over_react/component_declaration/builder_integration_tests/component2/component_integration_test/annotation_error_stateful_default_props_component.dart
- test/over_react_component_declaration_test.dart
Right now, accidentally using `@Component()` instead of `@Component2()` gives you an unhelpful error message.
```
require.js:143 Uncaught Error: UngeneratedError: `Symbol("typedPropsFactoryJs")` should be implemented by code generation.
Ensure that you're running a build via build_runner.
at Object.dart.throw (dart_sdk.js:4604)
at basic_with_state._$BasicComponent.new.typedPropsFactoryJs (component_base.ddc.js:550)
at basic_with_state._$BasicComponent.new.newProps (component_base.ddc.js:388)
at basic_with_state._$BasicComponent.new.getDefaultProps (abstract_inheritance.ddc.js:1973)
at Object.react_client._registerComponent2 (react.ddc.js:864)
at react_client._registerComponent (react.ddc.js:849)
at Object.dart._checkAndCall (dart_sdk.js:4807)
at Object.dart.dcall (dart_sdk.js:4812)
at …
```
> CPLAT-6376 Add helpful error message when `@Component()` is used with UiComponent2

- lib/over_react.dart
- lib/src/component/dom_components.dart
- lib/src/component/fragment_component.dart
- lib/src/component_declaration/builder_helpers.dart
- lib/src/component_declaration/component_base.dart
- lib/src/component_declaration/component_base/component_base_2.dart
- lib/src/util/map_util.dart
- pubspec.yaml
- test/over_react/component_declaration/component_base_test.dart
Component2 was implemented via a large number of PRs, and has some parts that need to be cleaned up before release.
- Update imports to use new top-level entrypoints and not src/ files
- Stub in a custom UiComponent bridge for use in prop validation PR
- Add automatic typing to `UiStatefulComponent.setStateWithUpdater` callbacks:
```dart
setStateWithUpdater((prevState, props) {
// prevState is statically typed as TState
// props is statically typed as TProps
});
```
Please review: @aaronlademann-wf @kealjones-wk @joebingham-wk @sydneyjodon-wk  …
> CPLAT-6510 Finalize UiComponent2 - part 1 of X

- lib/src/component/dom_components.dart
In 3.1.0-wip, `DomProps.componentFactory` had its type loosened from `ReactDomComponentFactoryProxy` to `ReactComponentFactoryProxy`, which could break consumer usages that depended on members declared on that subclass.
Perform this change in 3.0.0 so that any breakages happen only when consumers perform a major bump, and not during automatic minor bumps.
`DomProps.componentFactory`: loosen typing to `ReactComponentFactoryProxy` and make mutable to support future HOC APIs
Please review: @aaronlademann-wf @kealjones-wk @joebingham-wk @sydneyjodon-wk  …
> CPLAT-6735 Backport type loosening of DomProps.componentFactory in 3.1.0-wip

- lib/over_react.dart
- lib/src/component/callback_typedefs.dart
- lib/src/component/prop_mixins.dart
- lib/src/component/prop_mixins.over_react.g.dart
- lib/src/util/handler_chain_util.dart
- pubspec.yaml
> ~~Depends on unreleased react-dart changes: https://github.com/cleandart/react-dart/pull/202~~
react-dart is [adding support for `SyntheticAnimationEvent` and `SyntheticTransitionEvent`](https://github.com/cleandart/react-dart/pull/202), and it would be nice to have typed prop getters / setters for events like `onTransitionEnd`, `onAnimationEnd`, etc. that make use of those interfaces.
Add `onTransitionEnd`, `onAnimationEnd`, `onAnimationIteration` and `onAnimationStart` to `UbiquitousPropsMixin` and all the analogous changes that go along with those additions.
Add typed props for CSS Transition and Animation DOM events.
Please review: @greglittlefield-wf …
> Add support for SyntheticAnimationEvent / SyntheticTransitionEvent

- lib/over_react.dart
- lib/src/component/callback_typedefs.dart
- lib/src/component/prop_mixins.dart
- lib/src/util/handler_chain_util.dart
- pubspec.yaml
This release incorporates the `SyntheticAnimationEvent` / `SyntheticTransitionEvent` support from #327 into the Dart 1 compatible line-of-release.
@kealjones-wk
> RM-53705 Release over react 2.5.0+dart1

- CHANGELOG.md
- pubspec.yaml
This release bumps the Dart SDK dependency lower-bound to `2.4.0` to align with our `build_web_compilers` dev-dependency lower-bound of `^2.1.1`.
@greglittlefield-wf @kealjones-wk @joebingham-wk @evanweible-wf
> RM-55763 Release over_react 2.5.1+dart2

- pubspec.yaml
quiver is out of date, conflict with other libs, in my case, [jaguar_orm](https://pub.dev/packages/jaguar_orm)
Change quiver version to ^2.0.0.
Change quiver version to ^2.0.0.
@Workiva/app-frameworks
> Upgrade to quiver ^2.0.0

- CHANGELOG.md
- pubspec.yaml
> Complete `2.5.2` Changsets:
>
> - [Dart 2](https://github.com/Workiva/over_react/compare/2.5.1+dart2...2.5.2+dart2)
> - Dart 1 (no changes)
* #333 Expand upper-bound of `quiver` dependency to `<3.0.0`
@greglittlefield-wf @kealjones-wk @joebingham-wk
> RM-56520 Release over_react 2.5.2+dart2

- test/over_react/component_declaration/component_base_test.dart
- test/over_react/util/react_wrappers_test.dart
[react-dart #209](https://github.com/cleandart/react-dart/pull/209) added a new assertment that changed broke tests in `3.1.0`. This PR fixes those broken test.
- Change `getJsChildren` to access props via `getProperty` instead of `unconvertJsProps`.
- Update a test case to use `JsBackedMap` to access props rather than `unconvertJsProps`.
@aaronlademann-wf @kealjones-wk @greglittlefield-wf @sydneyjodon-wk  …
> Fix uncovertJsProps calls

- lib/src/component/ref_util.dart
- lib/src/util/react_wrappers.dart
- pubspec.yaml
- test/over_react/util/react_wrappers_test.dart
- test/test_util/component2/one_level_wrapper.dart
- test/test_util/component2/one_level_wrapper.over_react.g.dart
- test/test_util/component2/two_level_wrapper.dart
- test/test_util/component2/two_level_wrapper.over_react.g.dart
**Dependent on https://github.com/cleandart/react-dart/pull/212**
---
There were some missing areas of test coverage for some of the new APIs added in 3.x, as well as some issues discovered while improving test coverage in the corresponding React 16 branches of react-dart.
- React wrapper utilities
- Fix `getProps` which did not work for `Component2`
- Clean up `cloneElement` implementation
- Add support for chaining refs on ReactElements with `createRef`-based refs
- Add lots of tests using Component2 instances as input …
> CPLAT-7460 Component2 utilities coverage, fix getProps, createRef chaining

- CHANGELOG.md
- lib/src/component/error_boundary.dart
- lib/src/component_declaration/component_type_checking.dart
- lib/src/util/react_wrappers.dart
- pubspec.yaml
- test/over_react/component/error_boundary_test.dart
- test/over_react/component/fixtures/flawed_component.dart
- test/over_react/component/fixtures/flawed_component.over_react.g.dart
- test/over_react/component_declaration/redux_component_test/test_reducer.g.dart
- test/over_react/dom/fixtures/dummy_composite_component.dart
- test/over_react/util/react_wrappers_test.dart
- web/index.dart
- web/index.html
- web/src/demos.dart
- web/src/demos/faulty-component.dart
- web/src/demos/faulty-component.over_react.g.dart
__ReactJS 16.x Support__
- The underlying `react` dependency ([version 5.0.0-alpha](https://github.com/cleandart/react-dart/pull/214)) now provides ReactJS version 16 `.js` source files.
- Support for the new / updated lifecycle methods from ReactJS 16 [will be released in version `3.1.0`](https://github.com/Workiva/over_react/milestone/3).
---
FYA @greglittlefield-wf @kealjones-wk @joebingham-wk @sydneyjodon-wk
> RM-58640 Release over_react 3.0.0-alpha.0+dart2 (Includes CPLAT-7545)

- lib/src/component/prop_mixins.dart
- lib/src/component/prop_mixins.over_react.g.dart
To ensure that over_react's DOM elements have the same attributes, and attribute behavior, as React, we should update the `open` attribute to be a bool.
- Change `open` from `dynamic` to `bool`.
- Update the `open` HTML attribute typing to match that of the JavaScript community (and React specifically). 
@aaronlademann-wf @greglittlefield-wf @kealjones-wk @sydneyjodon-wk  …
> CPLAT-7550 Change open attribute typing to bool

- build.yaml
Over_react specifies a builder which should only be applied to this package, since it generates to source, allowing this package to be published to the public pub repository. While this builder doesn't auto-apply to any dependents, it does still appear in the build script for these dependents. This comes with two negatives:
1) Consumers could inadvertently enable the source builder
2) It adds noise to the consumer's `build.dart` files
The build config actually supports private builder keys, so we should make this private. Nowhere within Workiva is using this builder (as expected).
While we perform many automated checks before auto-merging, some …
> Make local builder private

- lib/src/component/prop_mixins.dart
(Same as #351 but for Dart 1)
To ensure that over_react's DOM elements have the same attributes, and attribute behavior, as React, we should update the `open` attribute to be a bool.
- Change `open` from `dynamic` to `bool`.
- Update the `open` HTML attribute typing to match that of the JavaScript community (and React specifically). 
@aaronlademann-wf @greglittlefield-wf @kealjones-wk @sydneyjodon-wk  …
> CPLAT-7750 Update open attribute to bool (Dart 1)

- README.md
- example/builder/abstract_inheritance.dart
- example/builder/abstract_inheritance.over_react.g.dart
- example/builder/basic.dart
- example/builder/basic.over_react.g.dart
- example/builder/basic_library.over_react.g.dart
- example/builder/basic_with_state.dart
- example/builder/basic_with_state.over_react.g.dart
- example/builder/basic_with_type_params.dart
- example/builder/basic_with_type_params.over_react.g.dart
- example/builder/generic_inheritance_sub.dart
- example/builder/generic_inheritance_sub.over_react.g.dart
- example/builder/generic_inheritance_super.dart
- example/builder/generic_inheritance_super.over_react.g.dart
- example/builder/part_of_basic_library.dart
- example/builder/private_component.dart
- example/builder/private_component.over_react.g.dart
- example/builder/private_factory_public_component.dart
- example/builder/private_factory_public_component.over_react.g.dart
- example/context/components/my_context_component.dart
- lib/src/builder/README.md
We updated over_react's web example and snippets to use `UiComponent2`, but not the README and other markdown files or the `example` dir.
- Update the README to only have references to `UiComponent2` / `Component2`.
- Update the builder REDME to reference `UiComponent2`.
- Update all components in `example` to use `UiComponent2` (or it's equivalent, e.g. `UiStatefulComponent2`).
@aaronlademann-wf @kealjones-wk @sydneyjodon-wk @greglittlefield-wf  …
> CPLAT-7557 Update Component References to Component2

- lib/src/component/error_boundary.dart
- lib/src/component/error_boundary.over_react.g.dart
- test/over_react/component/error_boundary_test.dart
- test/over_react/component/fixtures/flawed_component.dart
- test/over_react/component/fixtures/flawed_component.over_react.g.dart
- test/over_react/component/fixtures/flawed_component_on_mount.dart
- test/over_react/component/fixtures/flawed_component_on_mount.over_react.g.dart
- test/over_react/component/fixtures/flawed_component_that_renders_a_string.dart
- test/over_react/component/fixtures/flawed_component_that_renders_a_string.over_react.g.dart
- test/over_react/component/fixtures/flawed_component_that_renders_nothing.dart
- test/over_react/component/fixtures/flawed_component_that_renders_nothing.over_react.g.dart
While testing the recent `3.0.0-alpha.0` release in a consumer library, a problem was discovered.
Currently, our `ErrorBoundary` component - when `props.fallbackUIRenderer` is not specified - will attempt to remount its child component tree when an error is caught.  In most cases, this is a sane default - however - if a component in that tree throws __every time it mounts__ - this causes a huge problem, since it creates a sort of "infinite loop" of `component throws in componentDidMount -> ErrorBoundary remounts the componnet -> component throws in componentDidMount -> ...`.  This infinite loop has the potential to completely lock up the main CPU thread.
> See code comments for much more in-depth information about what happens when / why
1. Add some internal component fields to …
> CPLAT-7606 Improve handling of “repeat” errors thrown from components wrapped by an ErrorBoundary

- lib/src/component/error_boundary.dart
- test/over_react/component/error_boundary_test.dart
- test/over_react/component/fixtures/flawed_component.dart
- test/over_react/component/fixtures/flawed_component_on_mount.dart
- test/over_react/component/fixtures/flawed_component_that_renders_a_string.dart
- test/over_react/component/fixtures/flawed_component_that_renders_nothing.dart
+ Dart 1 port of #350
> See #350 for full description
> CPLAT-7607 [Dart 1] Improve handling of “repeat” errors thrown from components wrapped by an ErrorBoundary

- CHANGELOG.md
- pubspec.yaml
Pulls included in this __Dart 2 only (alpha)__ release:
---
> RM-58745 Release over_react 3.0.0-alpha.1+dart2

- pubspec.yaml
Upper bounds of the `analyzer` version need to be increased so that we aren't prevented from pulling newer versions of packages (e.g., `build_web_compilers`) that depend on newer versions of `analyzer`.
- Update `Analyzer` dependency.
- Increase the `analyzer` dependency upper bound to ensure the package can consume the latest version of other dependencies. 
@aaronlademann-wf @greglittlefield-wf @kealjones-wk @sydneyjodon-wk
- Pull down branch.
- Upgrade analyzer.
- Verify it resolves to `0.38.5` and there are no static errors. …
> Update analyzer version range

- pubspec.yaml
There are no functional changes  in this Dart 1 only stable release. It is merely a version bump to match the [analogous `+dart2` patch release](https://github.com/Workiva/over_react/pull/367).
@corwinsheahan-wf
> RM-55765 Release over_react 2.5.3+dart1

- CHANGELOG.md
- pubspec.yaml
Pulls included in this Dart 2 only stable release:
#363 Widen `analyzer` dependency range
---
@corwinsheahan-wf @joebingham-wk @greglittlefield-wf @kealjones-wk
> RM-56701 Release over_react 2.5.3+dart2

- pubspec.yaml
There are no functional changes  in this Dart 1 only __alpha__ release. It is merely a version bump to match the [analogous `+dart2` patch release](https://github.com/Workiva/over_react/pull/369).
---
@corwinsheahan-wf @joebingham-wk @greglittlefield-wf @kealjones-wk
> RM-59138 Release over_react 3.0.0-alpha.2+dart1

- CHANGELOG.md
- pubspec.yaml
Pulls included in this Dart 2 only __alpha__ release:
#363 Widen `analyzer` dependency range
---
@corwinsheahan-wf @joebingham-wk @greglittlefield-wf @kealjones-wk
> RM-59140 Release over_react 3.0.0-alpha.2+dart2

- README.md
The link at https://github.com/Workiva/over_react#contributing 404s
Update the link from https://github.com/Workiva/over_react/blob/master/.github/CONTRIBUTING.md to https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md
N/A?
> Fix link to contributing docs

- lib/over_react.dart
- lib/src/component/error_boundary.dart
- lib/src/component/error_boundary.over_react.g.dart
- test/over_react/component/error_boundary_test.dart
Consumers currently have to set their own `onComponentDidCatch` prop callback, and then manually pass the errors passed to that callback into their own instance of `Logger`.
* Add logging functionality to `ErrorBoundary` so that consumers get it for free, and they can simply set `props.loggerName` to customize the logger name if they choose.
* Consumers can then simply listen to the `ErrorBoundaryComponent.logger` if they want to log it to the service of their choice.
Add logging functionality to the ErrorBoundary
Please review: @greglittlefield-wf @kealjones-wk @joebingham-wk @sydneyjodon-wk @maxwellpeterson-wf 
While we perform many automated checks before …
> CPLAT-7721 Add error logging to ErrorBoundary

- pubspec.yaml
This Dart 1 only __alpha__ release of over_react includes:
---
> RM-59378 Release over_react 3.0.0-alpha.3+dart1

- lib/src/component/error_boundary.dart
- pubspec.yaml
This Dart 1 only stable release of over_react includes:
---
> RM-59372 Release over_react 2.6.0+dart1

- CHANGELOG.md
- lib/src/component/error_boundary.dart
- lib/src/component/error_boundary.over_react.g.dart
- pubspec.yaml
This Dart 2 only stable release of over_react includes:
---
> RM-59375 Release over_react 2.6.0+dart2

- pubspec.yaml
This Dart 1 only stable release contains no functional changes, and is merely a version bump for the analogous [Dart 2 release](https://github.com/Workiva/over_react/pull/382).
> RM-59676 Release over_react 2.6.1+dart1

- CHANGELOG.md
- lib/src/component/prop_typedefs.dart
- pubspec.yaml
- test/over_react/component/fixtures/prop_typedef_fixtures.dart
- test/over_react/component/fixtures/prop_typedef_fixtures.over_react.g.dart
- test/over_react/component/fixtures/prop_typedef_fixtures/abstract_component_with_custom_render_prop.dart
- test/over_react/component/fixtures/prop_typedef_fixtures/component_consuming_abstract_custom_render_prop.dart
- test/over_react/component/fixtures/prop_typedef_fixtures/component_consuming_custom_render_prop.dart
- test/over_react/component/fixtures/prop_typedef_fixtures/component_extending_from_abstract_component_with_custom_render_prop.dart
- test/over_react/component/fixtures/prop_typedef_fixtures/component_with_custom_render_prop.dart
- test/over_react/component/prop_typedefs_test.dart
- test/over_react_component_test.dart
This Dart 2 stable release of over_react is a hotfix to update prop typedef to work around a [Dart 2.6 compiler regression](https://github.com/dart-lang/sdk/issues/38880)
> RM-59694 Release over_react 2.6.1+dart2 (Hotfix to update prop typedef to work around Dart 2.6 compiler regression (CPLAT-7898))

- CHANGELOG.md
- lib/src/component/prop_typedefs.dart
- pubspec.yaml
- test/over_react/component/fixtures/prop_typedef_fixtures.dart
- test/over_react/component/fixtures/prop_typedef_fixtures.over_react.g.dart
- test/over_react/component/fixtures/prop_typedef_fixtures/abstract_component_with_custom_render_prop.dart
- test/over_react/component/fixtures/prop_typedef_fixtures/component_consuming_abstract_custom_render_prop.dart
- test/over_react/component/fixtures/prop_typedef_fixtures/component_consuming_custom_render_prop.dart
- test/over_react/component/fixtures/prop_typedef_fixtures/component_extending_from_abstract_component_with_custom_render_prop.dart
- test/over_react/component/fixtures/prop_typedef_fixtures/component_with_custom_render_prop.dart
- test/over_react/component/prop_typedefs_test.dart
- test/over_react_component_test.dart
This Dart 2 __alpha__ release of over_react is a hotfix to update prop typedef to work around a [Dart 2.6 compiler regression](https://github.com/dart-lang/sdk/issues/38880)
> RM-59694 Release over_react 3.0.0-alpha.4+dart2 (Hotfix to update prop typedef to work around Dart 2.6 compiler regression (CPLAT--7900))

- pubspec.yaml
This Dart 1 only __alpha__ release contains no functional changes, and is merely a version bump for the analogous [Dart 2 release](https://github.com/Workiva/over_react/pull/383).
> RM-59674 Release over_react 3.0.0-alpha.4+dart1

- lib/src/component/prop_mixins.dart
- lib/src/component/prop_mixins.over_react.g.dart
When trying to build web_skin_dart, failures occurred because of a reliance on the DomProps `label` and `type` being dynamic. 
- Update `DomPropsMixin` and set `label` and `type` back to dynamic instead of String.
@aaronlademann-wf @greglittlefield-wf @kealjones-wk @sydneyjodon-wk 
> Change Type and Label Back to Dynamic

- lib/src/component/prop_mixins.dart
- lib/src/component/prop_mixins.over_react.g.dart
Reverting typing to remove errors in consumer repos.
- Revert `props_mixin.dart` to SHA 756a01af
- Revert DOM Prop and SVG prop typing changes back to `dynamic`
@aaronlademann-wf @kealjones-wk @greglittlefield-wf @sydneyjodon-wk 
> Revert DOM Props Typing

- analysis_options.yaml
- lib/over_react.dart
- lib/src/util/safe_render_manager/safe_render_manager.dart
- lib/src/util/safe_render_manager/safe_render_manager_helper.dart
- lib/src/util/safe_render_manager/safe_render_manager_helper.over_react.g.dart
- test/over_react/util/safe_render_manager/safe_render_manager_helper_test.dart
- test/over_react/util/safe_render_manager/safe_render_manager_test.dart
- test/over_react/util/safe_render_manager/test_component.dart
- test/over_react/util/safe_render_manager/test_component.over_react.g.dart
- test/over_react_util_test.dart
There were some cases where top-level `react_dom.render`/`.unmountComponentAtNode` calls were being done from within the event handlers and lifecycle methods of React components, which encountered timing-related issues in React 16.
- Add SafeRenderManager:
> A class that manages the top-level rendering of a `ReactElement` into a given node,
with support for safely rendering/updating via `render` and safely unmounting via `tryUnmount`.
> 
> Content is also unmounted when this object is `dispose`d.
> 
> This is useful in cases where `react_dom.render` or `react_dom.unmountComponentAtNode`
may or may not be called from React events or lifecycle methods, which can have
undesirable/unintended side effects.
> 
> For instance, calling `react_dom.unmountComponentAtNode` can unmount a component …
> CPLAT-7979: Add SafeRenderManager

- analysis_options.yaml
- lib/over_react.dart
- lib/src/util/safe_render_manager/safe_render_manager.dart
- lib/src/util/safe_render_manager/safe_render_manager_helper.dart
- test/over_react/util/safe_render_manager/safe_render_manager_helper_test.dart
- test/over_react/util/safe_render_manager/safe_render_manager_test.dart
- test/over_react/util/safe_render_manager/test_component.dart
- test/over_react_util_test.dart
Dart 1 version of https://github.com/Workiva/over_react/pull/390 —see that PR for details.
All commits from that PR (other than generated code updates) were cherry-picked without merge conflicts.
Two additional commits were added adding Dart 1 compatibility and fixing tests in Dart 1:
https://github.com/Workiva/over_react/pull/396/files/b9f81fb542de38f7cabfb9cf5c2908429b4e7961..0242e043715861d8e0d9f850f5c8ac575598e4ea
> CPLAT-8011 Add SafeRenderManager (Dart 1)

- CHANGELOG.md
- pubspec.yaml
This Dart 2 only __alpha__ release of over_react includes:
* #390 Add new SafeRenderManager utility
---
> RM-59772 Release over_react 3.0.0-alpha.5+dart2

- pubspec.yaml
This Dart 1 only __alpha__ release of over_react includes:
* #396 Add new SafeRenderManager utility
---
> RM-59774 Release over_react 3.0.0-alpha.5+dart1

- lib/src/util/safe_render_manager/safe_render_manager.dart
- lib/src/util/safe_render_manager/safe_render_manager_helper.dart
- test/over_react/util/safe_render_manager/safe_render_manager_helper_test.dart
- test/over_react/util/safe_render_manager/safe_render_manager_test.dart
This PR addresses minor feedback in https://github.com/Workiva/over_react/pull/390, which was merged with the intention of following up with fixes later.
> Address CR feedback for SafeRenderManager

- analysis_options.yaml
- lib/over_react.dart
- lib/src/util/safe_render_manager/safe_render_manager.dart
- lib/src/util/safe_render_manager/safe_render_manager_helper.dart
- pubspec.yaml
- test/over_react/util/safe_render_manager/safe_render_manager_helper_test.dart
- test/over_react/util/safe_render_manager/safe_render_manager_test.dart
- test/over_react/util/safe_render_manager/test_component.dart
- test/over_react_util_test.dart
This Dart 1 only __stable__ release of over_react includes:
* #396 Add new SafeRenderManager utility
---
> RM-59766 Release over_react 2.7.0+dart1

- lib/src/component_declaration/component_base.dart
- test/over_react/component_declaration/component_base_test.dart
I've hit the following exception a few times in tests/app when trying to use `manageAndReturnTypedDisposable`.
```
NoSuchMethodError: invalid member on null: 'manageAndReturnTypedDisposable' at package:over_react/src/component_declaration/component_base.dart 371:24
```
This seems to only happen if you don't call another `manage*Disposable` (`manageDisposable`, `manageAndReturnDisposable`) method before `manageAndReturnTypedDisposable`, where `_disposableProxy` hasn't been initialized and is still `null`.
call `_getDisposableProxy()` like all the other `manage*Disposable` methods do to initialize `_disposableProxy` if it hasn't been initialized.
Fix an issue where calling `manageAndReturnTypedDisposable` throws a null exception unless another `manage` method is called first.
_[See …
> `manageAndReturnTypedDisposable` null exception

- pubspec.yaml
This Dart 1 only __alpha__ release contains no changes.  It is merely an analogous version bump to go alongside the [`3.0.0-alpha.6+dart2` release](https://github.com/Workiva/over_react/pull/406).
---
> RM-60452 Release over_react 3.0.0-alpha.6+dart1

- CHANGELOG.md
- pubspec.yaml
This Dart 2 only __alpha__ release of over_react includes:
* #404 Clean up Dart 2 lints
* #371 Fix `manageAndReturnTypedDisposable` null exception
---
> RM-60450 Release over_react 3.0.0-alpha.6+dart2

- pubspec.yaml
This Dart 1 only stable, __major__ release of over_react includes:
- The underlying `.js` files provided by this package are now ReactJS version `16.10.1`.
- Support for the new / updated lifecycle methods from ReactJS 16 [will be released in version `3.1.0`](https://github.com/Workiva/over_react/milestone/3). __These new lifecycle methods will only be supported in Dart 2.__
> See: [The over_react 3.0.0+dart2 release](https://github.com/Workiva/over_react/pull/408) for more details about breaking changes, etc.
---
🚨 __NOTE: This will be the last release of over_react that supports the Dart 1 SDK.__   🚨
> RM-60877 Release over_react 3.0.0+dart1 (stable)

- CHANGELOG.md
- README.md
- pubspec.yaml
This stable, __major__ release of over_react includes:
- The underlying `.js` files provided by this package are now ReactJS version `16.10.1`.
- Support for the new / updated lifecycle methods from ReactJS 16 [will be released in version `3.1.0`](https://github.com/Workiva/over_react/milestone/3).
> Full List of `3.0.0` Changes:
>
> - [Dart 2](https://github.com/Workiva/over_react/compare/2.7.0+dart2...3.0.0+dart2)
> - [Dart 1](https://github.com/Workiva/over_react/compare/2.7.0+dart1...3.0.0+dart1)
---
__ReactJS 16 breaking changes__
> Source: https://reactjs.org/blog/2017/09/26/react-v16.0.html#breaking-changes
Breakage | Migration path
-- | --
Errors in the render and lifecycle methods now unmount the component tree by default. | To prevent this, add error boundaries to the …
> RM-60869 Release over_react 3.0.0+dart2 (stable)

- CHANGELOG.md
- pubspec.yaml
This Dart 2 only, stable patch release of over_react lowers the Dart SDK lower-bound to `2.4.0`. It was accidentally increased to `2.4.1` in the 3.0.0 release.
---
> RM-60981 Release over_react 3.0.1+dart2

- pubspec.yaml
This Dart 1 only, stable patch release of over_react includes no changes. It is merely an analogous version bump to align with the [dart 2 release](https://github.com/Workiva/over_react/pull/410).
---
> RM-60992 Release over_react 3.0.1+dart1

- CHANGELOG.md
- pubspec.yaml
Dependency updates:
- Lower the dart_style constraint from ^1.3.1 to ^1.2.5 to help avoid version lock in downstream packages
- Open up built_value range to include 8.0.0
> RM-60496 RM-60495 Release over_react 3.0.2+dart2

- pubspec.yaml
Counterpart to https://github.com/Workiva/over_react/pull/412, no changes for Dart 1
> RM-61028 RM-61027 Release over_react 3.0.2+dart1

- lib/over_react.dart
- lib/src/component_declaration/component_base_2.dart
- pubspec.yaml
- test/over_react/component_declaration/builder_integration_tests/component2/constant_required_accessor_integration_test.dart
- test/over_react/component_declaration/builder_integration_tests/component2/required_accessor_integration_test.dart
- test/over_react/util/prop_key_util_test_dart2.dart
- web/component2/src/demo_components/prop_validation.dart
> __DEPENDS ON https://github.com/cleandart/react-dart/pull/228__
1. The [`Component2.propKeys` boilerplate is being shortened](https://github.com/cleandart/react-dart/pull/228) in react, so we need to update the analogous `UiComponent2` members.
2. The top level `getPropKey` utility function led to unnecessarily verbose calls when used within `UiComponent2` instances.
1. Update the `UiComponent2.propKeys` return signature to match the new one from `Component2`, and update the JS interop bits to account for the new function signature on the Dart side of things.
2. Add a `UiComponent2.getPropKey` instance method that proxies a call to the _(now private)_ top level `getPropKey` utility function.  This new instance method will be able to infer the type of the prop factory.
__Before:__ …
> CPLAT-8024 Shorten propTypes boilerplate

- test/over_react/component/dom_components_test.dart
- test/over_react/component_declaration/component_base_test.dart
- test/over_react_component_declaration_test.dart
After many rounds of changes and test additions, we needed to do a final sweep to ensure UiComponent2 was fully tested. 
- Add missing tests for `newProps` and disposal behavior
- Add tests for typed `setStateWithUpdater`
Boyscouting:
- Re-sort of Component2 tests, making it easier to visually compare the… …
- Fix Dom.* function source getting emitted in test names
- Add additional UiComponent2 test coverage …
> CPLAT-2276 Finalize UiComponent2 test coverage

- CHANGELOG.md
- lib/src/component/prop_mixins.dart
- lib/src/component/prop_mixins.over_react.g.dart
- pubspec.yaml
This hotfix of over_react restores the `xmlLang`, `xmlSpace`, `y1`, `y2`, `y` members that were accidentally removed from `SvgProps` in the 3.1.0 release.
---
@greglittlefield-wf @joebingham-wk @kealjones-wk @dustyholmes-wf @laurameckley-wk
> RM-61371 Release over_react 3.1.1 (Restore accidentally removed SvgProps members)

- CHANGELOG.md
- lib/over_react.dart
- lib/src/component_declaration/component_base_2.dart
- pubspec.yaml
- test/over_react/component_declaration/builder_integration_tests/component2/constant_required_accessor_integration_test.dart
- test/over_react/component_declaration/builder_integration_tests/component2/required_accessor_integration_test.dart
- web/component2/src/demo_components/prop_validation.dart
This hotfix of over_react restores the `getPropKey` function that was accidentally made private in the 3.1.0 release.
---
@greglittlefield-wf @jimhotchkin-wf
> RM-61377 Release over_react 3.1.2

- CHANGELOG.md
- lib/src/component_declaration/component_base_2.dart
- pubspec.yaml
- test/over_react/component_declaration/component2_type_checking_test/type_inheritance/subsubtype_of_component1.dart
- test/over_react/component_declaration/component2_type_checking_test/type_inheritance/subsubtype_of_component1.over_react.g.dart
- test/over_react/component_declaration/component2_type_checking_test/type_inheritance/subtype_of_component1.dart
- test/over_react/component_declaration/component2_type_checking_test/type_inheritance/subtype_of_component1.over_react.g.dart
- test/over_react/component_declaration/component_type_checking_test.dart
This patch release of over_react includes a hotfix for an issue that prevents `UiComponent` instances from being declared as sub-types of `UiComponent2` instances via the `subtypeOf` argument in a `Component2()` annotation:
__Causes RTEs:__
```dart
@Component2(subtypeOf: SomeVersion1Component)
class MyComponent2Instance extends UiComponent2<MyComponent2Props> {}
```
This patch prevents the above code from throwing at runtime.
---
> RM-61380 Release over_react 3.1.3 (Allow UiComponent2 to subtype UiComponent)

- CHANGELOG.md
- lib/src/component_declaration/component_base_2.dart
- lib/src/util/map_util.dart
- pubspec.yaml
- test/over_react/component_declaration/builder_integration_tests/component2/constant_required_accessor_integration_test.dart
- test/over_react/util/map_util_test.dart
This patch release of over_react includes:
- Previously, this method would not show up as deprecated because certain IDEs would default to the base implementation (`Component.redraw`) - instead of the newer, deprecated `Component2.redraw`.
```dart
class FooComponent extends UiComponent<FooProps> {
@override
get consumedProps => const [];
@override
render() {
return (SomethingElse()
// This does not cause a runtime exception
..addProps(copyUnconsumedProps())
)(props.children);
}
}
class FooComponent extends UiComponent2<FooProps> {
@override
get consumedProps => const [];
@override
render() {
return (SomethingElse()
// This was throwing a runtime exception
..modifyProps(addUnconsumedProps)
)(props.children);
}
}
```
---
> RM-61406 Release over_react 3.1.4

- lib/src/over_react_redux/devtools/middleware.dart
- lib/src/over_react_redux/over_react_redux.dart
- test/over_react_redux/connect_test.dart
1. Issue was encountered with mapStateToPropsWithOwnProps.
2. Gitter chat revealed a desire to have errors reveal more information about the issue during errors thrown via json encoding.
1. Fix typo that cause mapStateToPropsWithOwnProps to not fire correctly
2. Update error messages to provide more guidance and log out the error encountered for more context.
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.m …
> CPLAT-8499 OverReactRedux: fix bug and make error messages more verbose

- lib/src/component/error_boundary_mixins.dart
- test/over_react/component/shared_error_boundary_tests.dart
Currently, an `ErrorBoundary` can be fooled to think that the UI is recoverable by a call stack varying even though the same two or three call stack repeatedly occurs.
- Keep track of all errors thrown in the same 5 second interval.
- Add `ErrorBoundary` fix that helps to prevent recovery attempts after the UI is unrecoverable.
@kealjones-wk @greglittlefield-wf @sydneyjodon-wk 
- Add a virtualized list as the content to a side panel element (I was using header_footer_properties_panel_content.dart). You can override that file with [this gist](https://gist.github.com/joebingham-wk/0600617c72c9eee9f90ce4634e4fe454) that has a virtual list.
- Override …
> CPLAT-8603 Add Multiple Error Check to ErrorBoundary

- lib/src/builder/README.md
The code markdown was not rendering properly due to a misplaced "```"
Remove the extra "```"
Remove typo in builder README.md
Please review: @Workiva/app-frameworks
> Fixed typo in builder README.md

- .travis.yml
- pubspec.yaml
- test/over_react/component_declaration/builder_integration_tests/component2/constant_required_accessor_integration_test.dart
- test/over_react/component_declaration/builder_integration_tests/component2/required_accessor_integration_test.dart
The prop type tests for over_react were still using the outdated `propType` testing methods. Refactoring the tests keeps them up to date with the latest APIs and helps provide examples of how to use our testing utils.
- Refactor any test the tests `propTypes`
@kealjones-wk @greglittlefield-wf @sydneyjodon-wk @aaronlademann-wf 
> CPLAT-7471 Refactor Prop Type Tests

- test/over_react_redux/connect_test.dart
- test/over_react_redux/fixtures/counter.dart
The NPM package `react-redux` that over_react consumes from react-dart [changed its "Provider" component from a class based component to a function component](https://github.com/reduxjs/react-redux/pull/1377) in the 7.1.1 __patch__ version. This broke some expectations that our tests had in place for over_react_redux.
- Remove usage of Class only features from over_react_redux Provider tests   …
> CPLAT-8834 fix tests for redux 7.1.3

- lib/over_react.dart
- lib/src/component/error_boundary.dart
- lib/src/component/error_boundary_mixins.dart
- lib/src/component/error_boundary_recoverable.dart
- lib/src/component/error_boundary_recoverable.over_react.g.dart
- test/over_react/component/error_boundary_test.dart
- test/over_react/component/fixtures/custom_error_boundary_component.dart
- test/over_react/component/shared_error_boundary_tests.dart
- test/over_react_component_test.dart
- web/component2/index.dart
- web/component2/index.html
- web/component2/src/demos.dart
- web/src/demos/faulty-on-mount-component.dart
- web/src/demos/faulty-on-mount-component.over_react.g.dart
Even with ErrorBoundaries in place, we were seeing issues with the app still entirely unmounting even with the logic for "unrecoverable" errors. It turns out in React if an ErrorBoundary catches an error, it will have its error lifecycle methods called, if on that render cycle the component throws during the render cycle React will move up the tree to a parent ErrorBoundary instead. And due to all the Previous ErrorBoundaries having the same logic none would ever handle the render cycle error.
- Updated `ErrorBoundaryComponent` to handle render cycle unrecoverable errors (hopefully this wont happen often.)
- Moved the previous `ErrorBoundary` logic into `RecoverableErrorBoundary` and nested it as the first child of the updated `ErrorBoundary`.
- This nesting allows us to know that if …
> CPLAT-8600: Unrecoverable ErrorBoundary Fix

- CHANGELOG.md
- pubspec.yaml
The latest release of over_react includes:
- #435 Fix issue with `ErrorBoundary` that causes errors thrown within the `render` phase of the component lifecycle to bubble up to parent `ErrorBoundary` components, which resulted in entire consumer applications locking up / crashing / unmounting.
- __DEPRECATIONS:__ `ErrorBoundaryMixin`, `ErrorBoundaryPropsMixin` and `ErrorBoundaryStateMixin` are deprecated and will be removed in the 4.0.0 release.
- To create a custom error boundary moving forward, create an HOC that wraps around the `ErrorBoundary` component instead. 
- #433 Refactor `propTypes` tests
- #440 Make over_react_redux tests compatible with version `^7.1.1` of the redux JS library
- #442 Remove Dart 2.4.1 phase from the CI build
- #428 Add examples of components that have …
> RM-63295 Release over_react 3.1.7

- lib/over_react.dart
- lib/src/component/fragment_component.dart
- lib/src/component/strictmode_component.dart
- pubspec.yaml
- test/over_react/component/strictmode_component_test.dart
- test/over_react_component_test.dart
In order to move ourselves closer to concurrent mode the `StrictMode` component will help us by alerting devs with console errors about issues that are bad practice, deprecated usages, or will prevent concurrent mode.
StrictMode currently helps with:
- Identifying components with unsafe lifecycles
- Warning about legacy string ref API usage
- Warning about deprecated findDOMNode usage
- Detecting unexpected side effects
- Detecting legacy context API
- Implemented StrictMode Component props and factory.
- Added test for StrictMode rendering.
- Added StrictMode Component.
While we perform many automated checks before auto-merging, some manual …
> CPLAT-9057: Implement StrictMode component

- app/over_react_redux/todo_client/lib/src/actions.dart
- app/over_react_redux/todo_client/lib/src/actions.g.dart
- app/over_react_redux/todo_client/lib/src/components/app_bar/app_bar_local_storage_menu.dart
- app/over_react_redux/todo_client/lib/src/components/app_bar/save_as_menu_item.dart
- app/over_react_redux/todo_client/lib/src/local_storage.dart
- app/over_react_redux/todo_client/lib/src/store.dart
- app/over_react_redux/todo_client/test/unit/browser/redux/store_test.dart
The reducer was not pure, which is a big no-no in Redux: https://redux.js.org/style-guide/style-guide#reducers-must-not-have-side-effects
- 00a1cd0 Move local storage state manipulation into middleware to make reducer pure
- c2ec75a Fix save menu not detecting changes (fix to a bug introduced in the first commit)
- 73f2538 Remove unused type from actions, simplify JSON representation and payloads
- The `type` field wasn't used, and the Action class name is already retrieved from the middleware, so I removed it.
- This removes the extra `{"value": ...}` object that clutters up each action for the dev tools
<table><thead><tr><th>Before</th><th>After</th></thead><tbody><tr>
<td><img width="361" alt="Screen Shot 2020-01-16 at 3 21 52 PM" …
> Localstorage reducer/middleware cleanup

- lib/src/util/rem_util.dart
- test/over_react/component_declaration/redux_component_test/test_reducer.g.dart
Computed font size of the HTML node being calculated incorrectly when the page is refreshed while zoomed. See: https://bugs.chromium.org/p/chromium/issues/detail?id=1043349. 
Measure a container to determine how big 1rem is.
This update fixes issue in our product when document/spreadsheet doesn't fully expand after page refresh while zoomed.
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual-testing-c …
> CPLAT-9174: Fix bug in TDC when, document doesn't fully expand

- pubspec.yaml
* [CPLAT-6104 Add over_react_redux example app](https://github.com/Workiva/over_react/pull/439)
* [CPLAT-9057: Implement StrictMode component](https://github.com/Workiva/over_react/pull/447)
* [CPLAT-9092 Add built_redux to Redux Docs](https://github.com/Workiva/over_react/pull/452)
* [CPLAT-9174: Fix bug in TDC when, document doesn't fully expand](https://github.com/Workiva/over_react/pull/453)
Requested by: @kealjones-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/3.1.7...Workiva:release_over_react_3.2.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/3.1.7...3.2.0
The logs for the request that created this PR can be found …
> RM-63989 RM-63988 Release over_react 3.2.0

- CHANGELOG.md
Forgot to update changelog for 3.2.0 release
- Add changelog entry for 3.2.0 release 
> RM-60994 Release over_react 3.2.0

- lib/src/over_react_redux/over_react_redux.dart
- test/over_react_redux/connect_test.dart
Wrapping Dart components in `connect` unexpectedly jsified props, causing `Map` props to show up as JS Objects when read by the component.
- Use a ReactDartComponent2FactoryProxy instead of a JSComponentFactoryProxy, since the connect component really behaves more like a Dart component (see code comment in connect).
- Add regression test
- Fix accidental jsification of Map/Function Dart props in certain cases when using `connect`
Please review: @aaronlademann-wf @joebingham-wk @sydneyjodon-wk 
FYI: @matthewnitschke-wk @kealjones-wk  …
> CPLAT-9715 Fix accidental jsification of Map/Function Dart props when using `connect`

- CHANGELOG.md
- pubspec.yaml
* [CPLAT-9715 Fix accidental jsification of Map/Function Dart props when using `connect`](https://github.com/Workiva/over_react/pull/461)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/3.2.0...Workiva:release_over_react_3.2.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/3.2.0...3.2.1
> RM-66264 RM-66263 Release over_react 3.2.1

- lib/src/component/ref_util.dart
- lib/src/component_declaration/component_type_checking.dart
- lib/src/over_react_redux/over_react_redux.dart
- test/over_react/component_declaration/component_type_checking_test.dart
- The JS function-component HOCs returned by connect/forwardRef caused a failing assertion since they weren't considered valid `isPotentiallyValidComponentType`
- HOCs didn't have type meta information, meaning that type-checking wouldn't work as expected on them
- e.g., `isComponentOftype(ConnectedFoo()(), Foo)` would return false
- Fix `isPotentiallyValidComponentType` to support function types, fixing failing assertion
- Add regression test that also tests new type checking functionality
- `connect`/`forwardRef` HOCs
- Fix component type-checking error when passing into `isComponentOfType`
- Match against the type of the wrapped component, as expected.
Please …
> CPLAT-9796 HOC type checking fixes and improvements

- lib/src/component_declaration/flux_component.dart
- pubspec.yaml
- test/over_react/component_declaration/flux_component_test/component2/flux_component_test.dart
As part of the new boilerplate work, consumers will no longer be able to extend props classes from anything other than `UiProps`. This means that `FluxUiProps` will need to exist in the form of a mixin.
1. Deprecate `FluxUiProps`
2. Add `FluxUiPropsMixin`
Please review: @joebingham-wk @sydneyjodon-wk @greglittlefield-wf 
> CPLAT-9650 Add base mixins for flux props classes

- app/over_react_redux/todo_client/pubspec.yaml
- pubspec.yaml
#448 pointed out that our current version constraint for `redux` disallows the latest major release (`4.0.0`).
Open up the upper bound of the `redux` and `redux_dev_tools` dependencies.
* There do not appear to be any breaking changes in the [release notes for redux.dart 4.0.0](https://github.com/johnpryan/redux.dart/blob/master/CHANGELOG.md#400).
* No breakages are apparent when testing the todo app locally
* Tests passed locally 
Allow redux.dart version 4
Please review: @greglittlefield-wf @joebingham-wk @sydneyjodon-wk @kealjones-wk @UnHumbleBen  …
> Allow redux.dart version 4

- lib/src/component/ref_util.dart
- lib/src/component_declaration/component_type_checking.dart
- lib/src/over_react_redux/over_react_flux.dart
- lib/src/over_react_redux/over_react_redux.dart
- test/over_react/component/fixtures/basic_ui_component.dart
- test/over_react/component/fixtures/basic_ui_component.over_react.g.dart
- test/over_react/component/forward_ref_test.dart
- test/over_react/component_declaration/component_type_checking_test.dart
- test/over_react_redux/connect_flux_test.dart
- test/over_react_redux/connect_test.dart
- test/over_react_redux/fixtures/non_component_two_counter.dart
- test/over_react_redux/fixtures/non_component_two_counter.over_react.g.dart
Currently, wrapping a `UiComponent` in one of our HOC utilities (`forwardRef`, `connect`, `connectFlux`) will throw a cryptic error, and there's no mention of that on the utility doc comments.
- Update the doc comments for `connect`, `connectFlux`, and `forwardRef` noting that the component being wrapped should extend `Component2`.
- Add a utility that throws when a `Component` is passed in
- Add tests
- Ensure `connect`, `connectFlux`, and `forwardRef` fail gracefully when an invalid component gets passed in.
@aaronlademann-wf @greglittlefield-wf @sydneyjodon-wk  @willdrach-wk 
While we perform many automated checks before auto-merging, some …
> CPLAT-9691 Improve HOC Errors

- lib/src/builder/builder.dart
- lib/src/builder/generation/parsing/declarations.dart
Add a generation order and sort the declarations by that list.
- Add a `type` getter that explicitly states what type of declaration it is.
- Sort the declarations by a defined order.
@greglittlefield-wf 
> Change order of generated declarations

- lib/src/builder/generation/impl_generation.dart
- lib/src/builder/generation/parsing/declarations.dart
- lib/src/builder/generation/parsing/member_association.dart
- lib/src/builder/generation/parsing/member_detection.dart
- lib/src/builder/generation/parsing/members.dart
- lib/src/builder/generation/parsing/members/component.dart
- lib/src/builder/generation/parsing/members/factory.dart
- lib/src/builder/generation/parsing/members/props_and_state.dart
- lib/src/builder/generation/parsing/members/props_and_state_mixins.dart
- lib/src/builder/generation/parsing/version.dart
- test/vm_tests/builder/declaration_parsing_test.dart
- Be more strict 
- Move version confidence logic out of member classes and into member detection. This:
- allows for computation before we create member instances, so we don't have to filter them out after the fact.
- unifies the "is this a boilerplate member" logic with the "which version is it" logic, since the two have a lot of overlap and resulted in duplicate code
- Remove `BoilerplateVersion.noGenerate`; instead, use a confidence threshold to determine whether something should be generated. For declarations, this is the mean confidence of all members.
- This allows us to easily determine whether leftover boilerplate members should result in warning/errors (above threshold) or be ignored (below threshold)
- This removes the multiple ways to say something shouldn't be generated (low …
> New boilerplate parser confidence refactor

- lib/src/builder/codegen/accessors_generator.dart
- lib/src/builder/parsing/ast_util.dart
- lib/src/builder/parsing/members.dart
- lib/src/builder/parsing/members/props_and_state.dart
- test/over_react/component_declaration/builder_integration_tests/component2/constant_required_accessor_integration_test.dart
- test/over_react/component_declaration/builder_integration_tests/new_boilerplate/constant_required_accessor_integration_test.dart
- test/vm_tests/builder/declaration_parsing_test.dart
- test/vm_tests/builder/parsing/ast_util_test.dart
- test/vm_tests/builder/parsing/members_test.dart
It's currently an error to declare members within the body of a props/state class, since the generated class only implements it, not extends it.
However, that error should only apply to instance members, and it currently errors for static members.
- Allow static members in concrete props/state classes
- Add regression test
- Allow static members in concrete props/state classes in new, mixin-based boilerplate …
> Allow static members in concrete props/state classes

- .travis.yml
- pubspec.yaml
Allow consumers to use latest analyzer versions.
Widen analyzer range to include 0.39.x
> CPLAT-11102: Widen analyzer range to include 0.39.x

- lib/src/builder/parsing/declarations_from_members.dart
- lib/src/builder/parsing/members_from_ast.dart
- lib/src/component_declaration/component_base.dart
- test/vm_tests/builder/declaration_parsing_test.dart
If a component isn't named correctly in the new boilerplate, it won't get associated with the factory and props class the author intended it to be.
Currently, this mismatched component is ignored and the component gets interpreted as a props mapview, and when the consumer invokes the builder, they get a runtime error.
It would be better if it failed the build.
- When possible, increase `v4_mixinBased` confidence of components to above `neutral`, resulting in mismatched components emitting errors instead of getting silently ignored.
- Add tests
- Update runtime error to mention the mismatched component case, for better debugging of edge case mismatched components (with neutral confidences) that don't trigger a build error
- (Boyscouting) update punctuation in error messages
Emit a build …
> CPLAT-11143 Emit a build error for mismatched components in the new boilerplate

- doc/new_boilerplate_migration.md
We were missing some info in our upgrade guide about how props can no longer be declared  in concrete props classes.
> Note that props can only be declared in mixins

- tools/analyzer_plugin/lib/src/assist/refs/add_create_ref.dart
- tools/analyzer_plugin/lib/src/assist/refs/add_create_ref_assist.dart
- tools/analyzer_plugin/lib/src/diagnostic/arrow_function_prop.dart
- tools/analyzer_plugin/lib/src/diagnostic/bad_key.dart
- tools/analyzer_plugin/lib/src/diagnostic/callback_ref.dart
- tools/analyzer_plugin/lib/src/diagnostic/consumed_props_return_value.dart
- tools/analyzer_plugin/lib/src/diagnostic/dom_prop_types.dart
- tools/analyzer_plugin/lib/src/diagnostic/duplicate_prop_cascade.dart
- tools/analyzer_plugin/lib/src/diagnostic/forward_only_dom_props_to_dom_builders.dart
- tools/analyzer_plugin/lib/src/diagnostic/iterator_key.dart
- tools/analyzer_plugin/lib/src/diagnostic/missing_required_prop.dart
- tools/analyzer_plugin/lib/src/diagnostic/render_return_value.dart
- tools/analyzer_plugin/lib/src/diagnostic/single_child_key.dart
- tools/analyzer_plugin/lib/src/diagnostic/string_ref.dart
- tools/analyzer_plugin/lib/src/diagnostic/style_missing_unit.dart
- tools/analyzer_plugin/lib/src/fluent_interface_util/cascade_read.dart
- tools/analyzer_plugin/lib/src/util/ast_util.dart
- tools/analyzer_plugin/pubspec.yaml
- tools/analyzer_plugin/test/test_util.dart
- tools/analyzer_plugin/test/unit/fluent_interface_util/cascade_read_test.dart
- tools/analyzer_plugin/test/unit/util/ast_util_test.dart
Fixes #516 
Some utilities needed some cleanup and hardening:
- The methods `forEachCascaded(Prop|Method)(Async)?` had some issues:
- Usability: 
- it wasn't possible to short-circuit iteration
- it wasn't possible to use Iterable methods like `.map`, `.any`, etc.
- Suceptibility to bugs: 
- if you used the non-async version by accident, you wouldn't get any analysis hints letting you know you had unawaited async calls inside the callback
- We had several places in the code with duplicated/incomplete logic around getting the possible return expressions from a function body
- We don't have unit tests set up for any code in the repo
- Replace `forEachCascadedProp`/etc. with Iterable-based versions and update usages
- ___Reviewing note:___ make sure all `return;` statements were correctly …
> Utility hardening/cleanup, unit test setup

- tools/analyzer_plugin/lib/src/diagnostic/pseudo_static_lifecycle.dart
- tools/analyzer_plugin/playground/web/pseudo_static_lifecycle.dart
Accessing `super.defaultProps` within the `defaultProps` getter of a component was triggering the `PseudoStaticLifecycleDiagnostic` to display an error, but it should not.
This PR fixes that, and updates the test case in the playground to account for this.
> Account for super getter access in PseudoStaticLifecycleDiagnostic

- tools/analyzer_plugin/lib/src/assist/refs/add_create_ref.dart
- tools/analyzer_plugin/playground/web/refs.dart
Declaring a callback ref with parenthesized arrow function messed up the quick fix in a way that the plugin stopped suggesting the quick fix - even on non-arrow function callback refs.
This PR fixes that, and updates the test case in the playground to account for this.
> Fix createRef quick fix for arrow functions

- tools/analyzer_plugin/lib/src/diagnostic/incorrect_doc_comment_location.dart
- tools/analyzer_plugin/playground/web/doc_comment_location.dart
Props mixin map views look a lot like a `BoilerplateFactory`, but they are different. Doc comments found on their analogous props mixin should not be linted as being in the wrong place.
This PR fixes that, and updates the test case in the playground to account for this.
> Do not lint comments on declarations in a file with a MapView

- tools/analyzer_plugin/lib/src/plugin.dart
AnalysisDriver doesn't fully resolve files that are added via `addFile`; they need to be either explicitly requested via `getResult`/etc, or added to `priorityFiles`.
Since by default, all files just get added via `addFile`, we weren't getting resolved units for those files, so our Diagnostics weren't getting run.
This PR adds logic to update `priorityFiles` on the driver to include:
- Any files prioritized by the analysis server via `handleAnalysisSetPriorityFiles`
- All other files the driver has been told to analyze via addFile (in `ServerPlugin.handleAnalysisSetContextRoots`)
As a result, [processDiagnosticsForResult] will get called with resolved units, and thus __all of our diagnostics
will get run on all files in the repo__ instead of only the currently open/edited ones!
> Enable diagnostics to run on all files in project instead of just open ones

- tools/analyzer_plugin/analysis_options.yaml
- tools/analyzer_plugin/lib/src/async_plugin_apis/diagnostic.dart
- tools/analyzer_plugin/lib/src/diagnostic/arrow_function_prop.dart
- tools/analyzer_plugin/lib/src/diagnostic/boilerplate_validator.dart
- tools/analyzer_plugin/lib/src/diagnostic/bool_prop_name_readability.dart
- tools/analyzer_plugin/lib/src/diagnostic/dom_prop_types_gen.dart
- tools/analyzer_plugin/lib/src/diagnostic/invalid_child.dart
- tools/analyzer_plugin/lib/src/diagnostic/iterator_key.dart
- tools/analyzer_plugin/lib/src/diagnostic/missing_cascade_parens.dart
- tools/analyzer_plugin/lib/src/diagnostic/proptypes_return_value.dart
- tools/analyzer_plugin/lib/src/diagnostic/render_return_value.dart
- tools/analyzer_plugin/lib/src/diagnostic/single_child_key.dart
- tools/analyzer_plugin/lib/src/diagnostic/style_missing_unit.dart
- tools/analyzer_plugin/lib/src/diagnostic/variadic_children.dart
- tools/analyzer_plugin/lib/src/diagnostic_contributor.dart
- tools/analyzer_plugin/lib/src/fluent_interface_util/cascade_read.dart
- tools/analyzer_plugin/lib/src/plugin.dart
- tools/analyzer_plugin/lib/src/util/ast_util.dart
- tools/analyzer_plugin/lib/src/util/react_types.dart
- tools/analyzer_plugin/playground/web/children.dart
- tools/analyzer_plugin/test/unit/fluent_interface_util/cascade_read_test.dart
- tools/analyzer_plugin/test/unit/util/ast_util_test.dart
- tools/analyzer_plugin/tool/init_local_dev.dart
Implicit casts and implicit dynamic can obscure programming issues that can result in runtime errors.
In enabling these, several bad casts that previously went undetected were surfaced and able to be fixed.
Enabling these wasn't too bad in this repo, either, since there's so much good typing, generics, and type-checking in place already.
- Disable implicit-casts and fix issues
- Disable implicit-dynamic and fix issues
- Fix miscellaneous warnings/hints
- Verify in playground/web/iterator_key.dart that missing keys are correctly linted for `.map` calls as well as `.map()` calls with `.toList()` chained on the end
- Verify in playground/web/invalid_child.dart that lists of unsupported types are linted while lists of supported types are not
> Disable implicit casts and implicit dynamic, fix lints

- tools/analyzer_plugin/lib/src/plugin.dart
+ In order to use this, we would have to bump the lower bound of the Dart SDK to 2.8.x - which we aren’t ready to do just yet as a result of https://github.com/dart-lang/build/issues/2688
Partially reverts #534
> Revert use of runZoneGuarded for now

- tools/analyzer_plugin/lib/src/diagnostic/invalid_child.dart
Fixes #539
The existing type-check for whether a child was num was backwards, and thus only worked with implicit casts are enabled.
The code, 
```dart
typeSystem.isAssignableTo(typeProvider.numType, type)
```
translates to: "could a value of type `num` be assigned to `type`"?
For the case of `int`, "could a value of type `num` be assigned to `int`", the answer is:
- with implicit casts enabled: true
- with implicit casts disabled: false (because you can't assign `num` to `int` without casting it)
Fix ordering of arguments an use more explicit `isSubTypeOf` check
> Fix num type check that only works when implicit casts are enabled

- tools/analyzer_plugin/lib/src/diagnostic/arrow_function_prop.dart
- tools/analyzer_plugin/playground/web/misc_fixes.dart
1. The arrow functions in prop cascades lint is very noisy - especially since most consumers just move them to be the last setter in the cascade to avoid the other core dart errors caused by placing it in the middle of the cascade.
1. Upgrade the lint to an error
1. Only lint when the unwrapped function expression is in the middle of a cascade with more than one setter.
Closes #541
> Increase severity of / narrow scope of arrow function in cascade lint

- tools/analyzer_plugin/lib/src/diagnostic/proptypes_instance_members.dart
- tools/analyzer_plugin/lib/src/diagnostic/pseudo_static_lifecycle.dart
- tools/analyzer_plugin/playground/web/proptypes.dart
#535 added a lint for when users reference instance members within `propTypes`, but it doesn't prevent lints on the "whitelisted" instance members that the similar `PseudoStaticLifecycleDiagnostic` uses - and it should.
1. Update logic to not lint on "whitelisted" instance members within `propTypes`, and not to lint on calls to `super.propTypes`.
1. Update test case in the playground
> Do not lint whitelisted instance members within propTypes

- tools/analyzer_plugin/lib/src/diagnostic/boilerplate_validator.dart
- tools/analyzer_plugin/lib/src/diagnostic/bool_prop_name_readability.dart
- tools/analyzer_plugin/playground/web/boilerplate_validator_false_positives.dart
1. The lints that appear when a generated `.over_react.g.dart` `PartDirective` is missing - are appearing when they should not.  This is happening because `members` are really just things that *might* get generated.
1. Bail out before producing the lints if the version confidence of the builder is not `likely` or `certain`.
Fixes #528
> Fix boilerplate generated part directive lint false positives

- tools/analyzer_plugin/lib/src/diagnostic/iterator_key.dart
- tools/analyzer_plugin/lib/src/diagnostic/variadic_children.dart
1. The variadic children diagnostic is misclassified as a warning
1. The quick fix for converting list literals into variadic children did not remove the `key` prop from component children, but it should
1. List literal / mapped iterable children without keys did not have quick fixes
1. Downgrade the variadic children diagnostic to info
1. Remove prop keys when converting list literal children to variadic children
1. Added quick fixes for iterable children without keys:
1. _Within list literals:_ Unwrap from list literal _(only if found within the invocation of a parent component usage)_
1. _Within mapped iterable:_ Add a key prop
Closes #543
> Misc. iterable children improvements

- tools/analyzer_plugin/lib/src/diagnostic/dom_prop_types.dart
- tools/analyzer_plugin/lib/src/diagnostic/duplicate_prop_cascade.dart
- tools/analyzer_plugin/lib/src/fluent_interface_util/cascade_read.dart
- tools/analyzer_plugin/playground/web/dom_prop_types.dart
- tools/analyzer_plugin/playground/web/duplicate_prop_cascade.dart
In the dom prop validator lint, and the dupe prop detection logic - the use of things like
```
..aria.<<some AriaProps field name>>
..dom.<<some DomProps field name>>
``` 
make them not work as expected.
1. Add a new `targetName` getter to `PropAssignment` that returns the `propertyName` of `leftHandSide.target` - which in the cases shown above, will have a `name` of `'aria'` and `'dom'`, respectively.
1. Update the logic in the two aforementioned lints to ensure that the name of the target is factored in.
1. Add test cases for both in the playground.
Fixes #540
> Add better handling for dom and aria prop "targets"

- tools/analyzer_plugin/lib/src/diagnostic/duplicate_prop_cascade.dart
- tools/analyzer_plugin/playground/web/duplicate_prop_cascade.dart
1. #537 made it so that the last of 1 or more duplicate props didn't show as a lint.
2. Fixing duplicates had to be done on individual props, and with the changes from #537 reverted, the last of the dupes could be removed - which would change the runtime behavior of the component.
1. Revert #537 so that all dupes are linted.
1. Update the fix so that all dupes except the last one is removed - preserving the runtime behavior of the component.
Fixes #547
> Update dupe prop fix to remove all dupes except the last one

- tools/analyzer_plugin/lib/src/diagnostic/link_target_without_rel.dart
- tools/analyzer_plugin/lib/src/diagnostic/style_missing_unit.dart
- tools/analyzer_plugin/lib/src/util/ast_util.dart
- tools/analyzer_plugin/playground/web/link_target_without_rel.dart
- tools/analyzer_plugin/playground/web/style_missing_unit.dart
1. The `StyleMissingUnitDiagnostic` currently does not lint when a unitless string value is stored within a `const` that is referenced in the style map, but it should.
1. Update the diagnostic logic to detect constant values and lint _(without offering a quick fix)_ when appropriate using the logic from `LinkTargetUsageWithoutRelDiagnostic` as inspiration.
2. Split out the new and improved logic _(that now detects local constants in addition to instance fields)_ as a shared utility, and use it in both places.
3. Add / update playground test cases to exercise all new / improved logic.
Closes #562
> Lint unitless string const values in style maps

- tools/analyzer_plugin/lib/src/diagnostic/duplicate_prop_cascade.dart
- tools/analyzer_plugin/lib/src/diagnostic/variadic_children.dart
- tools/analyzer_plugin/lib/src/diagnostic/variadic_children_with_keys.dart
- tools/analyzer_plugin/lib/src/fluent_interface_util/cascade_edits.dart
- tools/analyzer_plugin/lib/src/fluent_interface_util/cascade_read.dart
- `convertUsageListLiteralToVariadicChildren` was iterating through children recursively, and removing keys on non-children descendants
- I noticed when testing it out that it was pretty annoying that the  parentheses were left in place after the fixes were applied, so I spiked out a solution to #545 and ended up tacking it on since it was so straightforward. 
We previously considered this post-MVP, but I think it does a lot to improve the UX of our plugin, so it seemed important enough to include.
- Only remove keys from children
- Add removeProp utility that removes parens when the last cascade is removed (fixes #545)
- Update all other prop removals to use this
> Fix unintended removal of keys in granchildren, add removeProp util

- lib/src/builder/builder.dart
- lib/src/builder/util.dart
- tools/analyzer_plugin/lib/src/diagnostic/boilerplate_validator.dart
- tools/analyzer_plugin/playground/web/invalid_generated_part_filename_parent.dart
- tools/analyzer_plugin/playground/web/invalid_generated_part_filename_part.dart
- tools/analyzer_plugin/playground/web/invalid_generated_part_filename_standalone.dart
Fixes #522 
The boiler plate validation logic doesn't currently account or the case where the component declarations are in a `part of` file.
* When analyzing a file which is a self-contained lib, run boilerplate validation and part directive validation.
* When the file is a `part of`, just run the boilerplate validation, but not any part directive validation.
* When we are in a parent lib file, examine the contents of all files in a lib and validate the part directive if any files in the lib contain over_react declarations. …
> Validate part directive for libs with parts

- tools/analyzer_plugin/lib/src/assist/toggle_stateful.dart
- tools/analyzer_plugin/playground/web/foo.dart
- tools/analyzer_plugin/test/integration/assists/boilerplate_assist_utils.dart
- tools/analyzer_plugin/test/integration/assists/toggle_statefulness_test.dart
Added tests for the toggle stateful analyzer plugin assist. This is a new PR for the changes first introduced in #580. 
- Add tests for assist
- Add some utils in a mixin for testing component boilerplate assist
> [Analyzer Plugin] Add toggle stateful tests

- lib/src/over_react_redux/over_react_flux.dart
- lib/src/over_react_redux/over_react_redux.dart
- lib/src/util/equality.dart
> Discovered while testing #499
[Tearoffs aren't guaranteed to be identical](https://github.com/dart-lang/sdk/issues/31665#issuecomment-352678783), and we don't want the use of them to trigger unnecessary rerenders in connect-ed components
Use `propsOrStateMapsEqual` instead of default JS equality
> Use propsOrStateMapsEqual in connect so that tearoffs don't cause unnecessary rerenders

- lib/src/component_declaration/component_base.dart
- pubspec.yaml
Assert message change to reflect work done in https://github.com/cleandart/react-dart/pull/261
- Assert message change
- Update assert message for null component factory
> CPLAT-11669 Update assert to reflect surfacing of registerComponent errors

- lib/over_react.dart
- lib/src/component_declaration/component_type_checking.dart
- lib/src/component_declaration/function_component.dart
- lib/src/util/memo.dart
- lib/src/util/react_wrappers.dart
- pubspec.yaml
- test/over_react/component/memo_test.dart
- test/over_react/component/memo_test.over_react.g.dart
- test/over_react_component_test.dart
We'd like a typed `memo` util to wrap the react-dart memo function to memoize function components.
- Add `memo` with support for over_react typing for function components
- Loosen types in signature of `registerComponentTypeAlias` so function components can be registered accordingly
- Add `enforceFunctionComponent` util
- Add unit tests for `memo`
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual-tes …
> CPLAT-9347 Add memo for function components

- lib/src/util/memo.dart
This fixes a couple of typos that were missed in #613
> Remove namespace from example import

- lib/src/builder/README.md
The builder/README.md file wasn't updated when we originally implemented the new parsing/codegen to support the new mixin-based boilerplate.
- Update the document to reflect the new builder logic
- Revamp that document entirely
- Go through parsing/codegen for  every kind of declaration in detail
- Update the document to reflect the new builder logic
- Update generated code snippets
- Update outdated boilerplate in snippets …
> CPLAT-9778: Update builder readme to reflect new codegen

- app/over_react_redux/todo_client/lib/src/components/shared/list_item_component_mixin.dart
- app/over_react_redux/todo_client/lib/src/components/shared/list_item_expansion_panel_summary.dart
- app/over_react_redux/todo_client/lib/src/components/shared/material_ui.dart
- app/over_react_redux/todo_client/lib/src/components/todo_list_item.dart
- app/over_react_redux/todo_client/lib/src/components/user_list_item.dart
- app/over_react_redux/todo_client/test/unit/browser/components/material_ui_test.dart
Noticed lots of deprecation warnings around `ExpansionPanel` when running the todo example.
- Replaced deprecated `ExpansionPanel` with the new `Accordion` component in ToDo Demo
- Replaced MaterialUi's deprecated `ExpansionPanel` usage with the new `Accordion` component in ToDo Demo
> Boyscoutin: Replace deprecated ExpansionPanel with new Accordion from MaterialUi

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
The latest release of over_react includes:
__Bug Fixes__
- #623 Include deprecation annotations on legacy props mixins
__Other Changes__
- #487 Readme Improvements
- #619 Redux example app: Replace deprecated ExpansionPanel with new Accordion from MaterialUi
> RM-81159 RM-81158 Release over_react 3.8.1

- app/over_react_redux/todo_client/lib/src/components/user_list.dart
- app/over_react_redux/todo_client/pubspec.yaml
- doc/over_react_redux_documentation.md
- lib/src/over_react_redux/devtools/middleware.dart
- lib/src/over_react_redux/over_react_redux.dart
- test/over_react_redux/connect_test.dart
React Redux allows you to return a function from mapStateToProps, allowing you to create a closure specific to that component instance, allowing you to set up a private copy of a memoized selector so that components don't invalidate each other's cache.
We should support this functionality so that consumers can follow the official React Redux tutorials for preventing unnecessary rerenders
- Add `makeMapStateToProps` & `makeMapStateToPropsWithOwnProps`
- Add `makeMapDispatchToProps` & `makeMapDispatchToPropsWithOwnProps`
- Add tests for all added `make` factory functions
- Update connect doc comments with `make` arguments
- Update and Format over_react_redux_documentation.md with `make` arguments
- Add `makeMapStateToProps` & `makeMapStateToPropsWithOwnProps`
- Add `makeMapDispatchToProps` …
> CPLAT-11374: Add makeMapStateToProps/WithOwnProps and makeMapDispatchToProps/WithOwnProps

- example/hooks/use_imperative_handle_example.dart
- example/hooks/use_imperative_handle_example.over_react.g.dart
- lib/src/component/hooks.dart
- lib/src/component/ref_util.dart
- lib/src/component_declaration/component_type_checking.dart
- lib/src/util/memo.dart
- pubspec.yaml
- test/over_react/component/ref_util_test.dart
https://github.com/cleandart/react-dart/pull/275 fixes forwardRef/memo bugs and exposes new versions of the APIs, and we need to consume them in over_react.
- Update `uiForwardRef` to use `forwardRef2` under the hood
- Update `memo` to use `memo2` under the hood
Fix `uiForwardRef` and `memo` being passed JSified versions of props.
- Smoke test examples
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manua …
> CPLAT-11977 Consume/update typing for forwardRef2/memo2 functions

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
The latest release of over_react includes:
- #620 Consume/update typing for forwardRef2/memo2 functions
- #625 Address analyzer lints / hints
> RM-83168 Release over_react 3.9.0

- lib/src/over_react_redux/devtools/middleware.dart
While testing with another project it was discovered that instance specific onRecord listeners actually act like `Logger.root.onRecord` when `hierarchicalLoggingEnabled` is `false` (default)
- Add an escape hatch to prevent from logging LogRecords that do not belong to OverReactReduxDevToolsMiddleware.
> Add onRecord escape hatch for OverReactReduxDevToolsMiddleware Logger

- lib/components.dart
- lib/over_react.dart
- lib/src/component/_deprecated/abstract_transition_props.dart
- lib/src/component/_deprecated/abstract_transition_props.over_react.g.dart
- lib/src/component/with_transition.dart
- lib/src/component/with_transition.over_react.g.dart
- test/over_react/component/with_transition_test.dart
- test/over_react/component/with_transition_test.over_react.g.dart
- test/over_react_component_test.dart
Currently, `AbstractTransitionComponent`s can only be programmatically shown/hidden using the `show` / `hide` / `toggle` API methods on the instance.
With React 16 componentry - this is not ideal since calling the methods from a parent component requires the use of a `ref`, and the child component is no longer guaranteed to have been mounted when the parent component is. This makes it very difficult to hide/show things within data-driven applications without having to work around runtime race conditions.
1. Add the `WithTransition` wrapper component. 
This component is designed to have identical behavior to `AbstractTransitionComponent`, but allows the consumer to control the behavior using the value of `props.isShown`.
2. Add tests.
Add `WithTransition` wrapper component to enable …
> CPLAT-12205 Add WithTransition wrapper component to enable "controlled" transitions using props

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [CPLAT-12205 Add WithTransition wrapper component to enable "controlled" transitions using props](https://github.com/Workiva/over_react/pull/621)
* [Add onRecord escape hatch for OverReactReduxDevToolsMiddleware Logger](https://github.com/Workiva/over_react/pull/628)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/3.9.0...Workiva:release_over_react_3.10.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/3.9.0...3.10.0
> RM-83646 RM-83645 Release over_react 3.10.0

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Boilerplate error improvements](https://github.com/Workiva/over_react/pull/500)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/3.10.0...Workiva:release_over_react_3.10.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/3.10.0...3.10.1
> RM-85340 RM-85339 Release over_react 3.10.1

- app/over_react_redux/todo_client/analysis_options.yaml
- app/over_react_redux/todo_client/pubspec.yaml
- build.yaml
1. When CI fails due to dart2js test failures, it's hard to see the stack of what failed since everything is minified.
2. Our to-do example app doesn't have ignores of ungenerated URIs set up, so it's not a valid representation of what most of our consumers use
1. Disable minification in dart2js builds of tests/examples
2. Pull in workiva_analysis_options to ignore ungenerated URI warnings
- Also remove redundant pedantic lints …
> Misc cleanup

- test/over_react_redux/connect_test.dart
Working on CPLAT-12194, I noticed there were just a few small lints that could be cleaned up just to have analysis clean.
> Clean up lints

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Misc cleanup](https://github.com/Workiva/over_react/pull/630)
* [Check in changed generated files](https://github.com/Workiva/over_react/pull/632)
* [CPLAT-12194 Enable functional components to use consumed props](https://github.com/Workiva/over_react/pull/633)
* [bump react to 5.6.1](https://github.com/Workiva/over_react/pull/635)
* [Clean up lints](https://github.com/Workiva/over_react/pull/638)
Requested by: @joebingham-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/3.10.1...Workiva:release_over_react_3.11.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/3.10.1...3.11.0
The logs for the request that created this PR can be found …
> RM-85606 RM-85605 Release over_react 3.11.0

- lib/src/util/memo.dart
- test/over_react/component/memo_test.dart
- test/over_react/component/memo_test.over_react.g.dart
[Tearoffs aren't guaranteed to be identical](https://github.com/dart-lang/sdk/issues/31665#issuecomment-352678783), and we don't want the use of them to trigger unnecessary rerenders in `memo`ized function components.
[Closely related to how we handled this same problem for `connect`ed components](https://github.com/Workiva/over_react/pull/608)
1. Use `propsOrStateMapsEqual` for `areEqual` instead of default JS equality when the consumer does not specify their own custom handler for the `areEqual` parameter.
1. Note that we're using our own utility to do the default shallow comparison in the doc comment for `memo`.
1. Add a regression test.
> Use propsOrStateMapsEqual in memo so that tearoffs don't cause unnecessary rerenders

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Use propsOrStateMapsEqual in memo so that tearoffs don't cause unnecessary rerenders](https://github.com/Workiva/over_react/pull/643)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/3.12.0...Workiva:release_over_react_3.12.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/3.12.0...3.12.1
> RM-88572 RM-88571 Release over_react 3.12.1

- tools/analyzer_plugin/lib/src/diagnostic/missing_cascade_parens.dart
- The contains checks weren't working properly since the error code objects weren't the same type, and would always be false
- CompileTimeErrorCode is part of analyzer.dart, which will be removed in a future version, and this prepares for that
- This API doesn't seem to be treated as stable, either, since we're getting weird failures in Dart 2.7 CI
Remove usages of CompileTimeErrorCode and hard code the errors instead
- Analyzer plugin CI passes in Dart 2.7
- This diagnostic works as intended (or at least doesn't cause bad behavior) in the analyzer playground
While we perform many automated checks before auto-merging, some manual checks are …
> Fix/remove usages of CompileTimeErrorCode

- lib/src/component/ref_util.dart
- lib/src/component_declaration/annotations.dart
- lib/src/component_declaration/component_base.dart
- lib/src/component_declaration/component_base_2.dart
- lib/src/component_declaration/component_type_checking.dart
- lib/src/over_react_redux/over_react_redux.dart
- lib/src/util/memo.dart
- test/over_react/component_declaration/component_base_test.dart
- test/over_react/component_declaration/component_type_checking_test.dart
- test/over_react/component_declaration/function_type_checking_test/components.dart
- test/over_react/component_declaration/function_type_checking_test/components.over_react.g.dart
The `@Component2` annotation can't be used with function components, preventing consumers from specifying arguments like `isWrapper` and `subtypeOf`.
- Add `setTypeMeta` extension method to `UiFactory`, providing parity with the `@Component2` annotation for function components
- Add tests
- Tweak arguments to private `setComponentTypeMeta` and `ComponentTypeMeta` to use raw component types in case the `ReactComponentFactoryProxy` isn't available
- Increase test coverage for these utilities
Examples of equivalent configuration for class-based vs function components:
```dart
// Class components:
@Component2(isWrapper: true)
class FooComponent extends UiComponent2<FooProps> { ... }
@Component2(subtypeOf: FooComponent)
class BarComponent ... {...}
// Function components:
UiFactory<FooProps> …
```
> CPLAT-12196: @Component2 annotation parity for function components

- .github/workflows/dart_ci.yml
- pubspec.yaml
- test/over_react_redux/hooks/use_selector_test.dart
The Dart stable build was failing due to:
- (Mainly) not being able to resolve to build_web_compilers, `^1.12.0`, which contains fixes for null-safety being opted into when it shouldn't
- Differences in some generated files compared to those generated in 2.7.2
- Update version bounds (credit to @aaronlademann-wf for almost all of these changes)
- Increase analyzer upper bound so that build_web_compilers `1.12.0` can be resolved to in Dart 2.12+, and keep lower bound low enough so that we can still resolve in Dart 2.7
- Widen other bounds as needed
- Update build to ignore changes in generated files
Update dependencies to allow resolution of build_web_compilers `^1.12.0` in Dart 2.12+, which contains fixes for null-safety being opted into when it shouldn't.
_[See …
> Enable resolution of build_web_compilers 1.12.0, fix Dart stable build

- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Remove deprecated authors field from pubspec.yaml](https://github.com/Workiva/over_react/pull/685)
* [DE-657: Delete docs.yml file created for Dev Portal.](https://github.com/Workiva/over_react/pull/686)
* [Enable resolution of build_web_compilers 2.12.0, fix Dart stable build](https://github.com/Workiva/over_react/pull/691)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.1.0...Workiva:release_over_react_4.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.1.0...4.1.1
This pull …
> RM-94745 RM-94744 Release over_react 4.1.1

- .github/workflows/dart_ci.yml
- app/over_react_redux/todo_client/pubspec.yaml
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
In order for projects to be compatible with Dart 2.13, there are dependencies that need to have their ranges widened. 
For a list of dependencies expected to be changed, see the dependencies section of the Dart 2.12+ [wiki page](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=189370832).
Another necessary change is the removal of `build_vm_compilers`. If this is the case, additional clean up may need to be done, such as removing the associated config from `build.yaml` or updating how tests are run. A member of Client Platform will be following up with PRs that have CI failures to resolve any issues or perform necessary clean up.
For any questions or concerns, don't hesitate to reach us in the #support-client-plat Slack channel!
- Update specific dependencies to be compatible …
> Widen Dependency Ranges Blocking Dart 2.13

- lib/src/builder/builder.dart
Libraries with language version comments must have the same version comments in all of their part files.
As a result, it's currently impossible to add a language version comment to a file with a generated over_react part, since the generated part never includes a language version comment.
- Copy any language version comment from the source file to the generated over_react part file.
- Add a language version comment to an example file with a generated over_react part
- Run a build (reminder you can run `pub run build_runner --build-filter='**.g.dart'` to build only Dart files and not JS
- Verify that the language version comment is present in the …
> Copy language version comments to generated part files

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Copy language version comments to generated part files](https://github.com/Workiva/over_react/pull/689)
* [Widen Dependency Ranges Blocking Dart 2.13](https://github.com/Workiva/over_react/pull/695)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.1.1...Workiva:release_over_react_4.1.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.1.1...4.1.2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?pull …
> RM-108356 RM-108355 Release over_react 4.1.2

- lib/src/component/prop_mixins.dart
- lib/src/component/prop_mixins.over_react.g.dart
- test/over_react/component_declaration/component_base_test.dart
- test/test_util/test_util.dart
Sometimes, Dart code can read props that originate from JS code (e.g., a JS component rendering/cloning a Dart component), and in cases where the JS prop value doesn't match the typings on the OverReact prop getter, you get a runtime type error.
Two common cases of this are the `style` and `children` props.
`style` props set by JS code are JS objects, which can't be casted to Dart `Map`s in the `DomPropsMixin.style` and `UbiquitousDomPropsMixin.style` getters.
`children` props are always `List`s for Dart components rendered by Dart code, but can be nullish or a singular value when rendered by JS components, and can cause cast errors in the typed `children` prop getter.
- Normalize the value of the `children` prop getter (`ReactPropsMixin.children`, mixed into `UiProps`) to always be a …
> CPLAT-15063 Conditionally unconvert style and children props

- CHANGELOG.md
- lib/src/component_declaration/component_base.dart
- pubspec.yaml
- test/over_react/component/element_type_test.dart
- test/over_react/component/element_type_test.over_react.g.dart
- test/over_react_component_test.dart
- tools/analyzer_plugin/pubspec.yaml
__The latest version of over_react contains:__
* Add `UiFactory.elementType` convenience getter
* Fix lower bound of the `meta` dependency that was mistakenly set too high in #695
> RM-111110 Release over_react 4.2.0

- lib/src/component_declaration/flux_component.dart
- lib/src/util/component_debug_name.dart
- test/over_react/component_declaration/flux_component_test/component2/flux_component_test.dart
- test/over_react/util/component_debug_name_test.dart
- test/over_react/util/component_debug_name_test.over_react.g.dart
- test/over_react_util_test.dart
We have some warning logs in place for before FluxUiComponent(2) components attempt to subscribe to disposed stores.
These logs weren't very helpful, though, since they didn't contain a stack trace, component name, or store name.
- Add more information to logs
- Add a utility to get a Dart component name from its Dart instance
- Add basic unit tests for this logging …
> Improve FluxUiComponent disposed store logging

- CHANGELOG.md
- lib/src/component_declaration/flux_component.dart
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
Reinstates [a recently-removed null-coalescing operator](https://github.com/Workiva/over_react/commit/dcbbea46dd0230c7915624388b3233ea1ccad8cf#diff-47691740357c7cfe159ca805f455f4b9e27d5df1ed49fc5c4bca5a0c21ce95a5L241) that consumers were depending on due to the use of mocked stores.
> RM-114209 RM-114208 Release over_react 4.2.2

- .github/workflows/dart_ci.yml
Getting dependencies sorted to the point where we can have a passing Dart 2.14 (`stable`) build is proving to be difficult, and we still want to verify that over_react works on Dart 2.13.
- Add Dart 2.13 to the build matrix
- Verify 2.7 and 2.13 builds are passing (minus analyzer plugin builds, which will be resolved in https://github.com/Workiva/over_react/pull/696) …
> Add 2.13.4 to matrix

- .github/workflows/dart_ci.yml
- Dockerfile
- app/over_react_redux/todo_client/pubspec.yaml
- pubspec.yaml
- tools/analyzer_plugin/playground/pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
This updates the minimum Dart version that can be used to at least 2.11.0. Why 2.11.0 and not 2.13.4? Because setting it to 2.12.0 or higher opts the project into null safety (https://dart.dev/null-safety) which our code has not been migrated to yet. 
Once a project has been migrated to null safety it is ok to update the  minimum to 2.12.0 or even 2.13.4 since everyone at Workiva should be  using 2.13.4 now.
If CI passes please review and merge. Most Dart CI has already been updated to run under 2.13.4 already so updating the minimum here doesn't change any code, or CI circumstances.
If CI fails, it's likely because an image in the Dockerfile or skynet.yaml is still running an older version of Dart. It should be updated to one with Dart 2.13. A list of existing 2.13 images lives here …
> Raise the Dart SDK minimum to at least 2.11.0

- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Add 2.13.4 to matrix](https://github.com/Workiva/over_react/pull/708)
* [Raise the Dart SDK minimum to at least 2.11.0](https://github.com/Workiva/over_react/pull/709)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.2.2...Workiva:release_over_react_4.2.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.2.2...4.2.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?pull_number=711&repo_name=Workiva%2 …
> RM-114239 RM-114238 Release over_react 4.2.3

- pubspec.yaml
Consume [react-dart 6.1.3](https://github.com/Workiva/react-dart/releases/tag/6.1.3)
* [Bump elliptic from 6.5.3 to 6.5.4](https://github.com/Workiva/react-dart/pull/308)
* [Update README.md](https://github.com/Workiva/react-dart/pull/309)
* [Bump ssri from 6.0.1 to 6.0.2](https://github.com/Workiva/react-dart/pull/311)
* [Bump lodash from 4.17.20 to 4.17.21](https://github.com/Workiva/react-dart/pull/312)
* [Bump browserslist from 4.16.1 to 4.16.6](https://github.com/Workiva/react-dart/pull/313)
* [Upgrade to Dart 2.13](https://github.com/Workiva/react-dart/pull/315)
* [Bump path-parse from 1.0.6 to 1.0.7](https://github.com/Workiva/react-dart/pull/318)
* [Raise the Dart SDK minimum to at least …
> Consume react-dart 6.1.3

- pubspec.yaml
Consume [react-dart 6.1.4](https://github.com/Workiva/react-dart/releases/tag/6.1.4)
* [Fix stable ci build](https://github.com/Workiva/react-dart/pull/327)
* [Work around $identityHash being added to JS objects passed into jsifyAndAllowInterop](https://github.com/Workiva/react-dart/pull/328)
* [RM-121022 Release react-dart 6.1.4](https://github.com/Workiva/react-dart/pull/329)
Requested by: @rmconsole4-wk
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/4948379952742400/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4948379952742400/?pull_number=715&repo_name=Workiva%2Fover_react)
> Consume react-dart 6.1.4

- .github/workflows/dart_ci.yml
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
Summary
---
Client Platform is updating dependencies! Read more details at
This batch is to find and open PRs to upgrade dependency_validator to v2.
Additional manual work that might be needed (CP will do):
[ ] Run dependency_validator to repos that aren't running it,
but do have the dependency. 
[ ] Fix CI due to removing an ignore that was actually needed.
For more info, reach out to `#support-client-plat` on Slack.
[_Created by Sourcegraph batch change `Workiva/update_dep_validator`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/update_dep_validator)
> Upgrade dependency_validator

- .github/workflows/dart_ci.yml
CI fails on Dart >=2.14 since our current analyzer version range doesn't support the `<<<` operator, causing build failures.
These failures are noisy and make it easier to mistake legitimate failures for expected ones.
Disable CI on Dart >=2.14 until we're able to get the build passing on it (i.e., once we're on analyzer 1.x).
- __All CI runs pass__
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual-t …
> Disable CI on Dart >=2.14 for now

- app/over_react_redux/todo_client/pubspec.yaml
Summary
---
Client Platform is updating dependencies! Read more details at
This batch is to find and open PRs to upgrade test_html_builder to v2.
For more info, reach out to `#support-client-plat` on Slack.
[_Created by Sourcegraph batch change `Workiva/update_test_html_builder_to_v2`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/update_test_html_builder_to_v2)
> Update test_html_builder to v2

- pubspec.yaml
- test/over_react/component/_deprecated/abstract_transition_test.dart
- test/over_react/component/abstract_transition_test.dart
- test/over_react/component_declaration/redux_component_test.dart
- test/over_react/util/css_value_util_test.dart
Summary
---
Client Platform is updating dependencies! Read more details at
This batch is to remove uses of dart2_constant which is a remnant from the dart 2 upgrade.
For more info, reach out to `#support-client-plat` on Slack.
[_Created by Sourcegraph batch change `Workiva/remove_dart2_constant`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/remove_dart2_constant)
> Remove dart2_constant

- analysis_options.yaml
- lib/over_react_flux.dart
- lib/src/over_react_redux/over_react_flux.dart
- test/over_react_redux/connect_flux_adapter_store_test.dart
- test/over_react_redux_test.dart
It's inconvenient to store references to `ConnectFluxAdapterStore`s to call `teardown` on them later, especially when using the extension method `asConnectFluxStore` after passing through the Flux store through several layers of constructors/functions.
Automatically call `teardown` on the created store when the backing Flux store disposes, since the Redux store won't be used to dispatch any events anyways after the Flux store has been disposed.
- Consumer tests pass
[contributing-review-types]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md …
> CPLAT-16343 Auto-tear-down ConnectFluxAdapterStores when backing Flux stores dispose

- CHANGELOG.md
- app/over_react_redux/todo_client/pubspec.yaml
- pubspec.yaml
- tools/analyzer_plugin/playground/pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
Summary
---
Client Platform is updating dependencies! More details at
This batch raises the max versions allowed for the following
dependencies:
- args <3.0.0
- build <3.0.0
- build_config <2.0.0
- build_runner <3.0.0
- checked_yaml <3.0.0
- logging <2.0.0
- pub_semver <3.0.0
- pubspec_parse <2.0.0
- uri <2.0.0
For more info, reach out to `#support-client-plat` on Slack.
[_Created by Sourcegraph batch change `Workiva/raise_max_versions`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/raise_max_versions)
> Raise Max Versions

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Fix wildcard to include branch names with slashes](https://github.com/Workiva/over_react/pull/725)
* [Closes #727](https://github.com/Workiva/over_react/pull/728)
* [CPLAT-16997 Fix selector hooks redrawing when values haven't changed](https://github.com/Workiva/over_react/pull/730)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.2.6...Workiva:release_over_react_4.2.7
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.2.6...4.2.7 …
> RM-127138 RM-127137 Release over_react 4.2.7

- pubspec.yaml
Client Platform is updating dependencies! Read more details at
This PR is the last step in the process to upgrade to built_value_generator
v8. At this point, all packages at Workiva are compatible with built_value
v8 and built_collection v5, so this PR upgrades the generator from v7 to v8
and commits the updated assets from it.
Note that because code generated by built_value_generator v8 uses APIs that
are only available in built_value v8 and built_collection v5, this PR also
raises the minimums of those dependencies accordingly.
For most consumers, static analysis along with existing unit and functional
tests should provide adequate coverage of these changes. We are already
using built_value v8 and built_collection v5 in Wdesk; …
> Upgrade built_value_generator to v8

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Upgrade built_value_generator to v8](https://github.com/Workiva/over_react/pull/729)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.2.7...Workiva:release_over_react_4.2.8
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.2.7...4.2.8
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?pull_number=732&repo_name=Workiva%2Fover_react)
> RM-132104 RM-132103 Release over_react 4.2.8

- lib/src/util/safe_render_manager/safe_render_manager.dart
- lib/src/util/safe_render_manager/safe_render_manager_helper.dart
- lib/src/util/safe_render_manager/safe_render_manager_helper.over_react.g.dart
- test/over_react/util/safe_render_manager/safe_render_manager_test.dart
SafeRenderManager gets retained by the rendered SafeRenderManagerHelper, which in some cases was being retained by React, seemingly because of the following behavior:
_From https://github.com/facebook/react/issues/16087:_
> Props/child trees retained by alternate children. Similarly, children that was just removed can sometimes between retained by the alternate copy of that. That is until that node gets another update on it which clears out the old children. These cases are fairly unusual and fix themselves eventually as the app lives on.
These retentions eventually resolve themselves, so they're not true leaks, but they can show up as leaks in memory leak tests that look for disposed-but-retained objects (via Disposable's LeakFlag mechanism).
There are cases where it's very difficult to …
> SafeRenderManager retention workaround

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [SafeRenderManager retention workaround](https://github.com/Workiva/over_react/pull/733)
Requested by: @lukeanderson-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.2.8...Workiva:release_over_react_4.2.9
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.2.8...4.2.9
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?pull_number=734&repo_name=Workiva%2Fover_react)
> RM-133131 RM-133130 Release over_react 4.2.9

- .github/workflows/dart_ci.yml
- Dockerfile
This Sourcegraph batch replaces deprecated commands from the Dart SDK with the new ones.
All new CLI commands now live under the main `dart` executable. See this issue for the details
https://github.com/dart-lang/sdk/issues/46100
This PR might need to be checked or tweaked for possible errors in the arguments to 
`dart analyze` and `dart format` since they take slightly different arguments than the original.
In most cases for analyze all the arguments can be removed and it can just be `dart analyze`.
Some of the argument changes were difficult to match and replace in an automated way. Since
there are only a few places that might break, it'll be easier to let the batch create the PR
and then manually adjust them.
`-w` should be removed automatically since overwriting files is now the …
> Replace deprecated commands with new dart commands

- lib/src/component/aria_mixin.dart
- lib/src/component/aria_mixin.over_react.g.dart
Update AriaPropsMixin with missing attributes
Added missing Aria attributes
Added missing Aria roles
Updated outdated W3 links
Add new documentation
> CPLAT-17301 Update AriaPropsMixin

- pubspec.yaml
Consume [react-dart 6.1.6](https://github.com/Workiva/react-dart/releases/tag/6.1.6)
* [RM-138703 Release react-dart 6.1.6 (Publish JS bundles to Workiva CDN)](https://github.com/Workiva/react-dart/pull/336)
Requested by: @rm-astro-wf
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/4948379952742400/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4948379952742400/?pull_number=740&repo_name=Workiva%2Fover_react)
> Consume react-dart 6.1.6

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Consume react-dart 6.1.6](https://github.com/Workiva/over_react/pull/740)
* [Add empty skynet plan so release pipelines will stop failing](https://github.com/Workiva/over_react/pull/745)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.3.0...Workiva:release_over_react_4.3.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.3.0...4.3.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?pull_number=74 …
> RM-144719 RM-144718 Release over_react 4.3.1

- tools/analyzer_plugin/lib/src/diagnostic/duplicate_prop_cascade.dart
- tools/analyzer_plugin/playground/web/duplicate_prop_cascade.dart
- tools/analyzer_plugin/test/integration/diagnostics/duplicate_prop_cascade_test.dart
This is a follow-up for feedback on #607.
> [Analyzer Plugin] Fix existing / add more duplicate prop cascade diagnostic tests

- tools/analyzer_plugin/lib/src/async_plugin_apis/diagnostic.dart
- tools/analyzer_plugin/lib/src/diagnostic/arrow_function_prop.dart
- tools/analyzer_plugin/lib/src/diagnostic/bad_key.dart
- tools/analyzer_plugin/lib/src/diagnostic/boilerplate_validator.dart
- tools/analyzer_plugin/lib/src/diagnostic/bool_prop_name_readability.dart
- tools/analyzer_plugin/lib/src/diagnostic/callback_ref.dart
- tools/analyzer_plugin/lib/src/diagnostic/consumed_props_return_value.dart
- tools/analyzer_plugin/lib/src/diagnostic/dom_prop_types.dart
- tools/analyzer_plugin/lib/src/diagnostic/duplicate_prop_cascade.dart
- tools/analyzer_plugin/lib/src/diagnostic/forward_only_dom_props_to_dom_builders.dart
- tools/analyzer_plugin/lib/src/diagnostic/hooks_exhaustive_deps.dart
- tools/analyzer_plugin/lib/src/diagnostic/incorrect_doc_comment_location.dart
- tools/analyzer_plugin/lib/src/diagnostic/invalid_child.dart
- tools/analyzer_plugin/lib/src/diagnostic/iterator_key.dart
- tools/analyzer_plugin/lib/src/diagnostic/link_target_without_rel.dart
- tools/analyzer_plugin/lib/src/diagnostic/missing_cascade_parens.dart
- tools/analyzer_plugin/lib/src/diagnostic/missing_required_prop.dart
- tools/analyzer_plugin/lib/src/diagnostic/non_defaulted_prop.dart
- tools/analyzer_plugin/lib/src/diagnostic/proptypes_return_value.dart
- tools/analyzer_plugin/lib/src/diagnostic/pseudo_static_lifecycle.dart
- tools/analyzer_plugin/lib/src/diagnostic/render_return_value.dart
- tools/analyzer_plugin/lib/src/diagnostic/rules_of_hooks.dart
- tools/analyzer_plugin/lib/src/diagnostic/string_ref.dart
- tools/analyzer_plugin/lib/src/diagnostic/style_value_diagnostic.dart
- tools/analyzer_plugin/lib/src/diagnostic/variadic_children.dart
- tools/analyzer_plugin/lib/src/diagnostic/variadic_children_with_keys.dart
- tools/analyzer_plugin/lib/src/diagnostic_contributor.dart
- tools/analyzer_plugin/test/integration/diagnostics/analysis_options_configuration_test.dart
- tools/analyzer_plugin/test/unit/analysis_options/parse_test.dart
Right now when you disable a diagnostic, we still compute the errors for that diagnostic even though the will eventually get filtered out.
Make it so that when all the diagnostics for a diagnostic contributor have been turned off, skip computing errors for that diagnostic.
> [Analyzer Plugin] Don't compute disabled diagnostics

- tools/analyzer_plugin/lib/src/assist/refs/add_create_ref.dart
- tools/analyzer_plugin/lib/src/assist/refs/add_create_ref_assist.dart
- tools/analyzer_plugin/lib/src/diagnostic/callback_ref.dart
- tools/analyzer_plugin/lib/src/diagnostic/hooks_exhaustive_deps.dart
- tools/analyzer_plugin/lib/src/diagnostic/string_ref.dart
- tools/analyzer_plugin/lib/src/plugin.dart
- tools/analyzer_plugin/lib/src/util/ast_util.dart
- tools/analyzer_plugin/playground/web/refs_fn_components.dart
- tools/analyzer_plugin/test/integration/assists/add_create_ref_test.dart
- tools/analyzer_plugin/test/integration/diagnostics/callback_ref_test.dart
- tools/analyzer_plugin/test/integration/test_bases/diagnostic_test_base.dart
Our "add_ref" assist, and the `CallbackRefDiagnostic` that uses it did not support function components. Now it does, it replaces callback refs with `useRef` instead of `createRef`, and there are tests.
> [Analyzer Plugin] Add function component support + tests for add ref assist / callback ref diagnostic

- tools/analyzer_plugin/lib/src/assist/convert_class_or_function_component.dart
Previously, methods in class components were discarded when converting to a function component.
This meant any render helper methods get removed as part of the assist, and also also lifecycle methods that need to be converted get lost.
Add any methods in the class inside the function component body.
> Include class methods when converting to a function component

- app/over_react_redux/todo_client/pubspec.yaml
Summary
---
Frontend Frameworks is updating more dependencies! More details at
This updates the maximum for the following packages (leaving the minimum unchanged)
pubspec_codemod raise-max build_runner 3.0.0 --recursive
pubspec_codemod raise-max crypto 4.0.0 --recursive
pubspec_codemod raise-max dart_style 3.0.0 --recursive
pubspec_codemod raise-max dependency_validator 4.0.0 --recursive
pubspec_codemod raise-max io 2.0.0 --recursive
pubspec_codemod raise-max mime 2.0.0 --recursive
pubspec_codemod raise-max quiver 4.0.0 --recursive
pubspec_codemod raise-max stream_transform 3.0.0 --recursive
pubspec_codemod raise-max tuple 3.0.0 --recursive
pubspec_codemod raise-max uuid 4.0.0 --recursive
pubspec_codemod raise-max yaml 4.0.0 …
> Raise More Max Versions

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [fw-149 Change skynet to verify that github workflow is successful](https://github.com/Workiva/over_react/pull/765)
* [Update to latest image of github ci verifier](https://github.com/Workiva/over_react/pull/768)
* [FED-178 Add Documentation for `uiJsComponent`](https://github.com/Workiva/over_react/pull/769)
* [FED-193 Show Component Name in ErrorBoundary Stack](https://github.com/Workiva/over_react/pull/770)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.4.1...Workiva:release_over_react_4.4.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.4.1...4.4.2
The logs for the request that created this PR can be found …
> RM-150529 RM-150528 Release over_react 4.4.2

- app/over_react_redux/todo_client/pubspec.yaml
- lib/src/component_declaration/disposable_manager_proxy.dart
- pubspec.yaml
We'd like to be able to upgrade to w_common v2
Replace deprecated w_common calls with their equivalent v2 calls. These calls also exist in v1 so we can go ahead and leave these in for a patch release and raise the w_common max to allow w_common v2.
> Allow wcommon 2

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Update references to the previous team name](https://github.com/Workiva/over_react/pull/773)
* [Make error message when component failed to initialize more helpful](https://github.com/Workiva/over_react/pull/774)
* [Allow wcommon 2](https://github.com/Workiva/over_react/pull/778)
* [Remove duplicate import](https://github.com/Workiva/over_react/pull/779)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.4.2...Workiva:release_over_react_4.4.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.4.2...4.4.3
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/64499523062333 …
> RM-156570 RM-156569 Release over_react 4.4.3

- app/over_react_redux/todo_client/pubspec.yaml
- pubspec.yaml
Summary
---
This update will allow w_common 2x by raising the max to < 3.0.0
It also raises the minimum of a few packages that addressed w_common
v2 breaking changes. In order to be compatible with w_common v2, we
need at least these versions.
dart_dev_workiva 1.5.9
wdesk_sdk 3.7.8
w_router 1.1.15
w_flux 2.10.21
w_module 2.0.30
bigsky_rest_files 1.33.10
In addition, sass compilation was moved out of w_common into a 
w_common_tools package, so if it detects that the repo might need it, 
it might add a dependency on w_common_tools.
Lastly, app/pubspec.lock files may have needed to be updated to get 
those minimum versions of packages
For more info, reach out to …
> w_common v2 rollout - 1 of 2 raise max

- app/over_react_redux/todo_client/pubspec.yaml
- pubspec.yaml
Summary
---
This update will require w_common 2x by raising the min to ^2.0.0
All consumers have already been updated to allow w_common 2 in the
step 1 batch, so this PR should be a no-op.
For more info, reach out to `#support-frontend-architecture` on Slack.
[_Created by Sourcegraph batch change `Workiva/w_common_v2_raise_min`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/w_common_v2_raise_min)
> w_common v2 rollout - 2 of 2 raise min

- test/over_react/util/prop_conversion_test.dart
There's a test in master that just started failing, without any changes: https://github.com/Workiva/over_react/actions/runs/3245189553/jobs/5649287921
```
00:11 +1142 -1: [Chrome] test/over_react_util_test.dart: prop conversion works as expected in advanced cases: Dart component used as `component` prop expecting a custom Dart Map prop [E]             
Expected: [
<<Instance of 'Object'> with `toString() value`: (match 'Expected a value of type 'Map[^']*', but got one of type 'NativeJavaScriptObject'' or match 'type 'UnknownJavaScriptObject' is not a subtype of type 'Map[^']*'')>
]
Actual: [
_TypeError:TypeError: Instance of 'PlainJavaScriptObject': type 'PlainJavaScriptObject' is not a subtype of type 'Map<dynamic, dynamic>'
]
Which: at location [0] is _TypeError:<TypeError: Instance of …
```
> FED-513 Fix PlainJavaScriptObject test failure in master

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-194 Fully implement hooks exhaustive dependencies diagnostic, add tests](https://github.com/Workiva/over_react/pull/788)
* [FED-513 Fix PlainJavaScriptObject test failure in master](https://github.com/Workiva/over_react/pull/791)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.5.0...Workiva:release_over_react_4.6.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.5.0...4.6.0 …
> RM-164256 RM-164255 Release over_react 4.6.0

- pubspec.yaml
Consume [react-dart 6.1.8](https://github.com/Workiva/react-dart/releases/tag/6.1.8)
* [FED-202 Return `jsUndefined` instead of `null` when children prop is empty](https://github.com/Workiva/react-dart/pull/350)
* [RM-156571 Release react-dart 6.1.8](https://github.com/Workiva/react-dart/pull/351)
Requested by: @rmconsole3-wf
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/4948379952742400/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4948379952742400/?repo_name=Workiva%2Fover_react&pull_number=794)
> Consume react-dart 6.1.8

- app/over_react_redux/todo_client/lib/src/store.dart
- doc/over_react_redux_documentation.md
- lib/over_react_redux.dart
- lib/src/over_react_redux/devtools/middleware.dart
As its currently implemented, we have no way to provide options to the initialization of the `overReactReduxDevToolsMiddleware`. This pr adds an additional `overReactReduxDevToolsMiddlewareFactory` which currently only accepts a `name` parameter (more can be added as needed)
This directly proxies the list of available options which the redux-devtools api [provides](https://github.com/reduxjs/redux-devtools/blob/main/extension/docs/API/Arguments.md)
- exposes new `overReactReduxDevToolsMiddlewareFactory` to allow constructing a dev tools middleware with a name parameter
Add `overReactReduxDevToolsMiddlewareFactory` which allows constructing redux dev tools with options …
> FEA-1258: Named redux devtools instances

- .github/workflows/dart_ci.yml
- CI was failing on Dart dev SDK (Dart 3), since Dart 3 doesn't support non-null-safe packages
- Example failure: https://github.com/Workiva/over_react/actions/runs/3952617728/jobs/6767917314
- I also noticed that we were skipping the `stable` SDK for over_react due to not allowing analyzer 1, which is no longer the case
- Stop running CI on Dart 3 since it'll never pass
- ~~Run main root CI on Dart stable as well~~
- I started down this path and then ran into a few more issues, which we can address in a follow-up
- CI passes …
> FED-675 Stop running plugin build on Dart 3 to fix CI

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FEA-1258: Named redux devtools instances](https://github.com/Workiva/over_react/pull/797)
* [FED-675 Stop running plugin build on Dart 3 to fix CI](https://github.com/Workiva/over_react/pull/798)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.7.0...Workiva:release_over_react_4.8.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.7.0...4.8.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/644995 …
> RM-171589 RM-171588 Release over_react 4.8.0

- doc/over_react_redux_documentation.md
There was a support question on how to properly integrate with the devtools for a module. It appears that these steps don't exist here yet.
- Add documentation from Devtools
- Introduce DevTools integration documentation
> FED-681: Add integration docs

- pubspec.yaml
Summary
---
This will raise the max allowed version of platform_detect to allow v2.
For more info, reach out to `#support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/platform_detect_2_raise_max`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/platform_detect_2_raise_max)
> Upgrade to platform_detect 2

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-681: Add integration docs](https://github.com/Workiva/over_react/pull/800)
* [Upgrade to platform_detect 2](https://github.com/Workiva/over_react/pull/802)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.8.0...Workiva:release_over_react_4.8.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.8.0...4.8.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_numbe …
> RM-176692 RM-176691 Release over_react 4.8.1

- app/over_react_redux/todo_client/pubspec.yaml
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
Summary
---
This will require analyzer 1.7.2+ and now that we're past analyzer 1.7.1
we can unpin the meta dependency. (We had restricted it to <1.7.0 in many places)
For more info, reach out to `#support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/analyzer1_unpin_meta`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/analyzer1_unpin_meta)
> Raise analyzer minimum & unpin meta

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Raise analyzer minimum & unpin meta](https://github.com/Workiva/over_react/pull/804)
* [FED-734 CI cleanup: remove failing stable config, add 2.18 config](https://github.com/Workiva/over_react/pull/805)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.8.1...Workiva:release_over_react_4.8.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.8.1...4.8.2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344 …
> RM-179069 RM-179068 Release over_react 4.8.2

- app/over_react_redux/todo_client/pubspec.yaml
Summary
---
This PR gets us closer to unblocking analyzer 2+ by allowing these new versions
once we upgrade built_redux, over_react, and handle json_serializable.
It raises the maximum for these packages:
- build_web_compilers
- build_test
- build_runner
For more info, reach out to `#support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/newer_build_dev_deps`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/newer_build_dev_deps)
> Allow newer build dependencies

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-756 Allow analyzer 2.x, fix analyzer plugin in newer SDKs](https://github.com/Workiva/over_react/pull/807)
* [Allow newer build dependencies](https://github.com/Workiva/over_react/pull/808)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.8.2...Workiva:release_over_react_4.8.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.8.2...4.8.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_na …
> RM-179762 RM-179761 Release over_react 4.8.3

- app/over_react_redux/todo_client/pubspec.yaml
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
This PR widens the allowable version ranges of dart_dev so that all repos at Workiva can consume dart_dev 4.0.0 without updating all repositories in lock step.
For more info, reach out to Timothy Steward or `#link23-state-of-the-dart-jam` on Slack.
[_Created by Sourcegraph batch change `Workiva/dart_dev_widen_ranges_v4`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/dart_dev_widen_ranges_v4)
> Prepare for dart_dev v4.0.0

- app/over_react_redux/todo_client/pubspec.yaml
- pubspec.yaml
Summary
---
Frontend Frameworks is updating dependencies!
This update will allow the nullsafe versions of w_common 3x 
by raising the max to < 4.0.0
For more info, visit `#lang-dart` in Slack.
[_Created by Sourcegraph batch change `Workiva/w_common_v3`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/w_common_v3)
> w_common v3 rollout - 1 of 2 raise max

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Prepare for dart_dev v4.0.0](https://github.com/Workiva/over_react/pull/815)
* [w_common v3 rollout - 1 of 2 raise max](https://github.com/Workiva/over_react/pull/816)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.8.4...Workiva:release_over_react_4.8.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.8.4...4.8.5
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_num …
> RM-184155 RM-184154 Release over_react 4.8.5

- app/over_react_redux/todo_client/pubspec.yaml
- pubspec.yaml
Summary
---
```
pubspec_codemod raise-min built_redux 8.0.0 --recursive
pubspec_codemod raise-min logging 1.0.0 --recursive
pubspec_codemod raise-min glob 2.0.0 --recursive
pubspec_codemod raise-min yaml 3.0.0 --recursive
pubspec_codemod raise-min archive 3.0.0 --recursive
pubspec_codemod raise-min xml 5.0.0 --recursive
pubspec_codemod raise-max io 2.0.0 --recursive
pubspec_codemod raise-max memoize 4.0.0 --recursive
pubspec_codemod raise-min intl 0.17.0 --recursive
pubspec_codemod raise-max intl 0.19.0 --recursive
pubspec_codemod raise-max color 4.0.0 --recursive
```
A passing CI is sufficient QA (means dependencies resolve and tests run and pass).
For more info, …
> Update dart dependencies

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-1255 Add [Suspense] Component](https://github.com/Workiva/over_react/pull/820)
* [Update dart dependencies](https://github.com/Workiva/over_react/pull/819)
Requested by: @kealjones-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.8.5...Workiva:release_over_react_4.9.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.8.5...4.9.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react …
> RM-188184 RM-188183 Release over_react 4.9.0

- app/over_react_redux/todo_client/pubspec.yaml
- pubspec.yaml
- test/over_react/component_declaration/builder_integration_tests/new_boilerplate/compact_hoc_syntax_integration_test.dart
Summary
---
Frontend Frameworks is updating dependencies.
This batch raises maximum versions for a set of 3rd party dependencies
in order to get the latest (nullsafe) versions of these packages.
```
pubspec_codemod raise-max codemirror 0.8.0 --recursive
pubspec_codemod raise-max csv 6.0.0 --recursive
pubspec_codemod raise-max diff_match_patch 0.5.0 --recursive
pubspec_codemod raise-max faker 3.0.0 --recursive
pubspec_codemod raise-max get_it 7.0.0 --recursive
pubspec_codemod raise-max redux 6.0.0 --recursive
pubspec_codemod raise-max redux_dev_tools 0.8.0 --recursive
pubspec_codemod raise-max redux_saga 4.0.0 --recursive
pubspec_codemod raise-max redux_thunk 0.5.0 --recursive
pubspec_codemod raise-max synchronized 4.0.0 --recursive
```
A test batch was done prior to verify that these new …
> Update 3rd party dependencies

- .github/workflows/dart_ci.yml
- app/over_react_redux/todo_client/pubspec.yaml
Summary
---
Frontend Frameworks is updating dependencies!
This update will allow the nullsafe/analyzer2 versions of test_html_builder.
We've made the v3 version safe to use a range for so that once the json_serializable 4
PRs land, everything can upgrade to analyzer 2.
Feel free to approve and merge this if CI passes.
Otherwise, someone from FEF will come by to approve and merge it.
Consumer tests and release notes are not needed.
For more info, visit `#support-frontend-dx` in Slack.
[_Created by Sourcegraph batch change `Workiva/test_html_builder_3`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/test_html_builder_3)
> Allow test_html_builder 3

- app/over_react_redux/todo_client/pubspec.yaml
Summary
---
```
pubspec_codemod raise-min w_intl 2.0.0 --recursive
pubspec_codemod raise-min json_schema 5.0.0 --recursive
pubspec_codemod raise-min intl 0.18.0 --recursive
pubspec_codemod raise-min color 3.0.0 --recursive
pubspec_codemod raise-min memoize 3.0.0 --recursive
```
A passing CI is sufficient QA (means dependencies resolve and tests run and pass).
For more info, reach out to Rob Becker in `#support-frontend-dx`
[_Created by Sourcegraph batch change `Workiva/raise_mins_5_31`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/raise_mins_5_31)
> Raise minimums

- .github/workflows/dart_ci.yml
Similar to https://github.com/Workiva/over_react/pull/725:
> From [the GitHub Actions docs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags):
> 
> > The * wildcard matches any character, but does not match slash (/).
> >
> > The ** wildcard matches any character including slash (/) in branch and tag names.
> 
> This PR updates to use ** instead of * so that GitHub Actions run on all branches, as opposed to skipping branches containing slashes.
it appears that `test_consume_` branch wildcard wasn't set up right, preventing it from being run on branches containing slashes.
For example, CI is not running on this test branch's original commit: https://github.com/Workiva/over_react/compare/master...test_consume_worki …
> FED-1568 Run CI on test_consume_ branches with slashes

- app/over_react_redux/todo_client/pubspec.yaml
- lib/src/builder/codegen/accessors_generator.dart
- lib/src/builder/codegen/component_factory_generator.dart
- lib/src/builder/codegen/typed_map_impl_generator.dart
- pubspec.yaml
- tools/analyzer_plugin/playground/pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
Summary
---
Frontend Frameworks is updating dependencies! Now that we can resolve to analyzer 2
we can raise the minimums of many dependencies were ranged to support both 
analyzer 1 and 2.
```
pubspec_codemod raise-min analyzer 2.0.0 --recursive
pubspec_codemod raise-min dependency_validator 3.0.0 --recursive
pubspec_codemod raise-min test_html_builder 3.0.0 --recursive
pubspec_codemod raise-min dart_style 2.0.0 --recursive
pubspec_codemod raise-min build_web_compilers 3.0.0 --recursive
pubspec_codemod raise-min build_test 2.0.0 --recursive
pubspec_codemod raise-min build_runner 2.0.0 --recursive
pubspec_codemod raise-min w_common 3.0.0 --recursive
pubspec_codemod raise-min w_common_tools 3.0.0 --recursive
pubspec_codemod raise-min uuid 3.0.0 --recursive
pubspec_codemod raise-min fluri …
```
> Update dev dependencies for analyzer 2

- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-1568 Run CI on test_consume_ branches with slashes](https://github.com/Workiva/over_react/pull/833)
* [FEDX-165 Upgrade to analyzer 5](https://github.com/Workiva/over_react/pull/835)
* [Update changelog for 4.10.1](https://github.com/Workiva/over_react/pull/838)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.10.0...Workiva:release_over_react_4.10.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.10.0...4.10.1 …
> RM-208146 RM-208145 Release over_react 4.10.1

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/.pubignore
- tools/analyzer_plugin/pubspec.yaml
There was a problem publishing 4.10.1 because of a nested test_fixture directory. Adding it to the .pubignore works around this issue.
```
Bad state: Unable to find the context to /Users/greglittlefield/workspaces/over_react2/tools/analyzer_plugin/test/test_fixtures/over_react_project/lib/analysis_warmup.dart
package:pub/src/dart.dart 119:5                           AnalysisContextManager._getExistingSession
package:pub/src/dart.dart 83:23                           AnalysisContextManager.parse
package:pub/src/dart.dart 102:16                          AnalysisContextManager.parseImportsAndExports
package:pub/src/validator/strict_dependencies.dart 35:45  StrictDependenciesValidator._findPackages
dart:async                                                _SyncStarIterator.moveNext …
```
> RM-213359 RM-213358 Release over_react 4.10.2

- lib/src/component/dom_components.dart
- lib/src/component/hooks.dart
- lib/src/component/react_dart_deprecated_forward_ref.dart
- lib/src/component/ref_util.dart
- lib/src/component_declaration/component_base_2.dart
- lib/src/over_react_redux/over_react_redux.dart
- pubspec.yaml
- test/over_react/util/component_debug_name_test.dart
- tools/analyzer_plugin/lib/src/diagnostic/exhaustive_deps.dart
- tools/analyzer_plugin/test/integration/diagnostics/exhaustive_deps_test_cases.dart
The not-yet-released react-dart 7.0.0 contains breaking changes that will need to be addressed in over_react before it's compatible.
We'll be making these compatibility changes proactively in order to make testing of the WIP react-dart 7.0.0 branch easier, and also to validate that we won't hit any blockers that require tweaks to the major changes in react-dart 7.0.0.
This PR won't be raising the upper bound of over_react's react-dart dependency, but once react-dart 7.0.0 is released, there shouldn't be any additional code changes necessary to raise that upper bound.
- Update usage of deprecated `react.main` to use `react.htmlMain`
- Add internal copy of react-dart's forwardRef, removed from react-dart 7.0.0 but still used by over_react's forwardRef
- over_react's `forwardRef` is …
> FED-1729 Prepare for react-dart 7.0.0

- CHANGELOG.md
Update the changelog in preparation for the 4.10.3 release, which will occur in a follow-up PR
Diff of this release: https://github.com/Workiva/over_react/compare/4.10.2...master
> Update changelog for 4.10.3

- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-1729 Prepare for react-dart 7.0.0](https://github.com/Workiva/over_react/pull/846)
* [Dart 2.19](https://github.com/Workiva/over_react/pull/848)
* [Update changelog for 4.10.3](https://github.com/Workiva/over_react/pull/849)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.10.2...Workiva:release_over_react_4.10.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.10.2...4.10.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTrigger …
> RM-213369 RM-213368 Release over_react 4.10.3

- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Allow react 7 and w_flux 3](https://github.com/Workiva/over_react/pull/853)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.10.3...Workiva:release_over_react_4.10.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.10.3...4.10.4
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_number=854)
> RM-222447 RM-222446 Release over_react 4.10.4

- analysis_options.yaml
- lib/src/builder/codegen/accessors_generator.dart
- lib/src/component/dom_components.dart
- lib/src/component_declaration/component_type_checking.dart
- lib/src/over_react_redux/over_react_redux.dart
- lib/src/util/component_debug_name.dart
- lib/src/util/promise_interop.dart
- lib/src/util/react_wrappers.dart
- pubspec.yaml
- test/over_react/util/css_value_util_test.dart
- test/over_react/util/prop_conversion_test.dart
- test/over_react/util/ref_test_cases.dart
- test/over_react_redux/value_mutation_checker_test.dart
- web/component1/src/demo_components/button_group.dart
- web/component2/src/demo_components/button_group.dart
I noticed our set of enabled lints is out of date, and may be missing some null-safety-related ones.
Also, not as many lints as we'd like have been upgraded to warnings.
- Use latest workiva_analysis_options recommended set, with some exceptions.
- Fix miscellaneous lints that were upgraded to warning, mostly unnecessary_cast lints
- CI passes
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual-testing …
> FED-1946 Null safety update lints

- .github/workflows/dart_ci.yml
- lib/src/builder/parsing/members_from_ast.dart
Formatting wasn't being run in CI - fix that and run ddev format
> Format master

- tools/analyzer_plugin/lib/src/util/boilerplate_assist_apis.dart
- tools/analyzer_plugin/test/integration/assists/add_create_ref_test.dart
- tools/analyzer_plugin/test/integration/assists/boilerplate_assist_utils.dart
- tools/analyzer_plugin/test/integration/assists/toggle_statefulness_test.dart
- tools/analyzer_plugin/test/integration/diagnostics/arrow_function_prop_test.dart
- tools/analyzer_plugin/test/integration/diagnostics/boilerplate_validator_test.dart
- tools/analyzer_plugin/test/integration/diagnostics/callback_ref_test.dart
- tools/analyzer_plugin/test/integration/diagnostics/create_ref_usage_test.dart
- tools/analyzer_plugin/test/integration/diagnostics/duplicate_prop_cascade_test.dart
- tools/analyzer_plugin/test/integration/diagnostics/exhaustive_deps_test.dart
- tools/analyzer_plugin/test/integration/diagnostics/forward_only_dom_props_to_dom_builders_test.dart
- tools/analyzer_plugin/test/integration/diagnostics/non_defaulted_prop_test.dart
- tools/analyzer_plugin/test/integration/test_bases/analysis_driver_test_base.dart
- tools/analyzer_plugin/test/integration/test_bases/server_plugin_contributor_test_base.dart
In a previous over_react release, we had to disable some diagnostics and assists that imported over_react builder code due to issues with the plugin running in unsound null safety.
As part of the over_react null-safety major release, we want to reenable those diagnostics, and have done so in v5_wip.
As a result to test refactors and other changes that were made while those contributors were disabled, there are test failures that need to be addressed, mostly to do with unique file names.
- Update `AnalysisDriverTestBase` to automatically substitute auto-generated filenames within source (using  `{{FILE_BASENAME_WITHOUT_EXTENSION}}`)
- Uncomment tests:
- test/integration/assists/toggle_statefulness_test.dart
- test/integration/diagnostics/boilerplate_validator_test.dart
- Fix all …
> FED-1763 Fix reenabled contributor tests 

- example/builder/src/functional_consumed_props.dart
- example/builder/src/props_mixin.dart
- lib/src/builder/codegen/accessors_generator.dart
- lib/src/builder/codegen/typed_map_impl_generator.dart
- lib/src/builder/parsing/members/props_and_state_util.dart
- lib/src/builder/parsing/meta.dart
- lib/src/component_declaration/annotations.dart
- lib/src/component_declaration/component_base.dart
- lib/src/component_declaration/flux_component.over_react.g.dart
- lib/src/over_react_redux/over_react_redux.over_react.g.dart
- lib/src/util/react_util.dart
- test/over_react/component_declaration/builder_integration_tests/new_boilerplate/null_safety_validate_required_props_test.dart
- test/over_react/component_declaration/ui_props_self_typed_extension_test.over_react.g.dart
Consumers can currently opt props they declare out of required prop vaildation, by annotating individual props with `@disableRequiredPropValidation`, but they can't opt out of validation for props in other mixins.
This becomes an issue for certain use-cases, primarily the declaration of wrapper components.
For example:
```
mixin FooProps on UiProps {
late String requiredProp1AlwaysSetInWrapper;
late String requiredProp2;
}
UiFactory<FooProps> Foo = uiFunction((props) {
// ...
}, _$FooConfig);
class WrapperProps = UiProps with FooProps, WrapperPropsMixin;
UiFactory<WrapperProps> Wrapper = uiForwardRef((props, ref) {
return (Foo()
..requiredProp1AlwaysSetInWrapper = 'foo'
..addProps(props.getPropsToForward(exclude: {WrapperPropsMixin}))
..ref = ref
)();
}, _$WrapperConfig);
```
`Wrapper` …
> FED-2015 Opt out of required props from mixin declaration

- example/builder/src/functional_consumed_props.dart
- lib/src/builder/codegen/typed_map_impl_generator.dart
- lib/src/builder/parsing/members/props_and_state_util.dart
- lib/src/component_declaration/annotations.dart
- lib/src/component_declaration/component_base.dart
- test/over_react/component_declaration/builder_integration_tests/new_boilerplate/null_safety_validate_required_props_test.dart
- tools/analyzer_plugin/lib/src/util/prop_declarations/required_props.dart
- tools/analyzer_plugin/playground/web/missing_required_props.dart
- tools/analyzer_plugin/test/integration/diagnostics/missing_required_prop_test.dart
- tools/analyzer_plugin/test/unit/util/prop_declaration/required_props_test.dart
- tools/analyzer_plugin/test/unit/util/prop_declaration/shared_test_source.dart
We should make the `disableRequiredPropValidation` naming consistent across all the disabling options
- Rename `ignoreRequiredProps` to `disableRequiredPropValidation` in @Props annotation
> FED-2154 Rename `ignoreRequiredProps` to `disableRequiredPropValidation` in @Props annotation

- CHANGELOG.md
- lib/src/component_declaration/annotations.dart
Backpatch new annotation arg to over_react v4 (they won't do anything until v5) so that we can use them in wdesk_sdk (and probably other places) when preparing for the migration to over_react v5
- Backpatch disableRequiredPropValidation annotation arg
> FED-2046 Backpatch disableRequiredPropValidation annotation arg

- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-2046 Backpatch disableRequiredPropValidation annotation arg](https://github.com/Workiva/over_react/pull/879)
* [react 7 and w_flux 3 step 2](https://github.com/Workiva/over_react/pull/857)
* [Rollout react_testing_library 3](https://github.com/Workiva/over_react/pull/861)
* [Format master](https://github.com/Workiva/over_react/pull/867)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.10.4...Workiva:release_over_react_4.11.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.10.4...4.11.0
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/64499 …
> RM-223686 RM-223685 Release over_react 4.11.0

- CHANGELOG.md
- lib/src/builder/parsing/members/props_and_state_util.dart
- test/over_react/component_declaration/builder_integration_tests/new_boilerplate/null_safety_validate_required_props_test.dart
- test/over_react_component_declaration_test.dart
- test/over_react_component_declaration_test.html
Mistakes have been made. We need to override the @Prop annotation creation so it doesn't throw an [incomplete meta error](https://github.com/Workiva/wdesk_sdk/actions/runs/7670962219/job/20908310965?pr=12230)
- Catch disableRequiredPropValidation arg and remove it from the meta so no error is thrown
- Add a test
> FED-2164 Fix disableRequiredPropValidation annotation and add test

- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-2164 Fix disableRequiredPropValidation annotation and add test](https://github.com/Workiva/over_react/pull/881)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.11.0...Workiva:release_over_react_4.11.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.11.0...4.11.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_number=883)
> RM-236454 RM-236453 Release over_react 4.11.1

- lib/src/component_declaration/component_base.dart
- test/over_react/component_declaration/builder_integration_tests/new_boilerplate/null_safety_validate_required_props_test.dart
- test/over_react/component_declaration/component_base_test.dart
I noticed in UiProps that we only perform required prop asserts in `call`, but not in `build`.
- Move shared asserts for required prop validation and `componentFactory != null` into shared function, `_sharedAsserts`, and call from both `call` and `build`.
- Add tests for required prop validation in `build`
- Add missing test case for children validation in `build`
- CI passes …
> FED-2167 Validate required props in UiProps.build

- CHANGELOG.md
- lib/src/util/context.dart
- lib/src/util/context.over_react.g.dart
- test/over_react/component/context_test.dart
- test/over_react/component/fixtures/context_provider_component.dart
- test/over_react/component/fixtures/context_provider_component.over_react.g.dart
Dependent on https://github.com/Workiva/over_react/pull/875
---
When looking at context APIs in https://github.com/Workiva/over_react/pull/875, I realized that the value prop on Provider wasn't considered required (by runtime checks and static analysis), even though it should be. It was also `TValue?`, when it should have been `TValue`.
`ProviderProps.value` was previously implemented as a custom getter/setter, and required props can only be declared in generated props mixins.
This refactor moves away from manual implementations to relying on generated code, cleaning up certain aspects, but unfortunately the implementations are still pretty custom and messy.
- Move declaration of `ProviderProps.value` from a custom getter/setter to a `late` required, potentially non-nullable (when as …
> FED-2139 Fix ProviderProps.value being optional/nullable, refactor internal impl

- lib/src/component_declaration/flux_component.dart
- test/over_react/component_declaration/flux_component_test/component2/flux_component_test.dart
- test/over_react/component_declaration/flux_component_test/component2/unsound_flux_component_test.dart
- test/over_react/component_declaration/flux_component_test/flux_component_test.dart
- test/over_react/component_declaration/flux_component_test/unsound_flux_component_test.dart
- test/over_react_component_declaration_non_null_safe_test.dart
When using mocked stores in flux components, consumers currently get errors like this:
```
NoSuchMethodError: method not found: 'cancel$0' on null
/packages/over_react/src/component_declaration/flux_component.dart 329:35  _FluxUiComponent2.UiComponent2.BatchedRedraws._FluxComponentMixin.componentWillUnmount.<fn>
/_internal/js_runtime/lib/js_array.dart 322:7                              Interceptor.forEach
/packages/react/src/react_client/dart_interop_statics.dart 289:9           ReactDartInteropStatics2.handleComponentWillUnmount.<fn>
/async/zone.dart 1398:12                                                   StaticClosure._rootRun
/async/zone.dart 1299:34                                                   _CustomZone.run
/packages/react/src/react_client/dart_interop_statics.dart 288:7 …
```
> FED-2194 Fix Flux components when using mocked stores

- .github/workflows/dart_ci.yml
- tools/analyzer_plugin/lib/src/async_plugin_apis/diagnostic.dart
- tools/analyzer_plugin/lib/src/component_usage.dart
- tools/analyzer_plugin/lib/src/diagnostic/boilerplate_validator.dart
- tools/analyzer_plugin/lib/src/diagnostic/exhaustive_deps.dart
- tools/analyzer_plugin/lib/src/diagnostic/visitors/non_static_reference_visitor.dart
- tools/analyzer_plugin/test/integration/diagnostics/boilerplate_validator_test.dart
- tools/analyzer_plugin/test/unit/util/ast_util_test.dart
- tools/analyzer_plugin/test/unit/util/component_usage_test.dart
- tools/analyzer_plugin/test/unit/util/non_null_safe/ast_util_test.dart
- tools/analyzer_plugin/test/unit/util/non_null_safe/component_usage_test.dart
- tools/analyzer_plugin/tool/doc.dart
I kept seeing analysis warnings locally in the analyzer plugin directory, and figured they must be only happening locally, otherwise they'd be failing CI.
Turns out, we weren't analyzing the analyzer plugin in CI 😅.
- Add CI step to run analysis on the analyzer_plugin directory
- Fix all warnings
- CI runs analysis and fails on warnings before they were fixed in https://github.com/Workiva/over_react/actions/runs/7908062168/job/21586466107
- CI passes on latest commit
[contributing-review-types]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.m …
> FED-2239 Analyze analyzer_plugin in CI, fix warnings

- lib/src/over_react_redux/over_react_flux.dart
- test/over_react/component_declaration/flux_component_test/component2/unsound_flux_component_test.dart
- test/over_react/component_declaration/flux_component_test/unsound_flux_component_test.dart
Similar to https://github.com/Workiva/over_react/pull/885, there is one more case where we should cast a store value as nullable to account for mock stores in unsound null safety
```
TypeError: Cannot read properties of null (reading 'whenComplete')
```
- cast didDispose as nullable
- Add tests
> FED-2041 Fix whenComplete null error

- lib/src/over_react_redux/devtools/middleware.dart
When testing v5_wip, we discovered a leak originating from the log listener in `_OverReactReduxDevToolsMiddleware`'s constructor.
`dart2js` was compiling the old log listener as a closure, `_OverReactReduxDevToolsMiddleware_closure`, which retained a reference to  `_OverReactReduxDevToolsMiddleware` in order to access the instance variable `log`. However, retaining the middleware instance also caused it and its store to be leaked.
<details>
<summary> dart2js-compiled code, for reference: </summary>
```js
// The middleware class, which constructs the closure in its constructor
A._OverReactReduxDevToolsMiddleware.prototype = {
_OverReactReduxDevToolsMiddleware$1(options) {
var e, t2, exception, _this = this, _null = null,
windowConsole = window.console,
t1 = _this.log; …
```
> FED-2250 Fix Redux dev tools middleware leak in v5_wip

- lib/src/builder/codegen/accessors_generator.dart
- lib/src/component/_deprecated/error_boundary_mixins.over_react.g.dart
- lib/src/component/abstract_transition.over_react.g.dart
- lib/src/component/error_boundary.over_react.g.dart
- lib/src/component/with_transition.over_react.g.dart
- lib/src/component_declaration/component_base.dart
- lib/src/component_declaration/component_base_2.dart
- lib/src/component_declaration/flux_component.over_react.g.dart
- lib/src/over_react_redux/over_react_flux.over_react.g.dart
- lib/src/over_react_redux/over_react_redux.over_react.g.dart
- lib/src/over_react_redux/redux_multi_provider.over_react.g.dart
- lib/src/util/context.over_react.g.dart
- test/over_react/component/fixtures/context_provider_component.over_react.g.dart
- test/over_react/component/fixtures/dummy_component.over_react.g.dart
- test/over_react/component/fixtures/prop_typedef_fixtures.over_react.g.dart
- test/over_react/component_declaration/builder_integration_tests/backwards_compatible/required_accessor_integration_test.dart
- test/over_react/component_declaration/builder_integration_tests/component2/null_safe_accessor_integration_test.over_react.g.dart
- test/over_react/component_declaration/builder_integration_tests/component2/required_accessor_integration_test.dart
- test/over_react/component_declaration/builder_integration_tests/component2/required_accessor_integration_test.over_react.g.dart
- test/over_react/component_declaration/builder_integration_tests/new_boilerplate/null_safety_validate_required_props_test.dart
- test/over_react/component_declaration/builder_integration_tests/null_safe_accessor_integration_test.over_react.g.dart
- test/over_react/component_declaration/builder_integration_tests/required_accessor_integration_test.dart
- test/over_react/component_declaration/builder_integration_tests/required_accessor_integration_test.over_react.g.dart
- test/over_react/component_declaration/ui_props_self_typed_extension_test.over_react.g.dart
Based on [this discussion](https://github.com/Workiva/wdesk_sdk/pull/12266#discussion_r1496136886) - we need to turn off prop type warnings for props that have been ignored in `@Props(disableRequiredPropValidation)`
- Coniditionally turn off prop type warnings
> FED-2267 Turn off prop type warnings for ignored prop validation

- CHANGELOG.md
- lib/src/util/react_util.dart
- test/over_react/util/react_util_test.dart
While testing the v5_wip branch within certain large, unsound applications, we encountered a significant slowdown in dart2js compilation speed.
We identified `UiPropsMapView` implementing `UiProps` as the main trigger of the issue, and changing it to extend `UiProps` instead works around the slowdown.
We'll be following up shortly with a lot more info in a dart-lang/sdk issue, but in the meantime, we know that this workaround works.
- Apply workaround: have `UiPropsMapView` extend `UiProps` instead of just implementing it
- Update changelog
- Add a little more test coverage to ensure UiPropsMapView reads to and writes from the underlying backing map
Please …
> FED-2294 Work around dart2js compilation slowdown by not implementing UiProps

- .gitignore
- tools/analyzer_plugin/lib/src/diagnostic/unsafe_required_prop_access.dart
- tools/analyzer_plugin/lib/src/plugin.dart
- tools/analyzer_plugin/lib/src/util/is_component_props.dart
- tools/analyzer_plugin/lib/src/util/is_props_from_render.dart
- tools/analyzer_plugin/playground/web/unsafe_required_props_access.dart
- tools/analyzer_plugin/test/integration/diagnostics/unsafe_required_prop_access_test.dart
- tools/analyzer_plugin/test/integration/test_bases/analysis_driver_test_base.dart
- tools/analyzer_plugin/test/unit/util/is_props_from_render_test.dart
- tools/analyzer_plugin/test/util/shared_analysis_context.dart
While required late props are validated to be present when a component is rendered, there are cases where they won't always be present. For example, "partial" props objects that represent a subset of a component's props.
If required late props are accessed without being set, they'll throw at runtime, and there's currently no static analysis that prevents consumers from doing so, or notifies them that they're doing something unsafe.
So, we want to help prevent consumers from unsafely accessing required late props.
- Add new `UnsafeRequiredPropAccessDiagnostic` that warns whenever required props are accessed in an unsafe manner
- Lints when accessing required props on objects that aren't props a component was rendered with
- Exceptions where we don't lint
- Accesses on callback args in …
> FED-2156 Unsafe required props lint

- tools/analyzer_plugin/lib/src/diagnostic/missing_required_prop.dart
- tools/analyzer_plugin/lib/src/util/prop_declarations/props_set_by_factory.dart
- tools/analyzer_plugin/lib/src/util/weak_map.dart
- tools/analyzer_plugin/playground/web/missing_required_props.dart
- tools/analyzer_plugin/test/integration/diagnostics/missing_required_prop_test.dart
- tools/analyzer_plugin/test/unit/util/prop_declaration/props_set_by_factory_test.dart
- tools/analyzer_plugin/test/unit/util/weak_map_test.dart
- tools/analyzer_plugin/test/util/over_react_builder.dart
There are some common use-cases where consumers declare BuilderOnlyUiFactory functions that are to be used as the main entrypoint of their components, and assign required props within them.
For example, the custom `FooComponents.content` factory:
```dart
UiFactory<FooProps> Foo = ...;
class FooProps = UiProps with FluxUiPropsMixin<...>, ...;
class FooComponents {
...
FooProps content() => Foo()
..store = store
..actions = actions;
}
```
Currently, the `missing_required_prop` lint occurs when using that factory, even though it sets required props:
```dart
void renderApp(FooComponents components) {
react_dom.render(components.content()(), mountNode);
//               ^^^^^^^^^^^^^^^^^^^^
// warning: over_react_late_required_prop 
//   Missing required late prop 'actions' from …
```
> FED-2432: Don't lint required props that are set in factory

- pubspec.yaml
In order to do a simultaneous major release of this library alongside over_react_test, we had to release 5.0.0 using a dependency override.
Remove the dependency override now that over_react_test 3 is released.
> Use over_react_test 3 release

- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Use over_react_test 3 release](https://github.com/Workiva/over_react/pull/901)
* [Add changelog entry for 5.0.1](https://github.com/Workiva/over_react/pull/902)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.0.0...Workiva:release_over_react_5.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/5.0.0...5.0.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_number=903)
> RM-250109 RM-250108 Release over_react 5.0.1

- app/over_react_redux/todo_client/pubspec.yaml
- tools/analyzer_plugin/playground/pubspec.yaml
This PR widens the allowable version ranges to over_react 5.0.0 / over_react_test 3.0.0 so that all repos at Workiva can consume without updating all repositories in lock step.
These major versions are a critical step towards unlocking null safety in Workiva's Dart ecosystem - and **have already been tested and verified as safe for consumption** using the `over_react` test PR [listed in this SourceGraph batch](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/over_react_5_test).
Due to the exhaustive consumption testing already performed in this repository by the FED team prior to releasing over_react 5.0.0, **these changes can be merged without approval from a FED team member.**
---
For more information about these changes, see [this …
> Allow consumption of null-safe over_react and over_react_test versions

- CHANGELOG.md
- lib/src/component/hooks.dart
- lib/src/util/context.dart
Consumers of `useRef`/`createContext` setting an initial / default value should use `useRefInit` / `createContextInit` instead to prepare for null safety.
Formally deprecate the optional `initialValue` / `defaultValue` args in the aforementioned hooks.
> FED-2136 Deprecate optional value argument in useRef hook & createContext fn

- tools/analyzer_plugin/lib/src/util/prop_declarations/get_all_props.dart
- tools/analyzer_plugin/test/unit/util/prop_declaration/get_all_props_test.dart
- tools/analyzer_plugin/test/unit/util/prop_declaration/required_props_test.dart
- tools/analyzer_plugin/test/unit/util/prop_declaration/shared_test_source.dart
Props declared directly in legacy abstract props classes (with `@AbstractProps`) weren't being picked up properly in `getAllProps`.
- Update `getAllProps` to not skip over `@AbstractProps`-annotated classes
- Add regression tests
This bugfix will cause any required props declared directly in abstract props classes to start linting if they're missing. There aren't any of these in over_react `lib/`, nor are there any that would currently be affected within the Workiva ecosystem, so this change should have minimal risk of breaking something.
- CI passes
- New regression test failed before the issue was fixed ([CI …
> FED-2609 Fix getAllProps not picking up props from AbstractProps classes

- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-2136 Deprecate optional value argument in useRef hook & createContext fn](https://github.com/Workiva/over_react/pull/909)
* [Allow consumption of null-safe over_react and over_react_test versions](https://github.com/Workiva/over_react/pull/905)
* [FEDX-689 : GHA OSS changes](https://github.com/Workiva/over_react/pull/908)
* [FED-2040 Placeholder null safety migration guide](https://github.com/Workiva/over_react/pull/910)
* [FED-2558 Add instructions for using a fork of the migrator tool](https://github.com/Workiva/over_react/pull/912)
* [FED-2609 Fix getAllProps not picking up props from AbstractProps classes](https://github.com/Workiva/over_react/pull/913)
* [Replace mockito with …
> RM-250128 RM-250127 Release over_react 5.1.0

- .github/workflows/dart_ci.yml
The 5.1.0 release failed to run a build on the tag commit because we were missing a crucial line in our github workflow file.
This adds the tag, and we can release this as a 5.1.1 patch
> Run CI on release tag commits

- doc/null_safety/null_safe_migration.md
The null safety migration documentation needs to be updated. This PR updates it with more helpful information for consumers.
> FED-2960 Update the null safety migration documentation

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-1945 Support prop conversion in OverReact to simplify RMUI converted props](https://github.com/Workiva/over_react/pull/920)
* [Remove publish action that always fails due to dry run warnings](https://github.com/Workiva/over_react/pull/925)
* [FED-2854 Fix num keys incorrectly linting as not unique](https://github.com/Workiva/over_react/pull/928)
* [FED-2855 Fix Analyzer Plugin error when typing keys](https://github.com/Workiva/over_react/pull/930)
* [FED-2960 Update the null safety migration documentation](https://github.com/Workiva/over_react/pull/932)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.1.2...Workiva:release_over_react_5.2.0 …
> RM-262845 RM-262844 Release over_react 5.2.0

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-2979 Clean up dependency ranges, clean out the lint trap](https://github.com/Workiva/over_react/pull/934)
* [FED-3009 Update migration guide with required props codemod instructions](https://github.com/Workiva/over_react/pull/935)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.2.0...Workiva:release_over_react_5.2.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/5.2.0...5.2.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/644 …
> RM-272801 RM-272800 Release over_react 5.2.1

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-2299 Utilize new ReactNode typedef](https://github.com/Workiva/over_react/pull/937)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.2.1...Workiva:release_over_react_5.3.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/5.2.1...5.3.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_number=938)
> RM-276972 RM-276971 Release over_react 5.3.0

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-2034: Analyzer plugin required props validation: check forwarded props](https://github.com/Workiva/over_react/pull/944)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.3.0...Workiva:release_over_react_5.3.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/5.3.0...5.3.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_number=945)
> RM-278870 RM-278869 Release over_react 5.3.1

- tools/analyzer_plugin/lib/src/assist/refs/add_create_ref.dart
- tools/analyzer_plugin/lib/src/diagnostic/invalid_child.dart
- tools/analyzer_plugin/lib/src/diagnostic/missing_required_prop.dart
- tools/analyzer_plugin/lib/src/util/null_safety_utils.dart
- tools/analyzer_plugin/test/integration/diagnostics/non_null_safe/missing_required_prop_test.dart
The over_react analyzer plugin is always supposed to lint for missing required props, unless they're on props declared in non-null safe libraries.
There's a bug in this conditional that instead checks the language version of the library the component is consumed in, as opposed to the library the component is declared in.
This prevents consumers from getting static warnings in cases where they'll get runtime errors.
For example, expected behavior:
```dart
//@dart=2.11
import 'package:null_safe_package/has_required.dart';
class NonNullSafeMixesInRequiredProps = UiProps with HasRequiredProps;
UiFactory<NonNullSafeMixesInRequiredProps>  NonNullSafeMixesInRequiredProps = ...;
example() {
// Should lint about missing required props
HasRequired()();
// Should not lint, because this props class …
```
> FED-3159 Fix required prop null-safe-conditional linting

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-3159 Fix required prop null-safe-conditional linting](https://github.com/Workiva/over_react/pull/948)
* [FED-3160 Improve null safety docs and messages for wrapper components and connect ](https://github.com/Workiva/over_react/pull/949)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.3.1...Workiva:release_over_react_5.3.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/5.3.1...5.3.2 …
> RM-284056 RM-284055 Release over_react 5.3.2

- .github/workflows/dart_ci.yml
- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.3.2...Workiva:release_over_react_5.3.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/5.3.2...5.3.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_number=951)
> RM-285731 RM-285730 Release over_react 5.3.3

- doc/null_safety/null_safe_migration.md
In the null safety migration guide [prop requiredness](https://github.com/Workiva/over_react/blob/master/doc/null_safety/null_safe_migration.md#prop-requiredness-and-nullability) section, what're supposed to be newlines in the mermaid diagram are rendering as `\n`.
Replace `\n` with `<br>` to fix newline rendering
- Open docs in GitHub and verify the diagram's newlines render as intended: https://github.com/Workiva/over_react/blob/2a0ed809cdb99da18fa6d32d20697843c281855b/doc/null_safety/null_safe_migration.md#prop-requiredness-and-nullability …
> FED-3197 Fix mermaid diagram newlines in migration guide

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-3114: Lazy](https://github.com/Workiva/over_react/pull/941)
* [FED-3197 Fix mermaid diagram newlines in migration guide](https://github.com/Workiva/over_react/pull/952)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.3.3...Workiva:release_over_react_5.4.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/5.3.3...5.4.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=W …
> RM-285743 RM-285742 Release over_react 5.4.0

- .github/workflows/dart_ci.yml
- lib/src/builder/codegen/typed_map_impl_generator.dart
- lib/src/builder/parsing/ast_util.dart
- lib/src/builder/parsing/declarations.dart
- pubspec.yaml
- test/vm_tests/builder/parsing/ast_util/classish_declaration_test.dart
- test/vm_tests/builder/parsing/ast_util_test.dart
Depends on https://github.com/Workiva/over_react/pull/958
over_react currently allows analyzer 5.x, but not analyzer 6.x, which prevents newer versions of other packages from being pulled in.
We were previously blocked on supporting analyzer 6.x since it can only be used in Dart 3, but now we support Dart 3!
- Raise analyzer upper bound to allow 6.x
- Add 6.x to CI matrix that validates behavior under different analyzer majors
- Fix usages of deprecated `NamedType.name`, which was removed in analyzer 6.0.0
- This getter included the name and any import prefix, and was deprecated in favor of the following getters:
- `name2` (the name without the prefix)
- `importPrefix` (just the prefix)
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) …
> FED-3255 Allow analyzer 6.x

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-3236 Docs: add more details around connect vs hooks](https://github.com/Workiva/over_react/pull/957)
* [FED-3254 Officially support Dart 3](https://github.com/Workiva/over_react/pull/958)
* [FED-3255 Allow analyzer 6.x](https://github.com/Workiva/over_react/pull/960)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.4.0...Workiva:release_over_react_5.4.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/5.4.0...5.4.1 …
> RM-288897 RM-288896 Release over_react 5.4.1

- doc/null_safety/null_safe_migration.md
Update the docs on the migrator companion codemod to take into account the changes from the following codemods:
- https://github.com/Workiva/over_react_codemod/pull/297
-  https://github.com/Workiva/over_react_codemod/pull/298
- https://github.com/Workiva/over_react_codemod/pull/302
- Update docs
> FED-3249 Update docs about migrator companion codemod

- app/over_react_redux/todo_client/pubspec.yaml
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
This PR raises the min version of meta to 1.16.0. Passing CI
should be sufficient for QA, so feel free to review and merge this once CI completes.
For more info, reach out to `#support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/meta_raise_min_v1_16_0_really`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/meta_raise_min_v1_16_0_really)
> Raise the meta dependency min to v1.16.0

- lib/src/component_declaration/disposable_manager_proxy.dart
- pubspec.yaml
We intend to make a null-safety related change to w_common that is technically a breaking change in which over_react is the only consumer impacted.  Rather than release a major, we intend to release the change as a minor and prepare an update pr to over_react ahead of time. This is that pr.
- Update `manageAndReturnTypedDisposable` to reflect the updated nullable bound, and that impacts over_react because the method is overridden.
- Update `manageAndReturnTypedDisposable` to reflect the updated nullable bound from w_common
- relied on static analysis in CI …
> FEDX-1997: adjust `manageAndReturnTypedDisposable`

- pubspec.yaml
- test/over_react/component/context_test.dart
- test/over_react/component/error_boundary/shared_stack_tests.dart
- tools/analyzer_plugin/lib/src/diagnostic/exhaustive_deps.dart
- tools/analyzer_plugin/lib/src/diagnostic/missing_required_prop.dart
- tools/analyzer_plugin/pubspec.yaml
- tools/analyzer_plugin/tool/doc_generation_utils/visitor.dart
A couple test updates in order to get tests passing on React 18
- Update context tests similar to react-dart since changedBits doesn't work on React 18
- Update ErrorBoundary prod tests to use `react_dom.render` to avoid RTL error about using `act` in prod builds
- Update analyzer plugin to fix analysis errors on Dart 3 (these were also happening in master)
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md# …
> FED-3274 React 18 Prep

- tools/analyzer_plugin/dart_dependency_validator.yaml
- tools/analyzer_plugin/pubspec.yaml
Updates the pubspec.yaml configuration of dependency_validator to use the updated dart_dependency_validator configuration
For any questions, please reach out to #support-frontend-dx
[_Created by Sourcegraph batch change `Workiva/dart_dependency_validator_config`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/dart_dependency_validator_config)
> dart_dependency_validator_config

- lib/src/component_declaration/component_type_checking.dart
- test/over_react/component_declaration/component_type_checking_test.dart
`getProps(child, traverseWrappers: true)` incorrectly raises the following assertion error, only in dart2js (when using `--enable-asserts`):
```
Assertion failed: "`type` should be a valid component type (and not null or a type alias)."
/_internal/js_runtime/lib/js_helper.dart 1128:37                                                        Object.wrapException
/_internal/js_runtime/lib/js_helper.dart 2596:3                                                         Object.assertThrow
/packages/over_react/src/component_declaration/component_type_checking.dart 175:3                       Object.getComponentTypeMeta
/packages/over_react/src/util/react_wrappers.dart 143:28                                                Object.getProps
```
For Fragment ReactElements (`Fragment()(...)`), `.type` is …
> FED-3585 Fix fragment type check assert

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Revert "FEDX-1997: adjust `manageAndReturnTypedDisposable`"](https://github.com/Workiva/over_react/pull/966)
* [dart_dependency_validator_config](https://github.com/Workiva/over_react/pull/969)
* [FED-3274 React 18 Prep](https://github.com/Workiva/over_react/pull/973)
* [FED-3585 Fix fragment type check assert](https://github.com/Workiva/over_react/pull/974)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.4.2...Workiva:release_over_react_5.4.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/5.4.2...5.4.3
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/644995 …
> RM-298715 RM-298714 Release over_react 5.4.3

- lib/src/builder/builder.dart
The over_react builder fails to generate code when there are analysis errors in the source file, regardless of their severity, due to the short-circuit [here](https://github.com/Workiva/over_react/blob/5c028ef0f13bfd3e835c3e35d7472c9e5d3eb77d/lib/src/builder/builder.dart#L246-L253).
Historically, this hasn't been an issue since we do a non-resolved AST parse, and most infos/warnings require resolved AST.
However, apparently the warning for bad doc comment directives comes through in unresolved AST.
This causes failures to emit several over_react.g.dart files due to doc comments like this:
```
/// Optional props to forward to the `ClickAwayListener` component
/// when {@link disableClickAwayListener } is `false`.
```
and also outputs this warning:
```
[WARNING] over_react:overReactBuilder …
```
> FED-3476 Adjust builder for Dart 3

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [FED-3476 Adjust builder for Dart 3](https://github.com/Workiva/over_react/pull/972)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.4.3...Workiva:release_over_react_5.4.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/5.4.3...5.4.4
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_number=976)
> RM-323591 RM-323590 Release over_react 5.4.4

- doc/.pubignore
- snippets/.pubignore
- tools/analyzer_plugin/doc/.pubignore
The over_react package currently publishes all the repo's contents, including images in various non-production documentation-esque directories, a couple of which are pretty large.
I noticed the last couple times I published that there are warnings for this.
We should avoid unnecessarily large assets in our published package, and also fix warnings so that we have less noise when publishing.
Stop publishing directories that contain images, none of which are needed when consuming the package:
- docs
- snippets
- tools/analyzer_plugin/docs
We could potentially extend this to other directories like examples/tests, but it'd be diminishing returns since those files are smaller and compress better. And it seems like the convention is to keep files published unless they're causing issues—see info …
> FED-3730 Exclude images when publishing, reducing tarball from 5.9MB to 1.3MB

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Consume react-dart 7.3.0](https://github.com/Workiva/over_react/pull/978)
* [FED-3730 Exclude images when publishing, reducing tarball from 5.9MB to 1.3MB](https://github.com/Workiva/over_react/pull/979)
* [FED-3977 Allow analyzer 7](https://github.com/Workiva/over_react/pull/982)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.4.4...Workiva:release_over_react_5.4.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/5.4.4...5.4.5 …
> RM-326642 RM-326641 Release over_react 5.4.5

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- CHANGELOG.md
We should set up gha-dart-oss so we can:
- take advantage of shared workflows
- use the publish workflow to auto-publish on merge 🎉
> FED-4063 Set up gha-dart-oss

- pubspec.yaml
Consume [react-dart 7.3.1](https://github.com/Workiva/react-dart/releases/tag/7.3.1)
* [FED-3927 Fix failing test on Dart 3](https://github.com/Workiva/react-dart/pull/420)
* [no_entrypoint_imports](https://github.com/Workiva/react-dart/pull/421)
* [FED-4060 Set up gha-dart-oss](https://github.com/Workiva/react-dart/pull/422)
* [RM-327375 Release react-dart 7.3.1](https://github.com/Workiva/react-dart/pull/423)
Requested by: @btr-rmconsole-3
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/4948379952742400/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4948379952742400/?repo_name=Workiva% …
> Consume react-dart 7.3.1

- CHANGELOG.md
- pubspec.yaml
- tools/analyzer_plugin/pubspec.yaml
* [Rollout React 18 to tests and example apps](https://github.com/Workiva/over_react/pull/984)
* [no_entrypoint_imports](https://github.com/Workiva/over_react/pull/985)
* [FED-4063 Set up gha-dart-oss](https://github.com/Workiva/over_react/pull/986)
* [Consume react-dart 7.3.1](https://github.com/Workiva/over_react/pull/987)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/5.4.5...Workiva:release_over_react_5.4.6
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/5.4.5...5.4.6
This pull request …
> RM-343175 RM-343174 Release over_react 5.4.6
